### ISSUE TITLE
Erreur enregistrement certificat

### ISSUE THREAD

**Issue by pingax** [dbarzin/mercator#102]
Bonjour, 

Lors de la création d'un nouveau certificat (/admin/certificates), bien que tous les champs soient remplis, après validation du formulaire, une erreur de requête SQL est levée : 

`Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'field list' (SQL: insert into `certificates` (`name`, `type`, `description`, `start_validity`, `end_validity`, `status`, `updated_at`, `created_at`)`

Je confirme l'absence de cette colonne `status` dans la base de données : 

![image](https://user-images.githubusercontent.com/51684/167662013-a6022a8f-9202-4725-bf0a-176e6ed285f7.png)

J'utilise la version `Release Maturity 1`, et non la version clonée du dépôt. La migration `2022_02_22_32654_add_cert_status.php` n'y est effectivement pas présente. 

J'espère avoir été clair :) et merci pour ce bel outil !

**Comment by dbarzin** [comment]
Bonjour,
La fichier manquant a été ajouté dans la version Release Maturity 1b.
Merci,
Didier

**Comment by pingax** [comment]
Bonjour, 

C'est bon, la migration a été effectuée, il n'y a plus d'erreur :)

Anthony
