### ISSUE TITLE
 Vue Métier - Information - Impossible d'afficher une information 

### ISSUE THREAD

**Issue by etienne-64** [dbarzin/mercator#105]
Après appui sur le bouton "Afficher" ou clic sur le nom de l'information (lien), affichage du message d'erreur ci-dessous.

![image](https://user-images.githubusercontent.com/10651729/168547419-083bff05-5c1b-4673-a6e0-ab1d4265c658.png)

**Comment by dbarzin** [comment]
Bonjour
Utilises-tu la dernière version du projet ?
Ce problème ne semble plus présent.
Cordialement,
Didier

**Comment by etienne-64** [comment]
Bonjour Didier,
Dernier pull le 12/05, v1.b 
Cordialement,
Stéphane

**Comment by dbarzin** [comment]
Peux-tu prendre la dernier version de la branche master en faisant

  git clone github.com/dbarzin/mercator

et pour mettre à jour

    git pull origin master

Merci,
Didier

**Comment by jfcjm** [comment]
D'après la navigation web du dépôt, le défaut n'est pas encore corrigé : 

[show.blade.php v1.b](https://github.com/dbarzin/mercator/blob/v1.b/resources/views/admin/information/show.blade.php)

**Comment by dbarzin** [comment]
Corrigé dans la branche master.
Merci,
Didier

**Comment by etienne-64** [comment]
OK pour moi. Merci.

**Comment by dbarzin** [comment]
C'est sans dout un problème de cache.
Peux-tu suivre la procédure de mise à jour.

**Comment by dbarzin** [comment]
Je regarde cela ce soir.
Merci pour less infos.
