### ISSUE TITLE
Add a " mercator_data.sql " test file for postgres backend 

### ISSUE THREAD

**Issue by jfcjm** [dbarzin/mercator#109]
Bonsoir,
 il n'est pas (encore ?) possible de charger la base de  données de test sous postgres. 

Rq:  il existe peut-être un mécanisme Illuminate/Eloquent pour créer un fichier de test de manière indépendante du backend.

Jean-Marie

**Comment by dbarzin** [comment]
Cette demande est ouverte à contribution.

**Comment by dbarzin** [comment]
Ajout du mode --compatible=ainsi
A tester

**Comment by jfcjm** [comment]
OK, merci.Je teste dès que j'en ai l'occasion

**Comment by jfcjm** [comment]
Je ne sais pas trop comment tester : sur master le fichier de test est toujours au format "mysql" et je ne vois pas comment utiliser le mode '--compatible=ansi' que tu mentionnes ...

**Comment by dbarzin** [comment]
L'option --compatible=ansi' a été ajoutée lors de la génération du fichier avec mysql_dump.
Si cela ne fonctionne pas, je ne sais pas comment généré un fichier compatible avec postgres.

**Comment by jfcjm** [comment]
Je vais regarder .. au pire je ferai un import mysql -> chargeur postgres -> dump postgres ...
Pas très résistant aux évolutions du fichier de test :)  mais en attendant de trouver mieux ...

J.-M.

**Comment by dbarzin** [comment]
Merci pour la contribution !

**Comment by jfcjm** [comment]
OK, merci  (et désolé pour le fichier vide accompagnateur).  

Je n'ai pas trouvé de manip "simple" pour la création de ce fichier (le programme contenu dans le paquet pgloader@debian n'est pas compatible avec la version de mysql utilisée sur cet OS).

Bien qu'il y ait sans doute plus simple, en attendant que je rédige un doc un peut structurée, voici pour mémoire la solution utilisée : 

```
apt-get install mysql mysql_fdw 
```
(mysql_fdw est un backend  (foreign data wrapper)  mysql pour postgres)

Puis:

```
sudo postgres psql mercator
create EXTENSION mysql_fdw;
create SERVER mysql FOREIGN DATA WRAPPER mysql_fdw
     OPTIONS (host '127.0.0.1', port '3306');
CREATE USER MAPPING FOR jfc SERVER mysql OPTIONS (username 'mercator_user', password 's3cr3t');
quit
```
puis en temps qu'utilisateur classique ;
```
psql -c 'IMPORT FOREIGN SCHEMA  mercator FROM SERVER mysql INTO public;'
```
A partir de là on peut réaliser un pg_dump (format postgres) du contenu de la base mysql. Mais pb: le dump est réalisé sans tenir compte des contraintes de clefs étrangères et il n'est alors pas possible de restaurer le contenu du dump :(.

L'idée a été ensuite d'obtenir (avec `tsort`) un  tri topologique des tables pour les avoir dans l'ordre de leurs dépendances sur les clefs étrangères puis dump table par table  du contenu mysql.

```
sudo mysql -e \
"select concat(REFERENCED_TABLE_NAME,concat( ' ', TABLE_NAME ))  \
from information_schema.KEY_COLUMN_USAGE \
where REFERENCED_TABLE_NAME is not null \
   and not (TABLE_NAME  in ('users', 'roles', 'permissions', \
                                                'permissions_roles', 'role_user', 'migrations') \
                 or REFERENCED_TABLE_NAME in ('users', 'roles', 'permissions',\
                                              'permissions_roles', 'role_user','migrations'));"\
    mercator -N -s  | tsort |\
for t in `cat /dev/stdin`;  do \
     pg_dump -a --include-foreign-data=mysql -t $t mercatormysql; \
done  |     psql -e mercator
```
