### ISSUE TITLE
Couche métiers et visibilité des activités/opérations aux niveaux 1 ou 2

### ISSUE THREAD

**Issue by jfcjm** [dbarzin/mercator#123]
Bonjour Didier, 

Je me demande s'il n'y a pas un défaut dans la couche métier, empêchant  la navigation entre processus et opérations aux niveaux de granularité 1 ou 2 :

1. en cohérence avec le doc ANSSI, les activités ne sont visibles qu'au niveau 3, les opérations sont visibles aux niveau 1,2,3
2. pour mercator, la navigation entre processus et opérations doit passer obligatoirement par les activités, activités qui sont inaccessibles aux niveau 1,2.
 
Du coup, il n'est pas possible aux niveaux 1,2 d'exprimer les liaisons entre processus et opérations, ni de naviguer de l'un à l'autre. 

Rq: le document ANSSI semble, de son côté, mentionner que 
la navigation devrait être 

- processus->opérations  en granularité 1 ou 2 
- processus->activités->opérations   en granularité 3.

Est-ce que je rate quelque chose ?

Jean-Marie

PS. (TL;DR) :   p/ au   fichier de test:  les activités sont visibles dans la vue métier quelque soit le niveau mais il n'est pas possible d'éditer/ajouter des activités aux niveau 1,2.

**Comment by dbarzin** [comment]
Oui, en effet mais cela pose un problème pour passe du niveau de granularité 2 au niveau 3.
Il a donc été choisi de modéliser le niveau de granularité 3 dans la base de données.
Laissant au niveau 1 et 2 impossible de faire le lien entre les opération et les processus.
