### ISSUE TITLE
Error Attempt to assign property "is_external" on null 

### ISSUE THREAD

**Issue by EV0IR** [dbarzin/mercator#127]
Bonjour,

Suite à une installation cette semaine, je rencontre l'erreur suivante lors de la création d'une entités
Error
Attempt to assign property "is_external" on null
App\Http\Controllers\Admin\EntityController::store
app/Http/Controllers/Admin/EntityController.php:4
[🧨 Attempt to assign property 'is_external' on null.pdf](https://github.com/dbarzin/mercator/files/8822311/Attempt.to.assign.property.is_external.on.null.pdf)
3

**Comment by jfcjm** [comment]
Bonjour,
  quelle est la revision que vous avez installée ?

**Comment by EV0IR** [comment]
Bonjour, merci de votre réponse

Comment puis-je  vérifier la version ?
Si cela peut aider l'installation a été faite 'from scratch' Lundi 30 mai



De : jfcjm ***@***.***
Envoyé : jeudi 2 juin 2022 11:24
À : dbarzin/mercator ***@***.***>
Cc : Romain IVOY ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/mercator] Error Attempt to assign property "is_external" on null (Issue #127)


Bonjour,
quelle est la revision que vous avez installée ?

-

**Comment by EV0IR** [comment]
Probablement cette version selon dans le changelog [1.1] - 2022-03-20

**Comment by jfcjm** [comment]
Non, ça ne doit pas être ça : is_external n'était pas présent à cette date.
Comment avez-vous downloadé le code ? git ?

**Comment by dbarzin** [comment]
Pouvez-vous mettre l'application à jour sur base des source de github.

Récupérer les sources de GIT

cd /var/www/mercator
sudo -u www-data git pull

Migrer la base de données

sudo -u www-data php artisan migrate

Mettre à jour les librairies

sudo -u www-data composer update

Vider les caches

sudo -u www-data php artisan config:clear &&  php artisan view:clear

**Comment by dbarzin** [comment]
OK, vu. Une correction va être apportée ce soir.

**Comment by dbarzin** [comment]
Corrigé !

**Comment by EV0IR** [comment]
Merci, je peux créer des entités maintenant.
