### ISSUE TITLE
ErrorException DOMDocument::loadXML()

### ISSUE THREAD

**Issue by webchl** [dbarzin/mercator#130]
Bonjour,
lors de la génération d'un rapport (depuis le menu documentation) j'ai une erreur: ErrorException
DOMDocument::loadXML(): Opening and ending tag mismatch: img line 1 and figure in Entity, line: 1
http://X.X.X.X:8000/admin/report/cartography
J'ai remarqué que cela se produit lorsque j'ajoute dans les vues "Ecosysteme" (je n'ai pas testé plusieurs cas)
Cela génère pourtant bien un rapport quand j'enlevé cette vue du rapport
une idée?
merci

**Comment by dbarzin** [comment]
Le problème est confirmé.

**Comment by dbarzin** [comment]
Je n'ai pas réussi à reproduire le même problème mais en attendant,
vous pouvez vérifier que la librairie php-dom est installée :
 
    sudo apt install php-dom 
    sudo systemctl restart apache2

Avez-vous la dernière version du projet ?

**Comment by dbarzin** [comment]
Dans les logs Apache j'ai trouvé cette erreur : 

    Allowed memory size of 134217728 bytes exhausted

Il faut augmenter la taille maximum allouée à PHP dans /etc/php/8.1/apache2/php.ini

    memory_limit = 512M
	
et redémarer Apache

    sudo systemctl restart apache2

**Comment by dbarzin** [comment]
Est-ce que le problème se produit en ne sélectionnant que la vue de l'écosystème ?

**Comment by webchl** [comment]
Bonjour

Oui cela fait le meme probleme quand on selectionne uniquement ecosysteme

***@***.***

De : Didier Barzin ***@***.***>
Envoyé : vendredi 10 juin 2022 07:35
À : dbarzin/mercator ***@***.***>
Cc : webchl ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/mercator] ErrorException DOMDocument::loadXML() (Issue #130)

ATTENTION: Ce courrier provient d’un expéditeur extérieur à l’établissement, Ne cliquez sur aucun lien suspect et n'ouvrez aucune pièce jointe d'un expéditeur ou d’un contenu qui vous parait inhabituel. Ne communiquez pas vos identifiants sur des sites internet ou à la demande d’un interlocuteur. En cas de doute, contactez le Service Informatique
'

Est-ce que le problème se produit en ne sélectionnant que la vue de l'écosystème ?

**Comment by dbarzin** [comment]
Donc, c'est très probablement lié à des tags HTML non correctement fermés dans les champs de la table entités ou relations.
Tu peux identifier le champ concerné en mettant en commentaire les lignes dans /app/Http/Controllers/Admin/CartographyController.php vers la ligne 175.

**Comment by webchl** [comment]
Desole mais je ne trouve ce qu’il faut commente.
Comment mettre a jour la derniere version de mercator ? quelle commande ou autre ?
Cela va peut etre corriger le probleme

merci


De : Didier Barzin ***@***.***>
Envoyé : vendredi 10 juin 2022 11:57
À : dbarzin/mercator ***@***.***>
Cc : webchl ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/mercator] ErrorException DOMDocument::loadXML() (Issue #130)

ATTENTION: Ce courrier provient d’un expéditeur extérieur à l’établissement, Ne cliquez sur aucun lien suspect et n'ouvrez aucune pièce jointe d'un expéditeur ou d’un contenu qui vous parait inhabituel. Ne communiquez pas vos identifiants sur des sites internet ou à la demande d’un interlocuteur. En cas de doute, contactez le Service Informatique
'

Donc, c'est très probablement lié à des tags HTML non correctement fermés dans les champs de la table entités ou relations.
Tu peux identifier le champ concerné en mettant en commentaire les lignes dans /app/Http/Controllers/Admin/CartographyController.php vers la ligne 175.

**Comment by dbarzin** [comment]
Les étapes à suivre pour mettre à jour de Mercator sont documentées dans la procédure d'installation.

**Comment by webchl** [comment]
J’ai des erreurs lors dela mise a jour
***@***.***:/var/www/mercator$ git pull
warning: redirecting to https://github.com/dbarzin/mercator.git/
Updating 2af2b4b..791803d
error: Your local changes to the following files would be overwritten by merge:
        .env.example
        .gitignore
        CHANGELOG.md
        Dockerfile
        INSTALL.md
        README.md
        app/AuditLog.php
        app/Certificate.php
        app/Console/Commands/CertificateExpiracy.php
        app/DhcpServer.php
        app/Dnsserver.php
        app/Entity.php
        app/Exceptions/Handler.php
        app/Gateway.php
        app/Http/Controllers/Admin/ActivityController.php
        app/Http/Controllers/Admin/ActorController.php
        app/Http/Controllers/Admin/AnnuaireController.php
        app/Http/Controllers/Admin/ApplicationBlockController.php
        app/Http/Controllers/Admin/ApplicationModuleController.php
        app/Http/Controllers/Admin/ApplicationServiceController.php
        app/Http/Controllers/Admin/AuditLogsController.php
        app/Http/Controllers/Admin/BayController.php
        app/Http/Controllers/Admin/BuildingController.php
        app/Http/Controllers/Admin/CartographyController.php
        app/Http/Controllers/Admin/CertificateController.php
        app/Http/Controllers/Admin/ConfigurationController.php
        app/Http/Controllers/Admin/DatabaseController.php
        app/Http/Controllers/Admin/DhcpServerController.php
        app/Http/Controllers/Admin/DnsserverController.php
        app/Http/Controllers/Admin/DomaineAdController.php
        app/Http/Controllers/Admin/EntityController.php
        app/Http/Controllers/Admin/ExternalConnectedEntityController.php
        app/Http/Controllers/Admin/FluxController.php
        app/Http/Controllers/Admin/ForestAdController.php
        app/Http/Controllers/Admin/GatewayController.php
        app/Http/Controllers/Admin/GlobalSearchController.php
        app/Http/Controllers/Admin/HomeController.php
        app/Http/Controllers/Admin/InformationController.php
        app/Http/Controllers/Admin/LanController.php
        app/Http/Controllers/Admin/LogicalServerController.php
        app/Http/Controllers/Admin/MApplicationController.php
        app/Http/Controllers/Admin/MacroProcessusController.php
        app/Http/Controllers/Admin/ManController.php
        app/Http/Controllers/Admin/NetworkController.php
        app/Http/Controllers/Admin/NetworkSwitchController.php
        app/Http/Controllers/Admin/OperationController.php
        app/Http/Controllers/Admin/PeripheralController.php
        app/Http/Controllers/Admin/PermissionsController.php
        app/Http/Controllers/Admin/PhoneController.php
        app/Http/Controllers/Admin/PhysicalRouterController.php
        app/Http/Controllers/Admin/PhysicalSecurityDeviceController.php
        app/Http/Controllers/Admin/PhysicalServerController.php
        app/Http/Controllers/Admin/PhysicalSwitchController.php
        app/Http/Controllers/Admin/ProcessController.php
        app/Http/Controllers/Admin/RelationController.php
        app/Http/Controllers/Admin/ReportController.php
        app/Http/Controllers/Admin/RolesController.php
        app/Http/Controllers/Admin/RouterController.php
        app/Http/Controllers/Admin/SecurityDeviceController.php
        app/Http/Controllers/Admin/SiteController.php
        app/Http/Controllers/Admin/StorageDeviceController.php
        app/Http/Controllers/Admin/SubnetworkController.php
        app/Http/Controllers/Admin/TaskController.php
        app/Http/Controllers/Admin/VlanController.php
        app/Http/Controllers/Admin/WanController.php
        app/Http/Controllers/Admin/WifiTerminalController.php
        app/Http/Controllers/Admin/WorkstationController.php
        app/Http/Controllers/Admin/ZoneAdminController.php
        app/Http/Controllers/Auth/LoginController.php
        app/Http/Middleware/Authenticate.php
        app/Http/Middleware/VerifyCsrfToken.php
        app/Http/Requests/MassDestroyManRequest.php
        app/Http/Requests/StoreDhcpServerRequest.php
        app/Http/Requests/StoreDnsserverRequest.php
        app/Http/Requests/StoreMApplicationRequest.php
        app/Http/Requests/StoreUserRequest.php
        app/Http/Requests/UpdateDhcpServerRequest.php
        app/Http/Requests/UpdateDnsserverRequest.php
        app/Http/Requests/UpdateMApplicationRequest.php
        app/Http/Requests/UpdateNetworkSwitchRequest.php
        app/LogicalServer.php
        app/MApplication.php
        app/Providers/AppServiceProvider.php
        app/Providers/AuthServiceProvider.php
        app/Providers/EventServiceProvider.php
        app/Providers/RouteServiceProvider.php
        app/Relation.php
        app/Role.php
        app/Traits/Auditable.php
        app/User.php
        composer.json
        config/app.php
        config/auth.php
        database/migrations/2021_05_08_191249_create_m_app
error: The following untracked working tree files would be overwritten by merge:
        resources/views/errors/401.blade.php
        resources/views/errors/403.blade.php
        resources/views/errors/404.blade.php
        resources/views/errors/419.blade.php
        resources/views/errors/429.blade.php
        resources/views/errors/500.blade.php
        resources/views/errors/503.blade.php
        resources/views/errors/illustrated-layout.blade.php
        resources/views/errors/layout.blade.php
        resources/views/errors/minimal.blade.php
Please move or remove them before you merge.
Aborting

Geoffroy Guégan
Service Informatique
Centre Hospitalier de Loches
0247913370
***@***.******@***.***>


De : Didier Barzin ***@***.***>
Envoyé : vendredi 10 juin 2022 12:35
À : dbarzin/mercator ***@***.***>
Cc : webchl ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/mercator] ErrorException DOMDocument::loadXML() (Issue #130)

ATTENTION: Ce courrier provient d’un expéditeur extérieur à l’établissement, Ne cliquez sur aucun lien suspect et n'ouvrez aucune pièce jointe d'un expéditeur ou d’un contenu qui vous parait inhabituel. Ne communiquez pas vos identifiants sur des sites internet ou à la demande d’un interlocuteur. En cas de doute, contactez le Service Informatique
'

Les étapes à suivre pour mettre à jour de Mercator sont documentées dans la procédure d'installation.

**Comment by dbarzin** [comment]
Etrange, il semble que les fichiers ont été modifiés.
Tu peux faire un git pull --force
Pense à prendre un snapshot de la VM avant...

**Comment by webchl** [comment]
Meme probleme avec git pull --force

De : Didier Barzin ***@***.***>
Envoyé : vendredi 10 juin 2022 13:54
À : dbarzin/mercator ***@***.***>
Cc : webchl ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/mercator] ErrorException DOMDocument::loadXML() (Issue #130)

ATTENTION: Ce courrier provient d’un expéditeur extérieur à l’établissement, Ne cliquez sur aucun lien suspect et n'ouvrez aucune pièce jointe d'un expéditeur ou d’un contenu qui vous parait inhabituel. Ne communiquez pas vos identifiants sur des sites internet ou à la demande d’un interlocuteur. En cas de doute, contactez le Service Informatique
'

Etrange, il semble que les fichiers ont été modifiés.
Tu peux faire un git pull --force
Pense à prendre un snapshot de la VM avant...

**Comment by dbarzin** [comment]
git reset --hard
git pull

**Comment by webchl** [comment]
Pareil dsl

Geoffroy Guégan
Service Informatique
Centre Hospitalier de Loches
0247913370
***@***.******@***.***>


De : Didier Barzin ***@***.***>
Envoyé : vendredi 10 juin 2022 14:17
À : dbarzin/mercator ***@***.***>
Cc : webchl ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/mercator] ErrorException DOMDocument::loadXML() (Issue #130)

ATTENTION: Ce courrier provient d’un expéditeur extérieur à l’établissement, Ne cliquez sur aucun lien suspect et n'ouvrez aucune pièce jointe d'un expéditeur ou d’un contenu qui vous parait inhabituel. Ne communiquez pas vos identifiants sur des sites internet ou à la demande d’un interlocuteur. En cas de doute, contactez le Service Informatique
'

git reset --hard
git pull

**Comment by dbarzin** [comment]
git clone https://www.github.com/dbarzin/mercator

**Comment by webchl** [comment]
Ca avance mais…
***@***.***:/var/www/mercator$ git pull
fatal: not a git repository (or any of the parent directories): .git
***@***.***:/var/www/mercator$ php artisan migrate
Could not open input file: artisan



De : Didier Barzin ***@***.***>
Envoyé : vendredi 10 juin 2022 15:07
À : dbarzin/mercator ***@***.***>
Cc : webchl ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/mercator] ErrorException DOMDocument::loadXML() (Issue #130)

ATTENTION: Ce courrier provient d’un expéditeur extérieur à l’établissement, Ne cliquez sur aucun lien suspect et n'ouvrez aucune pièce jointe d'un expéditeur ou d’un contenu qui vous parait inhabituel. Ne communiquez pas vos identifiants sur des sites internet ou à la demande d’un interlocuteur. En cas de doute, contactez le Service Informatique
'

git clone https://www.github.com/dbarzin/mercator<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fwww.github.com%2fdbarzin%2fmercator&umid=dc9f7c64-0cad-4023-ae31-c4a8811297b9&auth=1a3cb316522a2150df7bc4e6bd0090c1f2656ec1-377234af79bca684fb154e2c7cd212506fa44393>

**Comment by dbarzin** [comment]
git clone https://www.github.com/dbarzin/mercator

**Comment by webchl** [comment]
Meme apres restauration je relance la mise a jour et idem

Et quand je supprime le dossier mercator et que je fais ensuite un git clone https://www.github.com/dbarzin/mercator<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fwww.github.com%2fdbarzin%2fmercator&umid=d312f2d8-5572-409c-8006-01e7b1d1c0cc&auth=1a3cb316522a2150df7bc4e6bd0090c1f2656ec1-0a5e5239db410a537a242b6f07829e8987634e03> plus rien ne fonctionne
Est-ce que je peux récupérer les fichiers php et les ecraser sur la prod ?
Est-ce que cela suffira pour la maj ?


De : Didier Barzin ***@***.***>
Envoyé : vendredi 10 juin 2022 15:47
À : dbarzin/mercator ***@***.***>
Cc : webchl ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/mercator] ErrorException DOMDocument::loadXML() (Issue #130)

ATTENTION: Ce courrier provient d’un expéditeur extérieur à l’établissement, Ne cliquez sur aucun lien suspect et n'ouvrez aucune pièce jointe d'un expéditeur ou d’un contenu qui vous parait inhabituel. Ne communiquez pas vos identifiants sur des sites internet ou à la demande d’un interlocuteur. En cas de doute, contactez le Service Informatique
'

git clone https://www.github.com/dbarzin/mercator<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fwww.github.com%2fdbarzin%2fmercator&umid=d312f2d8-5572-409c-8006-01e7b1d1c0cc&auth=1a3cb316522a2150df7bc4e6bd0090c1f2656ec1-0a5e5239db410a537a242b6f07829e8987634e03>

**Comment by dbarzin** [comment]
Oui, tu peux refaire l'installation depuis le début.
Ce qui change est qu'avant de migrer la base de données tu dois restaurer le backup de la base de données puis faire "php artisan migrate" sans --seed 
Le reste de l'installation est identique.

**Comment by dbarzin** [comment]
Geoffroy,
As-tu réussi à réinstaller Mercator ?
Didier

**Comment by webchl** [comment]
Bonjour,

Désolé du retard ! bcp de travail

Je suis reparti d’une sauvegarde d’avant les essais de mise a jour

Voici ce que je compte faire suivant tes conseils:


mysqldump mercator > mercator_backup.sql
sudo apt update && sudo apt upgrade

cd /var/www/

git clone https://www.github.com/dbarzin/mercator

mysql mercator < mercator_backup.sql
php artisan migrate
composer update
php artisan config:clear && php artisan view:clear


Cela te semble jouable ?

Merci

De : Didier Barzin ***@***.***
Envoyé : lundi 13 juin 2022 23:14
À : dbarzin/mercator ***@***.***>
Cc : webchl ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/mercator] ErrorException DOMDocument::loadXML() (Issue #130)

ATTENTION: Ce courrier provient d’un expéditeur extérieur à l’établissement, Ne cliquez sur aucun lien suspect et n'ouvrez aucune pièce jointe d'un expéditeur ou d’un contenu qui vous parait inhabituel. Ne communiquez pas vos identifiants sur des sites internet ou à la demande d’un interlocuteur. En cas de doute, contactez le Service Informatique
'

Geoffroy,
As-tu réussi à réinstaller Mercator ?
Didier

**Comment by dbarzin** [comment]
Le backup et la restauration de la db n'est pas nécessaire.
Voici ma proposition : 

sudo apt update && sudo apt upgrade

cp /var/www/mercator/.env /tmp
rm -rf /var/www/mercator

cd /var/www/
git clone https://www.github.com/dbarzin/mercator

cd mercator
mv /tmp/.env .

php artisan migrate

composer update
php artisan vendor:publish --all

sudo chown -R www-data:www-data /var/www/mercator
sudo chmod -R 775 /var/www/mercator/storage

**Comment by dbarzin** [comment]
Nous avons oublié de faire "composer update" juste avant.

**Comment by webchl** [comment]
Bonjour
toujours des problemes de mise a jour
voici les étapes effectuées:

sudo apt update && sudo apt upgrade
cp /var/www/mercator/.env /tmp
rm -rf /var/www/mercator
cd /var/www/
sudo git clone https://www.github.com/dbarzin/mercator
cd mercator
sudo mv /tmp/.env .
sudo composer update

a partir d'ici j'ai ce message ne semblant pas bloquant:
_Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^8.0 but your php version (7.4.3) does not satisfy that requirement._

poursuite des étapes:

sudo php artisan migrate

et là, nouveau message d'erreur:
_PHP Warning:  require(/var/www/mercator/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/mercator/artisan on line 18
PHP Stack trace:
PHP   1. {main}() /var/www/mercator/artisan:0
PHP Fatal error:  require(): Failed opening required '/var/www/mercator/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/mercator/artisan on line 18
PHP Stack trace:
PHP   1. {main}() /var/www/mercator/artisan:0_

que dois je faire?
merci

**Comment by dbarzin** [comment]
La nouvelle version de Laravel nécessite l'installation de PHP 8

    sudo apt update 
    sudo apt install php8.0 libapache2-mod-php8.0

Puis les librairies :

    sudo apt install php8.0-zip php8.0-curl php8.0-mbstring php8.0-dom php8.0-ldap php8.0-soap php8.0-xdebug php8.0-mysql php8.0-gd

**Comment by webchl** [comment]
Erreur lors de l’instalaltion de la mise a jour php

sudo apt update && sudo apt upgrade

Hit:1 http://fr.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://fr.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://fr.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:4 http://fr.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Fetched 336 kB in 2s (204 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  libfwupdplugin1
Use 'sudo apt autoremove' to remove it.
The following packages will be upgraded:
  apt apt-utils cloud-init libapt-pkg6.0
4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 2840 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://fr.archive.ubuntu.com/ubuntu focal-updates/main amd64 libapt-pkg6.0 amd64 2.0.9 [839 kB]
Get:2 http://fr.archive.ubuntu.com/ubuntu focal-updates/main amd64 apt amd64 2.0.9 [1294 kB]
Get:3 http://fr.archive.ubuntu.com/ubuntu focal-updates/main amd64 apt-utils amd64 2.0.9 [213 kB]
Get:4 http://fr.archive.ubuntu.com/ubuntu focal-updates/main amd64 cloud-init all 22.2-0ubuntu1~20.04.2 [494 kB]
Fetched 2840 kB in 29s (99.3 kB/s)
Preconfiguring packages ...
(Reading database ... 110576 files and directories currently installed.)
Preparing to unpack .../libapt-pkg6.0_2.0.9_amd64.deb ...
Unpacking libapt-pkg6.0:amd64 (2.0.9) over (2.0.8) ...
Setting up libapt-pkg6.0:amd64 (2.0.9) ...
(Reading database ... 110576 files and directories currently installed.)
Preparing to unpack .../archives/apt_2.0.9_amd64.deb ...
Unpacking apt (2.0.9) over (2.0.8) ...
Setting up apt (2.0.9) ...
(Reading database ... 110576 files and directories currently installed.)
Preparing to unpack .../apt-utils_2.0.9_amd64.deb ...
Unpacking apt-utils (2.0.9) over (2.0.8) ...
Preparing to unpack .../cloud-init_22.2-0ubuntu1~20.04.2_all.deb ...
Unpacking cloud-init (22.2-0ubuntu1~20.04.2) over (22.2-0ubuntu1~20.04.1) ...
Setting up cloud-init (22.2-0ubuntu1~20.04.2) ...
Setting up apt-utils (2.0.9) ...
Processing triggers for rsyslog (8.2001.0-1ubuntu1.3) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...

sudo apt install php8.0 libapache2-mod-php8.0
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php8.0
E: Couldn't find any package by glob 'php8.0'
E: Unable to locate package libapache2-mod-php8.0
E: Couldn't find any package by glob 'libapache2-mod-php8.0'

sudo apt install php8.0-zip php8.0-curl php8.0-mbstring php8.0-dom php8.0-ldap php8.0-soap php8.0-xdebug php8.0-mysql php8.0-gd
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php8.0-zip
E: Couldn't find any package by glob 'php8.0-zip'
E: Unable to locate package php8.0-curl
E: Couldn't find any package by glob 'php8.0-curl'
E: Unable to locate package php8.0-mbstring
E: Couldn't find any package by glob 'php8.0-mbstring'
E: Unable to locate package php8.0-dom
E: Couldn't find any package by glob 'php8.0-dom'
E: Unable to locate package php8.0-ldap
E: Couldn't find any package by glob 'php8.0-ldap'
E: Unable to locate package php8.0-soap
E: Couldn't find any package by glob 'php8.0-soap'
E: Unable to locate package php8.0-xdebug
E: Couldn't find any package by glob 'php8.0-xdebug'
E: Unable to locate package php8.0-mysql
E: Couldn't find any package by glob 'php8.0-mysql'
E: Unable to locate package php8.0-gd
E: Couldn't find any package by glob 'php8.0-gd'



De : Didier Barzin ***@***.***>
Envoyé : lundi 20 juin 2022 14:40
À : dbarzin/mercator ***@***.***>
Cc : webchl ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/mercator] ErrorException DOMDocument::loadXML() (Issue #130)

ATTENTION: Ce courrier provient d’un expéditeur extérieur à l’établissement, Ne cliquez sur aucun lien suspect et n'ouvrez aucune pièce jointe d'un expéditeur ou d’un contenu qui vous parait inhabituel. Ne communiquez pas vos identifiants sur des sites internet ou à la demande d’un interlocuteur. En cas de doute, contactez le Service Informatique
'

La nouvelle version de Laravel nécessite l'installation de PHP 8

sudo apt update



sudo apt install php8.0 libapache2-mod-php8.0



Puis les librairies :

sudo apt install php8.0-zip php8.0-curl php8.0-mbstring php8.0-dom php8.0-ldap php8.0-soap php8.0-xdebug php8.0-mysql php8.0-gd

**Comment by dbarzin** [comment]
A ce point, je te propose de réinstaller Mercator avec la derrière version d'Ubuntu 22.04 LTS en suivant la procédure d'installation fournie sur le github. A la fin de l'installation, tu peux restaurer le backup de la DB et faire un "php artisan migrate".

**Comment by webchl** [comment]
Bonjour,

Je repars donc vers une nouvelle install et suis a la lettre la procedure mais…

sudo apt install apache2 mod_php git graphviz composer
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet mod_php



De : Didier Barzin ***@***.***>
Envoyé : mardi 21 juin 2022 13:52
À : dbarzin/mercator ***@***.***>
Cc : webchl ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/mercator] ErrorException DOMDocument::loadXML() (Issue #130)

ATTENTION: Ce courrier provient d’un expéditeur extérieur à l’établissement, Ne cliquez sur aucun lien suspect et n'ouvrez aucune pièce jointe d'un expéditeur ou d’un contenu qui vous parait inhabituel. Ne communiquez pas vos identifiants sur des sites internet ou à la demande d’un interlocuteur. En cas de doute, contactez le Service Informatique
'

A ce point, je te propose de réinstaller Mercator avec la derrière version d'Ubuntu 22.04 LTS en suivant la procédure d'installation fournie sur le github. A la fin de l'installation, tu peux restaurer le backup de la DB et faire un "php artisan migrate".

**Comment by dbarzin** [comment]
On a oublié "composer update"

**Comment by webchl** [comment]
git reset --hard
HEAD is now at 2af2b4b lien processus applications
***@***.***:/var/www/mercator$ git pull --force
warning: redirecting to https://github.com/dbarzin/mercator.git/
Updating 2af2b4b..791803d
error: The following untracked working tree files would be overwritten by merge:
        resources/views/errors/401.blade.php
        resources/views/errors/403.blade.php
        resources/views/errors/404.blade.php
        resources/views/errors/419.blade.php
        resources/views/errors/429.blade.php
        resources/views/errors/500.blade.php
        resources/views/errors/503.blade.php
        resources/views/errors/illustrated-layout.blade.php
        resources/views/errors/layout.blade.php
        resources/views/errors/minimal.blade.php
Please move or remove them before you merge.
Aborting

Geoffroy Guégan
Service Informatique
Centre Hospitalier de Loches
0247913370
***@***.******@***.***>


De : webchl ***@***.***>
Envoyé : vendredi 10 juin 2022 14:34
À : dbarzin/mercator ***@***.***>; dbarzin/mercator ***@***.***>
Cc : webchl ***@***.***>; Author ***@***.***>
Objet : RE: [dbarzin/mercator] ErrorException DOMDocument::loadXML() (Issue #130)

Pareil dsl

Geoffroy Guégan
Service Informatique
Centre Hospitalier de Loches
0247913370
***@***.******@***.***>


De : Didier Barzin ***@***.******@***.***>>
Envoyé : vendredi 10 juin 2022 14:17
À : dbarzin/mercator ***@***.******@***.***>>
Cc : webchl ***@***.******@***.***>>; Author ***@***.******@***.***>>
Objet : Re: [dbarzin/mercator] ErrorException DOMDocument::loadXML() (Issue #130)

ATTENTION: Ce courrier provient d’un expéditeur extérieur à l’établissement, Ne cliquez sur aucun lien suspect et n'ouvrez aucune pièce jointe d'un expéditeur ou d’un contenu qui vous parait inhabituel. Ne communiquez pas vos identifiants sur des sites internet ou à la demande d’un interlocuteur. En cas de doute, contactez le Service Informatique
'

git reset --hard
git pull
