### ISSUE TITLE
compte admin

### ISSUE THREAD

**Issue by ChevaucheurDeVague** [dbarzin/mercator#15]
bonjour,

je viens de finir l'installation de mercator sous linux Ubuntu sur un hyper-V.
Après un cri de victoire suite a l'affichage de la page de login de Mercator, une déception : il ne veut pas de admin@admin.com  /  password comme identifiants....

**Comment by dbarzin** [comment]
Quel est le message d'erreur ? (voir dans mercator/storage/logs/laravel.log)
L'utilisation admin existe t-il dans la DB ? ( sudo mysql mercator -e "select * from users;" )

**Comment by ChevaucheurDeVague** [comment]
Bonsoir
Je viens de regarder
L'erreur est :" Ces identifiants ne sont pas reconnus"
Ce qui est logique vu que votre commande renvoie "table 'mercator.users' doesn't exist"
Jai du oublié un truc
________________________________

**Comment by dbarzin** [comment]
Il semble que la DB ne soit pas créée. La commande à lancer dans le répertoire de mercator est : "php artisan migrate --seed".

**Comment by ChevaucheurDeVague** [comment]
:/var/www/html/mercator$ php artisan migrate --seed
Migrating: 2021_05_08_191249_create_activities_table

   Illuminate\Database\QueryException 

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'activities' already exists (SQL: create table `activities` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `description` longtext null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:692
    688▕         // If an exception occurs when attempting to run a query, we'll format the error
    689▕         // message to include the bindings with SQL, which will make this exception a
    690▕         // lot more helpful to the developer instead of just the database's errors.
    691▕         catch (Exception $e) {
  ➜ 692▕             throw new QueryException(
    693▕                 $query, $this->prepareBindings($bindings), $e
    694▕             );
    695▕         }
    696▕ 

      +12 vendor frames 
  13  database/migrations/2021_05_08_191249_create_activities_table.php:23
      Illuminate\Support\Facades\Facade::__callStatic()

      +21 vendor frames 
  35  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by dbarzin** [comment]
Quel est le type et la version de la base de données ? (mysql --version)

**Comment by ChevaucheurDeVague** [comment]
mysql  Ver 15.1 Distrib 10.1.48-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by dbarzin** [comment]
Mercator ne fonctionne pas sous MariaDB. Il faut installer mySQL.

**Comment by ChevaucheurDeVague** [comment]
ok

**Comment by ChevaucheurDeVague** [comment]
je vais repartir sur une autre

**Comment by ChevaucheurDeVague** [comment]
j'ai crée une nouvelle VM ubuntu et suivi le déroulé de l'install et cela bloque à la création du .env il me dit que je n'ai pas les droits:

 cp .env.example .env
cp: impossible de créer le fichier standard '.env': Permission non accordée

avec sudo c'est pas mieux.
Il m'a fait quelques erreurs de droit qui m'ont forcé a utiliser sudo alors que sur la première install(avec mariaDB), cela était passé sans sudo...

**Comment by dbarzin** [comment]
Tu n'as pas des droits d'écriture dans le répertoire courant.
Va dans le répertoire de mercator et fait : sudo chown -R mon_userid .

**Comment by ChevaucheurDeVague** [comment]
je me suis donné les droits sur www
j'ai supprimé le dossier mercator
je repris le process depuis Project sans encombre.

quand je me connecte sur l'interface web : 
j'ai ces messages :
------------------------------
APP_DEBUG is set to true while APP_ENV is not local

This could make your application vulnerable to remote execution. Read more about Ignition security.
/var/www/mercator/
Illuminate\Encryption\MissingAppKeyException
No application encryption key has been specified.
http://127.0.0.1:8000/
Hide solutions
Your app key is missing

Generate your application encryption key using php artisan key:generate.
Read more

    Laravel installation

----------------------- 

quand je fais générer la clé cela me dit que ça le fait sans problème : 
/var/www/mercator$ php artisan key:generate
Application key set successfully.

**Comment by dbarzin** [comment]
la clé de l'application est manquante. Pour générer la clé : 
php artisan key:generate
C'est dans la procédure d'installation.

**Comment by ChevaucheurDeVague** [comment]
je suis reparti à zéro, vm réinitialisée avec Ubuntu standard.
j'ai suivi tous les items. 
 - il faut se donner les droits sur www, pour pouvoir réalisé l'item "git clone ... " sinon err fatal permission non accordée pour créer  copie d etravail mercator 
- arrivé à la fin de l'installation sans erreur, mais a nouveau problème de clé : "No application encryption key has been specified"

Pourtant la clé a bien été générée. j'ai eu le retour : " Application key set successfully

**Comment by dbarzin** [comment]
Je vais essayer de reproduire le problème.
- Quelle version de Ubuntu as-tu utilisé ?
- Quelles commandes supplémentaire qui ne sont pas dans la procédure as-tu utilisé pour l'installation ?

**Comment by ChevaucheurDeVague** [comment]
j'ai refait : 
-  php artisan config:clear 
- php artisan serve
=> toujours problème de cle

- php artisan key:generate
- php artisan serve
=> toujours problème de clé

**Comment by ChevaucheurDeVague** [comment]
ma version : ubuntu 20.04 installé sur une VM hyper-V
ma première install c'était une vm existante avec maria DB
ma deuxième avec ubuntu 20.04 en version minimale
l'actuelle ubuntu avec toutes les applis
une fois les mises a jour effectuées, je n'ai rien fait d'autre que de suivre la procédure d'install .

**Comment by ChevaucheurDeVague** [comment]
après l'install d'ubuntu je n'ai fait que suivre la procédure, sauf pour le clone de git.
 quand on part de zéro on a pas les droits d'écriture sur www

**Comment by ChevaucheurDeVague** [comment]
et j'ai suivi le lien "install composer globally"
et installer le premier script

**Comment by dbarzin** [comment]
As-tu importé les données de test ?
Quelle commande as-tu utilisé pour changer les droits sur www ?

**Comment by ChevaucheurDeVague** [comment]
oui j'ai importé les données de test (mais peut être après mon premier essai de connexion)

la commande avec laquelle je me suis donné les droits  :
cyril@SRVLINUX2:/var/www/mercator$ sudo chown -R cyril /var/www/

**Comment by dbarzin** [comment]
Je viens de retester la procédure d'installation sous Ubuntu et l'application se lance.
Il y avait quelques changements à faire concernant les droits d'accès au répertoire /var/www/mercator.

Concernant ton problème, peux-tu vérifier que la clé de l'application a bien été généré dans le fichier .env ?
APP_KEY=....

Lorsque tu t'es donné les droits, si tu as fait : sudo chown -R cyril /var/www/mercator/*
cela peut expliquer le problème car le fichier .env ne t’appartient par et Laravel ne peut pas le lire au démarrage.

**Comment by ChevaucheurDeVague** [comment]
je n'ai pas de ligne qui commence par APP_KEY= dans le fichier .env (qui est un fichier caché)
les seules lignes qui commencent par APP_ sont celles-ci :
APP_DEBUG=true
APP_URL=http://localhost

Sinon j'ai ça dans le .env :
PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

**Comment by ChevaucheurDeVague** [comment]
pour la commande git je n'ai pas fait de sudo.
je me suis donné les droits sur www et du coup le commande est passée

**Comment by ChevaucheurDeVague** [comment]
et j'ai vraiment tapé ça :
sudo chown -R cyril /var/www/

j'ai regardé dans l'historique du terminal

**Comment by dbarzin** [comment]
Dans le fichier .env.example cette variable est pourtant bien présente. Peux-tu refaire ceci : 
    cd /var/www/mercator
    cp .env.example .env
    php artisan key:generate
Vérifier que la clé de l'application a bien été générée (APP_KEY=....)
Vider la cache et lancer l'application
    php artisan config:clear
    php artisan serve

**Comment by ChevaucheurDeVague** [comment]
ok super ! cela fonctionne.
je suis connecté en admin
je vais pouvoir regarder l'appli.
merci du support
