### ISSUE TITLE
Problème pour la création et la modification des applications

### ISSUE THREAD

**Issue by Omberinian** [dbarzin/mercator#150]
Bonjour,
Lorsque je valide la création ou la modification d'une application, j'obtient un message d'erreur suivant :

TypeError
implode(): Argument #1 ($pieces) must be of type array, string given

La création se fait malgré tout, l'application apparaît bien dans la liste, mais il m'est impossible de pouvoir la modifier. Les modifications faites ne sont pas prises en compte.

![Capture d’écran 2022-06-28 091530](https://user-images.githubusercontent.com/108326877/176122421-5946ada0-2cd9-4c2f-94bb-12aa67a23ebd.png)

Merci

**Comment by dbarzin** [comment]
Corrigé !
Merci
