### ISSUE TITLE
Error Attempt to assign property "crypted" on null http://192.168.238.93/admin/fluxes 

### ISSUE THREAD

**Issue by EV0IR** [dbarzin/mercator#152]
Je rencontre cette erreur lors de la création d'un flux.

![image](https://user-images.githubusercontent.com/106736221/176440717-ad0ed95f-fb00-477a-9cb2-5d0115ba2e84.png)

**Comment by dbarzin** [comment]
Corrigé !
Merci,
Didier

**Comment by EV0IR** [comment]
Merci, cela fonctionne.
