### ISSUE TITLE
Send emails with UTF-8

### ISSUE THREAD

**Issue by Foxi352** [dbarzin/mercator#160]
Special characters do not appear correctly in emails.

![image](https://user-images.githubusercontent.com/5746932/177965385-f57f2d79-5ae5-4991-966b-bd4d9b6c5d3e.png)

Solution is maybe to send emails UTF-8 encoded ?

```
Subject: Test: Certificat expirÃ©
Content-Type: text/html; charset="iso-8859-1"
```

**Comment by dbarzin** [comment]
Fixed using  [base64 encoding](https://www.rfc-editor.org/rfc/rfc2045#section-6.8).

**Comment by Foxi352** [comment]
Confirmed working !
Thank you.
