### ISSUE TITLE
Problème pour afficher la page de l'application

### ISSUE THREAD

**Issue by lle-git** [dbarzin/mercator#17]
Bonjour,
Merci de proposer ce projet.

J'ai installé (depuis Windows10) en suivant le manuel d'install pour Docker. 
L'installation me semble ok (à toute fin utile : j'ai du simplement modifier les commandes apt par apt-get, sinon cela n'installait pas les packages curl et autres dans mon cas).

Mais je ne parviens pas à obtenir la page de l'application.
    __root@d43b6562b097:/var/www/mercator# curl http://localhost:8000
    curl: (7) Failed to connect to localhost port 8000: Connection refused__

Le problème est surement trivial mais je ne sais comment investiguer (je commence à l'instant avec Docker, et je suis face à mes limites pour le reste).
Avez-vous une idée svp à partir de la log en PJ ?
Manque t-il un paramétrage ? Je ne m'y prends pas de la bonne manière ? 

Merci par avance.

**************************
[log_mercator_20210617.txt](https://github.com/dbarzin/mercator/files/6671968/log_mercator_20210617.txt)

**Comment by dbarzin** [comment]
essaye curl http://app:8000

**Comment by lle-git** [comment]
Alors cela donne pareil : 
root@d43b6562b097:/var/www/mercator# curl http://app:8000
curl: (7) Failed to connect to app port 8000: Connection refused

**Comment by dbarzin** [comment]
l'APP_URL vaut https://mercator.mydomain.com/
As-tu essayé avec curl http://mercator.mydomain.com:8000

**Comment by dbarzin** [comment]
Y-a-t-il des erreurs dans les logs lors de la construction des

**Comment by dbarzin** [comment]
Je te propose d'essayer une installation dans une VM. Cette procédure est bien maitrisée et testée.

**Comment by mqu** [comment]
```
bonjour, tu peux aussi diagnostiquer avec les commandes suivantes:


# lister les containers et leur état
docker-compose ps

# lister les processus à l'intérieur des containers
docker-compose top
```

**Comment by dbarzin** [comment]
As-tu trouvé une solution ?

**Comment by mqu** [comment]
pas de retour sur cette problématique.

**Comment by mqu** [comment]
sur une installation toute fraiche, je viens de reproduire le problème ... l'application dans le container "app" reste bloquée, en attente du démarrage de la base de donnée "db".

```
marc@gigabyte:/extra/tmp/docker/mercator/docker$ docker-compose logs -ft app
Attaching to docker_app_1
app_1  | 2021-07-07T05:53:20.779789223Z waiting for mysql to be ready ...
```
je regarde dès que j'ai un peu de temps.

**Comment by mqu** [comment]
il faut adapter le fichier de configuration .env avec : 
`
DB_HOST=db
`
en script bash

`
sed -i -e 's/DB_HOST=127.0.0.1/DB_HOST=db/' .env 
`

**Comment by mqu** [comment]
j'ai ouvert un merge-request sur la procédure de mise en oeuvre : docker/README.md.

**Comment by dbarzin** [comment]
requête validée.

**Comment by dbarzin** [comment]
Ce problème est-il définitivement résolu ? Pouvons-nous fermer cette demande ?
