### ISSUE TITLE
API et python 

### ISSUE THREAD

**Issue by pepes1lence** [dbarzin/mercator#171]
Je reviens vers vous avec un autre problème que nous avons lorsque nous essayons de joindre l'api avec du pyton.

Avec ce bout de code python:

```
    api_url = "http://mercator.my.local:8000/api/login"

    vdata = {'email':'toto@bidule.com', 'password':'mypasswww'}
    
    vheaders = {}
    vheaders['accept'] = 'application/json'
    vheaders['content-type'] = 'application/x-www-form-urlencoded'
    response = requests.post(api_url, headers=vheaders, data=vdata)
```
Nous avons ce message d'erreur en retour:

```
b'{"message":"This user does not exist, check your details"}'
(400) The request was malformed!
```
Nous avons le même retour avec le comtpe admin qui possède bien tous les droits/rôles

Est ce que vous savez si certains utilisateurs sont déjà parvenu à joindre l'API en python ?

**Comment by dbarzin** [comment]
L'utilisateur doit avoir le droit API. Il y a des exemples d'utilisation de l'API dans [la documentation](https://dbarzin.github.io/mercator/api/) de Mercator.

**Comment by pepes1lence** [comment]
C'est bien la documentation que nous avons suivi.
Il y a quelque chose que nous n'avons pas dû bien comprendre.
Dans la configuration des utilisateurs nous avons un compte admin qui dispose de tout les droits et pourtant nous ne parvenons pas à requêter l'API avec le compte admin.
Il n'y a rien de particulier à faire pour activer l'usage de l'API ? 

Excusez moi d'insister mais nous travaillons actuellement sur un projet d'automatisation pour nourrir automatiquement la base de données mercator. Sans API il nous faudrait exposer la base de données ce qui n'est pas idéal. 
Disons que cela reste la dernière option si jamais nous ne parvenons pas à utiliser l'API. 

Merci encore pour votre patience. 
Bien à vous.

**Comment by dbarzin** [comment]
Il semble que personne n'utilise l'API. Il y avait un bug dans le contrôleur d'authentification qui doit date de l'introduction de l'utilisation de l'AD. Cela devrait être corrigé.

**Comment by fendo64** [comment]
Bonjour dbarzin,

je suis un collègue de pepes1lence, et ta correction fonctionne.
Pour que ça fonctionne j'ai du exécuter cette commande dans le container docker "**php artisan passport:install**", si non j'avais l'erreur suivante:
```
LogicException: Unable to read key from file file:///var/www/mercator/storage/oauth-private.key in file /var/www/mercator/vendor/league/oauth2-server/src/CryptKey.php on line 67
```
Je pense qu'il faudrait ajouter cette commande "**php artisan passport:install**" dans le Dockerfile/composer du build de l'image.

Merci pour ton job.

**Comment by fendo64** [comment]
Bonjour dbarzin,

c'est bon nous avons ajouté la commande dans **entrypoint.sh**:
```
# configurer Passport
php artisan passport:install

# start application
php artisan serve --host=0.0.0.0
```

**Comment by dbarzin** [comment]
Merci, c'est commité.
