### ISSUE TITLE
[Docker] entrypoint.sh not found

### ISSUE THREAD

**Issue by ncastel-arvalis** [dbarzin/mercator#18]
Bonjour,

J'ai suivi (enfin il me semble!) la documentation d'installation docker (Poste W10 avec docker Desktop).

Au build, pas d'erreur notable, le composer install se lance sans erreur.
Au up, le service app sort en erreur : app_1  | /bin/sh: 1: /var/www/mercator/docker/entrypoint.sh: not found

Une idée?

**Comment by dbarzin** [comment]
Ce fichier se trouve pourtant bien dans le dépot des sources.
Il faut vérifier pourquoi ce fichier n'a pas été téléchargé lors de la première étape d'installation : 
    git clone https://github.com/dbarzin/mercator

**Comment by ncastel-arvalis** [comment]
Bonjour, 
Il est bien présent dans les sources.  mais ne semble pas être accessible lors de l'appel au docker-compose up
![2021-06-28_09h23_38](https://user-images.githubusercontent.com/68684525/123596471-85190900-d7f2-11eb-9415-40b7f864b219.png)

**Comment by ncastel-arvalis** [comment]
En décommentant la ligne 
``` 
entrypoint: /bin/sleep 3600 # pour debug
````

J'ai pu vérifié la présence du scipt dans le bon répertoire 
![2021-06-28_09h35_23](https://user-images.githubusercontent.com/68684525/123597998-54d26a00-d7f4-11eb-87f4-9f2a5b315eda.png)

Je poursuis mes investigations... Mais si vous avez une piste je suis preneur!  Merci!

**Comment by ncastel-arvalis** [comment]
Il s'agissait d'un problème d'encodage des retours chariots. (Dans Visual studio code, je suis passé pour le script de CRLF en LF)

Donc problème résolu ! je poursuis ma découverte de ce projet!

Merci
