### ISSUE TITLE
problème accés id via API sur certaines tables

### ISSUE THREAD

**Issue by tom6450** [dbarzin/mercator#186]
Bonjour,

Lorsque j'utilise l'api avec python et que je fais un "get", il y a certaines tables dont l'accés à l'identifiant ne fonctionne pas.

Par exemple api_url = "http://mercator.mycompany.company:8000/api/logical-servers/" fonctionne mais http://mercator.mycompany.company:8000/api/logical-servers/id" ne fonctionne pas.
Ceci se produit également sur les tables building, physical-servers et storage-devices.

En est-il de même pour vous?

**Comment by dbarzin** [comment]
Le problème est confirmé.

**Comment by dbarzin** [comment]
Un correctif a été implémenté.

**Comment by tom6450** [comment]
Merci bien, le correctif est fonctionnel.
