### ISSUE TITLE
Les besoins de sécurité

### ISSUE THREAD

**Issue by patshining** [dbarzin/mercator#2]
Bonjour,

Tout d'abord merci pour cet outil :)

Serait-il possible d'avoir une fonctionnalité permettant de définir plus précisément les besoins de sécurité ? Actuellement ceux-ci ne portent que sur la confidentialité (Public, Interne,...) et on ne peut pas préciser les besoins en termes de disponibilité, intégrité et traçabilité.

Encore merci.

**Comment by dbarzin** [comment]
Cette fonctionnalité va être ajoutée.

**Comment by dbarzin** [comment]
Fixed
$ git pull
$ php artisan migrate
