### ISSUE TITLE
Publication sur DockerHub

### ISSUE THREAD

**Issue by Sailman83** [dbarzin/mercator#214]
Bonjour,

L'installation sur Docker me parait compliqué par rapport à ce que je connais.

Avez-vous prévus :
1. Un publication sur DockerHub
2. Un ficher Docker fil qui integre direct la jour de GitHub (avec un RUN wget -O dans le dockerfile)

Car actuellement pour l'installation et les MAJ c'est très compliqué :)

Cordialement,

**Comment by dbarzin** [comment]
Bonjour,
Ce point se trouve dans le feuille de route. Cela mérite effectivement une amélioration.
Merci pour la demande,
Didier

**Comment by Sailman83** [comment]
C'est surtout un sacré boost pour l'utilisation de la solution.

Déploiement d'un Docker ~5min, 
Pour le moment, j'avoue ne même pas avoir essayer de l'installer

**Comment by asiffer** [comment]
Dans l'esprit de ce que propose @Sailman83 (avec les commentaires de @dbarzin), je pense qu'il faudrait faire les choses suivantes:
- [ ] revoir le `Dockerfile` pour générer une image simple et standalone (peut-être éviter ubuntu, simplifier l'entrypoint, utiliser sqlite par défaut etc.) -> installation "dev"
- [ ] revoir le `docker-compose` (healthcheck, env etc.) -> installation "prod"
- [ ] mettre en place une Github Action pour générer l'image à chaque merge et la mettre à dispo sur le hub github

**Comment by asiffer** [comment]
@Sailman83, @dbarzin si vous voulez tester:
```shell
docker run --rm -it --name mercator -p "127.0.0.1:8000":8000 ghcr.io/asiffer/mercator:latest
```
Puis: http://127.0.0.1:8000/

**Comment by asiffer** [comment]
Dans tous les cas il faudrait l'importer? Ou le choix doit-il être laissé à l'utilisateur?

**Comment by Sailman83** [comment]
Bonjour,
Attention, je vois pas la gestion des volumes persistent :)

Du coup, en cas d’arrêt et redémarrage on perd tout :)

**Comment by asiffer** [comment]
ah ah, en effet c'était vraiment en mode dev (plutôt pour tester)!
@dbarzin on doit pouvoir faire l'import selon la valeur d'une variable d'environnement, ex:
```shell
docker run --rm -it --name mercator -p "127.0.0.1:8000":8000 -e TESTING=1 ghcr.io/asiffer/mercator:latest
```
@Sailman83 je vais regarder mais ça va être qqch de simple comme:
```shell
docker run --rm -it --name mercator -p "127.0.0.1:8000":8000 -v "./db.sqlite:/var/www/mercator/database/db.sqlite" ghcr.io/asiffer/mercator:latest
```

**Comment by dbarzin** [comment]
Il y a une erreur lors du lancement de docker : 

In Connection.php line 712:
                                                                               
  Database (/var/www/mercator/db.sqlite) does not exist. (SQL: PRAGMA foreign  
  _keys = ON;)                                                                 
                                                                               

In SQLiteConnector.php line 34:
                                                          
  Database (/var/www/mercator/db.sqlite) does not exist.  
                                                          

Seeding: Database\Seeders\PermissionsTableSeeder

In Connection.php line 712:
                                                                               
  Database (/var/www/mercator/db.sqlite) does not exist. (SQL: PRAGMA foreign  
  _keys = ON;)                                                                 
                                                                               

In SQLiteConnector.php line 34:
                                                          
  Database (/var/www/mercator/db.sqlite) does not exist.  
                                                          
Conserver la base de données dans le répertoire /var/www/mercator/ n'est probablement pas une bonne idée car elle peut être téléchargée via le serveur web. /var/local est sans doute un meilleur endroit.

**Comment by asiffer** [comment]
Normalement il faut initier le fichier en local:
```shell
touch db.sqlite && chmod a+w db.sqlite
```
Puis le monter au moment de lancer le conteneur (attention à bien garder le `./` en début de fichier sinon docker crée un volume mais je crois que j'ai fait l'erreur dans le README):
```
docker run --rm -it --name mercator -p "127.0.0.1:8000":8000 -v "./db.sqlite:/var/www/mercator/database/db.sqlite" ghcr.io/dbarzin/mercator:latest
```

On peut changer la localisation du fichier avec la variable d'environnement `DB_DATABASE`. Exemple avec `/tmp/db.sqlite`:
```
docker run --rm -it --name mercator -p "127.0.0.1:8000":8000 -e "DB_DATABASE=/tmp/db.sqlite" -v "./db.sqlite:/tmp/db.sqlite" ghcr.io/dbarzin/mercator:latest
```

**Comment by asiffer** [comment]
Je pense que `docker` renvoit cette erreur parce qu'il ne trouve pas le fichier `db.sqlite` là où est lancée la commande (par conséquent il cherche à créer un volume et il ne peut créer un volume dont le nom a des caractères spéciaux). Pour être sûr de cela, le mieux est d'utiliser le chemin absolu de `db.sqlite`:

```shell
touch /tmp/db.sqlite && chmod a+w /tmp/db.sqlite
docker run --rm -it --name mercator -p "127.0.0.1:8000":80 -v /tmp/db.sqlite:/var/www/mercator/db.sqlite ghcr.io/dbarzin/mercator:latest
```

**Comment by dbarzin** [comment]
Même erreur : 

          $ docker run --rm -it --name mercator -p "127.0.0.1:8000":80 -v /tmp/db.sqlite:/var/www/mercator/db.sqlite ghcr.io/dbarzin/mercator:latest
          2023-04-28 14:22:48,763 INFO supervisord started with pid 1
          2023-04-28 14:22:49,769 INFO spawned: 'migrate' with pid 7
          2023-04-28 14:22:49,771 INFO spawned: 'nginx' with pid 8
          2023-04-28 14:22:49,775 INFO spawned: 'php' with pid 9
          
          In Connection.php line 712:
                                                                                         
            SQLSTATE[HY000] [14] unable to open database file (SQL: PRAGMA foreign_keys  
             = ON;)                                                                      
                                                                                         
          
          In Exception.php line 18:
                                                               
            SQLSTATE[HY000] [14] unable to open database file  
                                                               
          
          In PDOConnection.php line 40:
                                                               
            SQLSTATE[HY000] [14] unable to open database file  
                                                               
          
          Seeding: Database\Seeders\PermissionsTableSeeder
          
          In Connection.php line 712:
                                                                                         
            SQLSTATE[HY000] [14] unable to open database file (SQL: PRAGMA foreign_keys  
             = ON;)                                                                      
                                                                                         
          
          In Exception.php line 18:
                                                               
            SQLSTATE[HY000] [14] unable to open database file  
                                                               
          
          In PDOConnection.php line 40:
                                                               
            SQLSTATE[HY000] [14] unable to open database file  
                                                               
          
          2023-04-28 14:22:50,216 INFO exited: migrate (exit status 0; not expected)

**Comment by dbarzin** [comment]
En faisant ceci cela fonctionne : 

        touch /tmp/db.sqlite && chmod a+w /tmp/db.sqlite
        docker run --rm -it --name mercator -p "127.0.0.1:8000":80 -v $PWD/db.sqlite:/var/www/mercator/db.sqlite ghcr.io/dbarzin/mercator:latest

Par contre il y a une erreur 404 sur l'URL http://127.0.0.1:8000

**Comment by dbarzin** [comment]
J'ai découvert également qu'il fallait faire un composer update and composer install :

    # Install mercator deps 
    RUN composer update
    RUN composer install

mais je n'arrive pas à faire fonctionner docker.

**Comment by dbarzin** [comment]
Il manque le fichier db.sqlite dans le docker pour exécuter la version sans persistance.

**Comment by asiffer** [comment]
> En faisant ceci cela fonctionne :
> 
> ```
>     touch db.sqlite && chmod a+w db.sqlite
>     docker run --rm -it --name mercator -p "127.0.0.1:8000":80 -v $PWD/db.sqlite:/var/www/mercator/db.sqlite ghcr.io/dbarzin/mercator:latest
> ```
> 
> Par contre il y a une erreur 404 sur l'URL http://127.0.0.1:8000

Attention, ici il faut bien monter le fichier créé soit `/tmp/db.sqlite` (au lieu de `$PWD/db.sqlite`).

Pour la version sans persistance, c'est un choix à discuter mais je suis d'accord que l'on peut créer le fichier au début de l'exécution du docker (c'est ce que j'avais fait initialement avant de me raviser^^)

**Comment by pdurandfr** [comment]
Bonjour, j'ai fait une install "dev persistent", derrière un reverse proxy nginx qui fait le taf https. On est donc sur un proto bien solide, ou une petite prod.
+ Docker-compose : simple, à partir de l'image ghcr.io/dbarzin/mercator:latest, avec PV et .env très light qui peut peupler des données de démo.
+ Nginx.conf : forward des bonnes en-têtes pour passer la bonne URL d'accès aux routes Laravel -> le login/mdp esst bien envoyé sur l'URL nginx.
+ modif de Kernel.php et création d'un nouveau fichier middleware pour ré-utiliser le protocole employé sur le site présenté par NGINX (http ou https) => une fois l'étape de login on est re-dirigé sur le bon protocole pour accéder au site

Plutôt que de refaire un répertoire docker-compose etc, je propose de faire un .zip avec les fichiers docker-compose, laravel et nginx que j'ai utilisé et vous voyez comment l'intégrer proprement dans le répo?

**Comment by dbarzin** [comment]
Oui, tu peux également faire un pull request. Cela semble être une très bonne contribution.
