### ISSUE TITLE
Installation erreur PHP

### ISSUE THREAD

**Issue by GoodFeel91** [dbarzin/mercator#215]
Bonjour,

Je rencontre un problème lors de l'initialisation de la base de données MySQL. Lorsque je lance la commande **php artisan migrate --seed**, une erreur (ci-dessous) apparait au moment de traiter le fichier Role.php

![image](https://user-images.githubusercontent.com/78422494/191248174-d02bc629-0faf-493a-b152-53609794da04.png)

Malgré cela, je continue l'install jusqu'au bout, j'arrive à accéder à l'interface de connexion mais les identifiants par défaut (admin@admin.com / password) ne fonctionnent pas. Je pense que le script PHP n'a pas fait le boulot jusqu'au bout à cause de l'erreur sur le Role.php.

Quand pourraisè-e débuguer ce problème et réussir à me connecter à l'application ?

Merci par avance pour votre aide.

**Comment by dbarzin** [comment]
Bonjour,

Le problème est probablement corrigé mais cela ne se produit pas lors des tests d'intégration ni dans mon environnement de développement.

Il faut reprendre l'installation à 

    php artisan migrate --seed

Quelle version de PHP utilises-tu ?
Quel OS ?

**Comment by GoodFeel91** [comment]
Bonjour,

Merci pour le retour.

Quand je relance la commande php artisan migrate --seed, la même erreur se produit.

Version PHP : 7.4.30
OS : Debian 11

**Comment by dbarzin** [comment]
Il faut utiliser PHP version >= 8.0. Composer a du l'installer mais elle n'est pas dans ton PATH.

Puis, il faut mettre à jour le projet avant 

    git pull

en ensuite :

    php artisan migrate

**Comment by GoodFeel91** [comment]
Effectivement, j'ai passé la version de PHP en 8.x et fait un git pull et la commande php artisan migrate passe bien sans erreur.

Par contre, toujours impossible de me connecter à l'interface avec les identifiants par défaut.

Je lance la commande 

`php artisan serve --host 192.168.1.178 --port 8000`

correspondant à mon serveur. 

J'ai trouvé trace d'une log dans storage/logs/laravel.log


```
[2022-09-20 19:14:07] local.INFO: LDAP (ldap://127.0.0.1:389) - Operation: Binding - Username: cn=user,dc=local,dc=com
[2022-09-20 19:14:07] local.ERROR: Can't contact LDAP server {"code":null}
```

Il semble tenter une connexion LDAP alors que je n'ai pas configuré cette partie.

**Comment by dbarzin** [comment]
essaye

    php artisan serve --host 0.0.0.0 --port 8000

Le mar. 20 sept. 2022 à 21:16, GoodFeel91 ***@***.***> a
écrit :

**Comment by GoodFeel91** [comment]
Idem, impossible de me connecter à l'appli, avec la même erreur LDAP. J'ai vérifié le fichier .env, la partie LDAP est bien commentée.

**Comment by dbarzin** [comment]
Pour le message d'erreur, cela ne doit pas poser de problème.
Tu essayes bien d'ouvrir l'URL http://127.0.0.1:8000 ?



Le mar. 20 sept. 2022 à 21:39, GoodFeel91 ***@***.***> a
écrit :

**Comment by GoodFeel91** [comment]
Je viens d'installer une interface graphique sur ma Debian pour me connecter sur le 127.0.0.1 mais toujours le même problème à l'authentification.

Dois-je peut-être retenter l'install sur une Ubuntu ?

**Comment by dbarzin** [comment]
J'ai la même erreur mais cela n'a pas d'impact.
Les crédentials par défaut sont : admin@admin.com / password

**Comment by dbarzin** [comment]
Peux-tu essayer de réinstaller la DB

    php artisan migrate:fresh --seed

**Comment by GoodFeel91** [comment]
Ca fonctionne bien après réinstallation de la DB. J'ai réussi à me connecter à l'appli (en local en tout cas).

Merci pour ta précieuse aide.

**Comment by GoodFeel91** [comment]
Dernière question : Est-ce possible de se connecter depuis un client distant si on renseigne l'IP du serveur (comme je l'avais fait au début) ?

**Comment by GoodFeel91** [comment]
Non, c'est bon, ça fonctionne bien depuis mon client distant. Tout est OK.

Merci encore pour ton aide.
