### ISSUE TITLE
Procédure d'installation non concluante

### ISSUE THREAD

**Issue by 3pypoisson2** [dbarzin/mercator#217]
Bonjour,

J'ai bien lu la documentation et pourtant, je n'arrive pas à installer le produit : le "composer" ne s'installe pas correctement (la version préconisée est "deprecated" et génère de multiples erreurs). J'ai bien tenté de faire une mise à jour : même problème, même en repartant de zéro. j'ai toujours ces messages : 

 " PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /usr/share/php/Symfony/Component/Console/Helper/HelperSet.php on line 104"
J'ai bien tenté l'approche d'upgrader en PHP8 : idem.

"php artisan vendor:publish --all
PHP Warning:  require(/var/www/mercator/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/mercator/artisan on line 18
PHP Stack trace:
PHP   1. {main}() /var/www/mercator/artisan:0
PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/mercator/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/mercator/artisan:18
Stack trace:
#0 {main}
  thrown in /var/www/mercator/artisan on line 18"

Je bloque depuis quelques heures .... si une bonne âme pouvait m'aider ..
Config : Linux Mint 20.3
Merci d'avance.

**Comment by dbarzin** [comment]
Il faut composer2 et PHP 8. 
Pour composer : https://getcomposer.org/download/
Pour PHP 8 : https://linuxhint.com/install-php-8-on-linux-mint-20/

**Comment by dbarzin** [comment]
Pas de retour
