### ISSUE TITLE
Use of deleted table in logical report view

### ISSUE THREAD

**Issue by Foxi352** [dbarzin/mercator#219]
All from current master branch (27/09/2022):

When choosing a network or subnet from the logicial_infrastructure report it yields an error:
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mercator.external_connected_entity_network' doesn't exist (SQL: select * from `external_connected_entities` inner join `external_connected_entity_network` on `external_connected_entities`.`id` = `external_connected_entity_network`.`external_connected_entity_id` where `external_connected_entity_network`.`network_id` = 4 and `external_connected_entities`.`deleted_at` is null order by `name` asc)
```

I think i found the root cause.

In one of the lastest migrations you delete the table : https://github.com/dbarzin/mercator/blob/017b6aa37b206be27eff11e334322b3d65e45f2d/database/migrations/2022_08_11_165441_add_vpn_fields.php#L31

But here you use the table: https://github.com/dbarzin/mercator/blob/017b6aa37b206be27eff11e334322b3d65e45f2d/app/Http/Controllers/Admin/ReportController.php#L622

**Comment by dbarzin** [comment]
Corrigé.
