### ISSUE TITLE
 Integrity constraint violation

### ISSUE THREAD

**Issue by emeygret** [dbarzin/mercator#22]
Erreur lors de l'initialisation de la bdd:

php artisan migrate --seed

`Migrated:  2021_07_14_071311_create_certificates_table (77.12ms)                                                                                                                                        [45/1403]
Migrating: 2021_08_08_125856_config_right

   Illuminate\Database\Eloquent\ModelNotFoundException

  No query results for model [App\Role] 1

  at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:434
    430▕         } elseif (! is_null($result)) {
    431▕             return $result;
    432▕         }
    433▕
  ➜ 434▕         throw (new ModelNotFoundException)->setModel(
    435▕             get_class($this->model), $id
    436▕         );
    437▕     }
    438▕

      +3 vendor frames
  4   database/migrations/2021_08_08_125856_config_right.php:30
      Illuminate\Database\Eloquent\Model::__callStatic()

      +21 vendor frames
  26  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()`

**Comment by emeygret** [comment]
install de la v1 puis upgrade depuis le master ok

**Comment by dbarzin** [comment]
Merci, corrigé !
