### ISSUE TITLE
Installation incomplète : duplicate primary key in permissions table id=262, 

### ISSUE THREAD

**Issue by ianbogda** [dbarzin/mercator#23]
Bonjour,
Vendredi j’ai tenté d’installer la dernière version du 10/08. Sans succès.
Il a fallu que je descende à la version du commit 219acda847e1634c96f9e9fbb759e435d81d4155
Il y a une erreur sur la migration avec une clé primaire dupliquée (262, configure) dans la table des permissions.

**Comment by dbarzin** [comment]
Désolé, il y avait une erreur dans la dernière migration.
Pour corriger :
    git pull 
    php artisan migrate

**Comment by ianbogda** [comment]
Super.
Merci pour tout
