### ISSUE TITLE
Connexion LDAP

### ISSUE THREAD

**Issue by Neoliapaul** [dbarzin/mercator#230]
Bonjour,

Tout d'abord, félicitations pour le développement de ce superbe outil ! Une véritable plus-value quand on est une DSI qui a son scope qui n'arrête pas de grandir.

Pour la connexion LDAP, j'ai configuré dans le fichier .env, mais je n'ai pas l'impression que ça fasse grand chose. Est-ce implémenté ? Si oui, comment ajoute t-on un utilisateur depuis l'AD ?

Bonne réception,

**Comment by dbarzin** [comment]
Il faut aller voir dans la documentation de [LdapRecord](https://ldaprecord.com/docs/laravel/v2/configuration#using-a-published-configuration-file).

**Comment by Neoliapaul** [comment]
Très bien,

Mais une fois que j'ai validé la connexion avec l'AD avec la commande `sudo php artisan ldap:test`, comment configure t-on les profils utilisateurs ?

**Comment by dbarzin** [comment]
Les profils utilisateurs sont configurés dans Mercator. L'AD est utilisé pour valider le mot de passe et le droit d'accès à l'application.

**Comment by Neoliapaul** [comment]
Je viens de comprendre !

Dans storage/logs/laravel.log, j'avais ceci : `[2022-10-11 19:57:38] local.INFO: User was denied authentication because their model is soft-deleted. `

Le compte en question existait dans la base en mode "soft deleted" et en mode actif, en supprimant les comptes "soft deleted" , le problème a été résolu.

Merci
