### ISSUE TITLE
Génération rapport 

### ISSUE THREAD

**Issue by GoodFeel91** [dbarzin/mercator#232]
Bonjour,

Après avoir peuplé ma cartographie, je souhaitais générer des rapports par vue afin de schématiser les relations entre les actifs mais lors de la génération des rapports je rencontre une erreur "500 - Server error".

![image](https://user-images.githubusercontent.com/78422494/195138474-e13b4043-2eda-493e-ba34-7ca15b2b4b4c.png)

Comme indiqué dans la doc, j'ai modifié le php.ini pour passer le paramètre memory_limit à 512 mais sans succès. Je n'ai rien trouvé de spécial dans les logs Apache pouvant me mener à une piste.

Sur la page http://IP_SERVER:8000/admin/doc/report, aucun lien ne fonctionne, je tombe toujours sur la meme erreur 500 (y compris les sections Listes et Audit).

Je viens de mettre à jour l'application via Git.

Merci par avance pour votre aide.

**Comment by dbarzin** [comment]
?

**Comment by GoodFeel91** [comment]
Bonjour,

Désolé, mon texte n'a pas été pris.

Bonjour,

Après avoir peuplé ma cartographie, je souhaitais générer des rapports par vue afin de schématiser les relations entre les actifs mais lors de la génération des rapports je rencontre une erreur "500 - Server error".

![image](https://user-images.githubusercontent.com/78422494/195138474-e13b4043-2eda-493e-ba34-7ca15b2b4b4c.png)

Comme indiqué dans la doc, j'ai modifié le php.ini pour passer le paramètre memory_limit à 512 mais sans succès. Je n'ai rien trouvé de spécial dans les logs Apache pouvant me mener à une piste.

Sur la page http://IP_SERVER:8000/admin/doc/report, aucun lien ne fonctionne, je tombe toujours sur la meme erreur 500.

Je viens de mettre à jour l'application via Git.

Merci par avance pour votre aide.

**Comment by dbarzin** [comment]
Bonjour,
Pouvez-vous confirmer que le reste de l'application fonctionne donc sans erreurs ?
Avez-vous une erreur dans storage/logs/laravel.log ?
Didier

**Comment by dbarzin** [comment]
Il manque des classes PHP :

    sudo apt-get install php-dom php-xml

**Comment by GoodFeel91** [comment]
Effectivement, j'avais une version de PHP (7.4) qui était installé et qui entrait en collision avec la version 8. Et donc les deux classes étaient installées mais sur la version 7.

J'ai supprimé PHP 7 pour éviter tout cela.

Merci encore pour votre aide, je peux à présent générer les rapports sans problème.
