### ISSUE TITLE
Exception raised on /admin/report/physical_infrastructure

### ISSUE THREAD

**Issue by PaulVnc** [dbarzin/mercator#24]
Hi,
When going on the **/admin/report/physical_infrastructure** endpoint (via the navbar) I get this exception:

![image](https://user-images.githubusercontent.com/45337343/129685341-b1297597-4210-4297-929b-bddc5d2f60bb.png)

I only get this issue with the physical infrastructure view, and I can't figure out wether it is a problem in the php code or a problem with the database not being complete enough.

Otherwise, great tool ! It definitely helped me a lot in my task !

**Comment by PaulVnc** [comment]
For information, my mercator deploy runs on an Ubuntu 20.04 VM

**Comment by dbarzin** [comment]
Hello, I cannot reproduce it. Have you had errors during the installation ?
Check you have the latest version from github  ; 
git pull
php artisan migrate
Then send me a more complete log.

**Comment by PaulVnc** [comment]
Thanks for the quick reply !
I don't remember facing any error during the installation,
I tried pulling the latest update, but I still get the same error
Here is the complete error log shared on https://flareapp.io/share/dmkyMge7#F61

I could try to reinstall the whole project...

**Comment by dbarzin** [comment]
ok fixed, just pull the change.

**Comment by PaulVnc** [comment]
Thanks a lot !
I then encountered an error at line 810 of the same file, and fixed it buy changing building to site (which was refered to in the if statement juste above)
Should I do a new branch and a merge request or do you prefer to fix it on your side aswell?

**Comment by dbarzin** [comment]
Let's propose a merge request !
