### ISSUE TITLE
Mémorisation de la configuration de l'envoi de notification par mail lorsque des certificats arrivent à expiration

### ISSUE THREAD

**Issue by LPailles** [dbarzin/mercator#240]
Bonjour

J'ai beau remplir complètement le formulaire dans /admin/config/cert et cliquer sur [Save] (j'ai alors le message "Configuration saved !"), le paramétrage ne subsiste pas au-delà de quelques heures.

**Comment by dbarzin** [comment]
Bonjour,
Pouvez-vous répondre à ces quelques questions :
Y-a-til une erreur dans le fichier "storage/logs/laravel.log" lorsque vous sauvez la configuration ? 
La configuration est-elle sauvegardée dans le fichier de configuration "config/mercator-config.php" ?
Apache a-t-il le droit d'écrite sur le fichier de configuration "config/mercator-config.php" ?
Merci,
Didier

**Comment by dbarzin** [comment]
Pas de retour
