### ISSUE TITLE
(SQL: alter table `network_subnetwork` rename index `subnetword_id_fk_1492377` to `subnetwork_id_fk_1492377`)

### ISSUE THREAD

**Issue by flapvhd** [dbarzin/mercator#25]
Bonjour Didier,
Je souhaite tester votre application mais j'ai une erreur lors du "php artisan migrate --seed" initial, lancé sur la derniére version de l'appli, récupérére sur le site ce matin, avec la doc présente ici https://github.com/dbarzin/mercator/blob/master/INSTALL.md.
J'effectue l'install sur une VM debian 10, dimensionnée selon les recommandations...
Merci ce magnifique développement et pour votre aide.

Migrating: 2021_05_19_161123_rename_subnetwork

   Illuminate\Database\QueryException

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'index `subnetword_id_fk_1492377` to `subnetwork_id_fk_1492377`' at line 1 (SQL: alter table `network_subnetwork` rename index `subnetword_id_fk_1492377` to `subnetwork_id_fk_1492377`)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:692
    688▒         // If an exception occurs when attempting to run a query, we'll format the error
    689▒         // message to include the bindings with SQL, which will make this exception a
    690▒         // lot more helpful to the developer instead of just the database's errors.
    691▒         catch (Exception $e) {
  ▒ 692▒             throw new QueryException(
    693▒                 $query, $this->prepareBindings($bindings), $e
    694▒             );
    695▒         }
    696▒     }

      +12 vendor frames
  13  database/migrations/2021_05_19_161123_rename_subnetwork.php:26
      Illuminate\Support\Facades\Facade::__callStatic("table")

      +21 vendor frames
  35  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by flapvhd** [comment]
Juste une précision, j'avais commencé un test hier soir, mais j'ai tout effacé et récupéré par git la version de ce matin. Avant de relancer "php artisan migrate --seed", j'avais pris soin de faire un drop database mercator et de tout récréer...

**Comment by dbarzin** [comment]
Utilises-tu bien MySQL et pas MariaDB ?
mysql --version

**Comment by flapvhd** [comment]
Non, c'est MariaDB, en effet...

**Comment by dbarzin** [comment]
Le framework Laravel ne fonctionne pas sous MariaDB, il faut installer MySQL.

**Comment by flapvhd** [comment]
Ok, je ne savais pas. Je vais m'y atteler, merci pour les réponses rapides.
