### ISSUE TITLE
Filtre pour flux applicatif

### ISSUE THREAD

**Issue by Neoliapaul** [dbarzin/mercator#250]
Bonjour,

Dans la vue des flux applicatifs, lorsqu'un flux est associé à un service, lui même associé à une application, on ne voit pas le flux en question si on filtre au niveau de l'application.
Est-ce normal ?

Bonne réception,

**Comment by dbarzin** [comment]
Très bonne remarque, cela va être implémenté.
Merci,
Didier

**Comment by dbarzin** [comment]
Je viens de vérifier avec la base de données de test. Les flux sont biens présents :

![image](https://user-images.githubusercontent.com/43208232/199593654-c38c86d1-58fb-4c35-aba4-e3a1477432f6.png)

et dans le code, il y a bien un filtre sur les flux associés aux services de l'application.

As-tu un exemple ?

**Comment by Neoliapaul** [comment]
En effet, le cas semble se produire quand une application est lié au service d'une autre application, et qu'on ne sélectionne pas le bloc applicatif
Sans Bloc applicatif
![image](https://user-images.githubusercontent.com/115541291/199672783-562a12e3-3cb6-49a4-a2c2-6c88e3420398.png)
Avec bloc applicatif
![image](https://user-images.githubusercontent.com/115541291/199672826-1dd69f54-70a2-4d4f-bc34-7e8c74caafe6.png)

Dans l'exemple, test service 1 est un service de testapp2

![image](https://user-images.githubusercontent.com/115541291/199672955-ec2ac125-3d4d-42f8-ab88-91fe78c9f281.png)

Et au niveau des flux

![image](https://user-images.githubusercontent.com/115541291/199673004-c3b8e692-be79-4518-9c03-ab180fe937af.png)

**Comment by dbarzin** [comment]
La sélection des objets à afficher dans cette vue se passe en trois étapes :
- sélectionner toutes les applications, modules, services et bases de données du filtre
- identifier les flux entre les objects sélectionnés
- supprimer les objets qui n'ont pas de flux

Le service "TEST SERVICE 1" n'est pas sélectionné dans la première étape du filtre.

**Comment by dbarzin** [comment]
Tu devrais pouvoir générer le graphique que tu souhaites avec les filtres de la page d'exploration de la cartographie : 
![image](https://user-images.githubusercontent.com/43208232/200176457-79ee4817-5e78-4664-a77e-0218ad0d65d3.png)
C'est sur la branche dev uniquement pour l'instant.

**Comment by Neoliapaul** [comment]
J'ai mis à jour Mercator de mon côté et tester le filtre, c'est top ça réponds au besoin.
Merci.
