### ISSUE TITLE
Enhancement RPO/RTO

### ISSUE THREAD

**Issue by TheGiu99** [dbarzin/mercator#256]
En plus des besoin en DICP, je pense que ça serait bien d'avoir les champs de RTO et RPO.
De même pour le visuel avoir une information visuelle indicant qu'une application est critique (RTO/RPO faibles) ou sensible (Besoin Intégrité, Confidentialité ou Traçabilité très élevé)

**Comment by dbarzin** [comment]
Pour les RTO et RPO, ce serait deux entiers qui représente le nombre d'heure.
Pour le visuel indiquant qu'une application est critique (RTO/RPO faibles) ou sensible, as-tu une idée précise ?

**Comment by TheGiu99** [comment]
Pour les RTO/RPO oui un système d'entiers allant de 0 à 4 correspondant à une échelle définie en Interne comme pour les DICP.
Concernant le visuel je pensais à une ligne en plus sous le nom indiquant en rouge (par exemple) avec écrit sensible

**Comment by dbarzin** [comment]
Je développe une solution basée sur le composant [Bootstrap Duration Picker](https://github.com/koss-lebedev/bootstrap-duration-picker).
Les champs RTO et RPO contiendront le nombre de secondes dans la base de données.

**Comment by dbarzin** [comment]
![image](https://user-images.githubusercontent.com/43208232/207711599-e70c6d4f-31e6-4aac-a535-1882dfb2dcee.png)

**Comment by dbarzin** [comment]
Les champs RTO et RPO ont été ajoutés.
