### ISSUE TITLE
page de démarrage

### ISSUE THREAD

**Issue by Jyc44** [dbarzin/mercator#26]
Bonjour Didier

reste quelques jours de calme pour voir de plus près ce travail.
Installation toute fraiche de ce midi :-)
quelle est la page de démarrage?
quand je pointe sur .../public j'ai une redirection sur une page login qui n'existe pas
pb de droits sur les fichiers/répertoires?

merci?

(install sur VM - Vhost apache sur /var/www/mercator/public)

**Comment by ianbogda** [comment]
Bonjour,

Je vois 3 points à vérifier.
Le 1er est que le répertoire appartient bien à apache

```bash
chown -R www-data: /var/www/mercator
```
Le second est que le mode rewrite d'apache soit actif
```bash
a2enmod rewrtire
systemctl restart apache2
```
Et le dernier est que dans votre fichier de vhost, il y ait les information suivante:
```bash
<VirtulaHost *:80>
    DocumentRoot /var/www/mercator/public
    <Directory>
        Options -Indexes +FolloSymlinks
        AllowOverride All
        Require All granted
    </Directory>
</VirtualHost>
systemctl restart apache2
```

**Comment by dbarzin** [comment]
Après le démarrage de Mercator avec la commande
php artisan serve
L'application répond sur http://127.0.0.1:8000
Pour la configuration avec Apache, cela fonctionne mais ce n'est pas documenté pour l'instant.
Il faut aller voir dans la documentation de Laravel

**Comment by Jyc44** [comment]
Ok merci
pas mieux mais je vais avancer sur la config
