### ISSUE TITLE
Lien double vue "système d'information" 

### ISSUE THREAD

**Issue by Neoliapaul** [dbarzin/mercator#267]
Bonjour,

Dans la représentation graphique de la vue système d'information, lorsque le lien entre processus et opération et entre processus et activités sont tout les deux renseignés, le lien de la vue se fait aux deux niveaux

![image](https://user-images.githubusercontent.com/115541291/208137594-4fab3977-6835-4055-92b3-c1ae727d639e.png)

Je pense qu'il serait plus pertinent que cela se fasse uniquement au niveau le plus fin

Bonne réception,

**Comment by dbarzin** [comment]
Bonne remarque ! Je met cela dans la liste des prochaines petites améliorations.
Ma proposition serait de faire apparaitre les liens et objets en fonction du niveau de granularité utilisé.
Merci,
Didier

**Comment by dbarzin** [comment]
La fonction a été ajoutée.

**Comment by Neoliapaul** [comment]
Parfait,
Je confirme que tout est fonctionnel ! Merci.
