### ISSUE TITLE
Undefined variable $peripheral - Exploration

### ISSUE THREAD

**Issue by EV0IR** [dbarzin/mercator#288]
Bonjour,
Suite à la mise à jour aujourd'hui d'une version de mai 2022, nous ne pouvons plus explorer les objets.
Si vous avez une idée, nous sommes cela nous intéresse :)

Message Erreur
in /var/www/mercator/app/Http/Controllers/Admin/ExplorerController.php (line 130)

            // Wifi terminals
            $wifiTerminals = DB::table('wifi_terminals')->select('id', 'name', 'site_id', 'building_id')->whereNull('deleted_at')->get();
            foreach ($wifiTerminals as $wifiTerminal) {
                $this->addNode($nodes, 6, $this->formatId('WIFI_', $wifiTerminal->id), $wifiTerminal->name, '/images/wifi.png', 'wifi-terminals');
                **if ($peripheral->building_id !== null) {**
                    $this->addLinkEdge($edges, $this->formatId('WIFI_', $wifiTerminal->id), $this->formatId('BUILDING_', $wifiTerminal->building_id));
                } elseif ($peripheral->site_id !== null) {
                    $this->addLinkEdge($edges, $this->formatId('WIFI_', $wifiTerminal->id), $this->formatId('SITE_', $wifiTerminal->site_id));
                }
            }

HandleExceptions->handleError() in /var/www/mercator/app/Http/Controllers/Admin/ExplorerController.php (line 130)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Controller.php -> explore (line 54)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php -> callAction (line 45)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Route.php -> dispatch (line 262)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Route.php -> runController (line 205)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Router.php -> run (line 721)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> Illuminate\Routing\{closure} (line 128)
Pipeline->Illuminate\Pipeline\{closure}() in /var/www/mercator/app/Http/Middleware/SetLocale.php (line 28)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
Pipeline->Illuminate\Pipeline\{closure}() in /var/www/mercator/app/Http/Middleware/AuthGates.php (line 32)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php -> Illuminate\Pipeline\{closure} (line 50)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php -> Illuminate\Pipeline\{closure} (line 44)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php -> Illuminate\Pipeline\{closure} (line 78)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php -> Illuminate\Pipeline\{closure} (line 49)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php -> Illuminate\Pipeline\{closure} (line 121)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php -> handleStatefulRequest (line 64)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php -> Illuminate\Pipeline\{closure} (line 37)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php -> Illuminate\Pipeline\{closure} (line 67)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> Illuminate\Pipeline\{closure} (line 103)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Router.php -> then (line 723)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Router.php -> runRouteWithinStack (line 698)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Router.php -> runRoute (line 662)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Router.php -> dispatchToRoute (line 651)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php -> dispatch (line 167)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> Illuminate\Foundation\Http\{closure} (line 128)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php -> Illuminate\Pipeline\{closure} (line 21)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php -> handle (line 31)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php -> Illuminate\Pipeline\{closure} (line 21)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php -> handle (line 40)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php -> Illuminate\Pipeline\{closure} (line 27)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/fruitcake/laravel-cors/src/HandleCors.php -> Illuminate\Pipeline\{closure} (line 37)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php -> Illuminate\Pipeline\{closure} (line 86)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/fideloper/proxy/src/TrustProxies.php -> Illuminate\Pipeline\{closure} (line 57)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> handle (line 167)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php -> Illuminate\Pipeline\{closure} (line 103)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php -> then (line 142)
in /var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php -> sendRequestThroughRouter (line 111)
Kernel->handle() in /var/www/mercator/public/index.php (line 55)
require_once('/var/www/mercator/public/index.php') in /var/www/mercator/server.php (line 21) 

Stack Trace
ErrorException:
Undefined variable $peripheral

  at /var/www/mercator/app/Http/Controllers/Admin/ExplorerController.php:130
  at Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
     (/var/www/mercator/app/Http/Controllers/Admin/ExplorerController.php:130)
  at App\Http\Controllers\Admin\ExplorerController->explore()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54)
  at Illuminate\Routing\Controller->callAction()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45)
  at Illuminate\Routing\ControllerDispatcher->dispatch()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Route.php:262)
  at Illuminate\Routing\Route->runController()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Route.php:205)
  at Illuminate\Routing\Route->run()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Router.php:721)
  at Illuminate\Routing\Router->Illuminate\Routing\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/app/Http/Middleware/SetLocale.php:28)
  at App\Http\Middleware\SetLocale->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/app/Http/Middleware/AuthGates.php:32)
  at App\Http\Middleware\AuthGates->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:50)
  at Illuminate\Routing\Middleware\SubstituteBindings->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:44)
  at Illuminate\Auth\Middleware\Authenticate->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:78)
  at Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49)
  at Illuminate\View\Middleware\ShareErrorsFromSession->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:121)
  at Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:64)
  at Illuminate\Session\Middleware\StartSession->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37)
  at Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:67)
  at Illuminate\Cookie\Middleware\EncryptCookies->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103)
  at Illuminate\Pipeline\Pipeline->then()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Router.php:723)
  at Illuminate\Routing\Router->runRouteWithinStack()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Router.php:698)
  at Illuminate\Routing\Router->runRoute()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Router.php:662)
  at Illuminate\Routing\Router->dispatchToRoute()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Routing/Router.php:651)
  at Illuminate\Routing\Router->dispatch()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:167)
  at Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:128)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21)
  at Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php:31)
  at Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:21)
  at Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php:40)
  at Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27)
  at Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/fruitcake/laravel-cors/src/HandleCors.php:37)
  at Fruitcake\Cors\HandleCors->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php:86)
  at Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/fideloper/proxy/src/TrustProxies.php:57)
  at Fideloper\Proxy\TrustProxies->handle()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:167)
  at Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103)
  at Illuminate\Pipeline\Pipeline->then()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:142)
  at Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
     (/var/www/mercator/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:111)
  at Illuminate\Foundation\Http\Kernel->handle()
     (/var/www/mercator/public/index.php:55)
  at require_once('/var/www/mercator/public/index.php')
     (/var/www/mercator/server.php:21)

**Comment by dbarzin** [comment]
C'est corrigé. Il faudra également migrer la DB car la table contenant les liens physique entre les équipements a été ajoutée.

**Comment by EV0IR** [comment]
Merci pour la réactivité, cela fonctionne parfaitement.
