### ISSUE TITLE
Problème sur formulaire Bornes Wifi

### ISSUE THREAD

**Issue by Lb59** [dbarzin/mercator#29]
Bonjour, 
Le formulaire de saisie des bornes wifi ne fait pas apparaitre le champs physical_switch_id présent dans la table wifi_terminals.
Ce champs permets apparemment de lier la borne wifi à la table des switchs ( physical_swithes).

**Comment by ianbogda** [comment]
Dans l'optique de compléter la cartographie, il y a le même sujet sur les éléments suivants :

- phones
- physical_servers
- storage_devices
- wifi_terminals (déjà cité dans cette 'issue')
- workstations

**Comment by dbarzin** [comment]
A l'origine, il s'agit d'une erreur lors de la conception de l'application qui a été corrigé dans les formulaires mais pas dans la base de données. Les bornes Wifi et les autres équipements pourraient être reliés aux commutateurs physiques mais cela n'apporte pas grand chose à la cartographie à moins d'avoir deux réseaux physiquement distincts. Le lien entre les équipements et leurs localisations physique devrait suffire dans la majeure partie des cas.
J'essaye de rester au plus proche du modèle de données proposé par l'ANSSI dans son guide sur la cartographie.
