### ISSUE TITLE
Erreur 2054 - php artisan migrate --seed

### ISSUE THREAD

**Issue by kifjeff** [dbarzin/mercator#31]
Si lors de l’exécution de la commande  `php artisan migrate --seed` vous avez l'erreur : 
_Illuminate\Database\QueryException_
__ SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = mercator and table_name = migrations and table_type = 'BASE TABLE')_

C'est surement à cause de de la version de Mysql. 
Ces commandes SQL permettent de mettre votre mot de passe en native pour le compte utilisé :
`ALTER USER 'mercator_user'@'localhost' IDENTIFIED WITH mysql_native_password BY 's3cr3t';
FLUSH PRIVILEGES;`

**Comment by dbarzin** [comment]
Quelle version de mysql utilises-tu ?
Quel version d'OS ?

**Comment by kifjeff** [comment]
Debian 10.10 et mysql 8.0.26
