### ISSUE TITLE
Batiments / Salles

### ISSUE THREAD

**Issue by rssiHDL** [dbarzin/mercator#32]
Bonjour,

D'abord, merci pour ce travail. RSSI, dans un établissement de santé, je commence à me servir de Mercator et il devrait répondre à notre besoin notamment pour répondre mieux qu'actuellement à l'instruction 309 qui nous demande une cartographie de notre SI. Et de prime abord facilement.
Une question néanmoins. Dans vue des infrastructures physiques Bâtiments / Salles, on ne peut pas (ou je n'ai pas trouvé) affecter une salle à un bâtiment, seulement à un site. Est-ce que la logique ne serait pas  ? :
Site -->bâtiment-->salles-->Baie...
Merci de votre retour.
Cordialement

JM EMERAS

**Comment by dbarzin** [comment]
Salle et bâtiment sont un seul et même objet qu'il est possible d'affecter à un site.
Site -->bâtiment / salle--> Baie ...
Généralement une convention de nomage des locaux est déjà en place dans l'établissement. 
Le nom de chaque salle est souvent unique pour tout l'établissement même si celui-ci occupe plusieurs sites.

**Comment by rssiHDL** [comment]
OK. Mais dans ce cas pourquoi faire le distinguo. Le nom de la salle suffit avec une bonne convention de nommage...

**Comment by dbarzin** [comment]
Cela dépend de la manière dont faite la modélisation de l'infrastructure physique.
Le nom de la salle est généralement suffisant mais parfois des bâtiments techniques n'ont pas de salles identifiées.

**Comment by rssiHDL** [comment]
Dans mon cas la limite vient plutôt du fait qu'un même site à plusieurs bâtiments. Ce qui rend la visualisation moins claire puisque sont rattachés au même code site des salles avec un code bâtiment différent. J'ai contourné en prenant les bâtiments comme site, c'est moins génant

**Comment by dbarzin** [comment]
Merci pour ton retour. Chez nous, les bâtiments sur un même site géographiques sont regroupés sur la dénomination du site dans Mercator et la dénomination des salles permet de clairement identifier le bâtiment sur le site concerné.
