### ISSUE TITLE
Unknown column 'guid'

### ISSUE THREAD

**Issue by fyamani** [dbarzin/mercator#334]
Bonjour

J'ai configuré l'accès ldap qui semble fonctionner mais au moment de me logguer j'ai l'erreur:
#Unknown column 'guid' in 'where clause' (SQL: select * from `users` where `guid` = 

il semble y avoir un bug. le fichier responsable de l'ajout des colonnes guid et domain semble avoir été supprimé en avril 2022:
https://github.com/dbarzin/mercator/commit/adcbbe4c14a9bc3ba2cc649a9b9a51584b3e049e

Est ce que mon approche est correcte ?
Merci

**Comment by dbarzin** [comment]
Ce fichier de migration est créer par lors de l'exécution de la commande

    php artisan vendor:publish --all

ll a été commité par erreur en 2022.

A vérifier avec :

    grep -r add_ldap_columns_to_users_table vendor/*

**Comment by fyamani** [comment]
A priori la cmd ci dessous est manquante dans le fichier entrypoint.sh
`php artisan vendor:publish --all`

je l'ai ajouté et j'ai relancé l'install et tout fonctionne

merci

**Comment by dbarzin** [comment]
Effectivement, il n'a jamais été prévu d'utiliser l'AD avec Docker.
Vous solution va poser un problème car cette commande ne peut être exécutée qu'un fois car elle génère une migration.
Lors démarrage suivant la migration va générer une erreur car le champ est déjà présent.

**Comment by krptg0** [comment]
Je me permet de rouvrir cette issue.

Dans le CT, j'ai lancé une fois au démarrage la commande `php artisan vendor:publish --all`

Cela dit, j'ai quand même la même erreur de colonne manquante guid.

**Comment by dbarzin** [comment]
Il faut appliquer la migration avec la commande :

    php artisan migrate

Si vous avez exécuté la commande de publication plusieurs fois, il faut supprimer les fichiers *_add_ldap_colums_to_users_table.php qui ont été créés en trop.
