### ISSUE TITLE
Les routeurs logiques ne s’affichent pas

### ISSUE THREAD

**Issue by Mazwak** [dbarzin/mercator#34]
Bonjour

J’ai rentré 3 routeurs, mais la liste reste vide.

Il s’agit des routeurs des infrastructures **logiques**. En physique, ça fonctionne.

Ils sont bien dans la table :
```
mercator=# select * from routers;
 id |        name         | description | rules |     created_at      |     updated_at      | deleted_at
----+---------------------+-------------+-------+---------------------+---------------------+------------
  1 | ***********         |             |       | 2021-09-21 10:07:06 | 2021-09-21 10:07:06 |
  2 | Routeur_*********** |             |       | 2021-09-21 10:07:41 | 2021-09-21 10:07:41 |
  3 | Routeur_*********** |             |       | 2021-09-21 10:10:39 | 2021-09-21 10:10:39 |
(3 rows)
```

La BDD est sur un serveur distant en Ubuntu 20.04 et j’utilise postgresql.

Les exports ne donnent rien non plus.

J’ai déjà saisi pas mal d’objets, et c’est le seul (pour l’instant) qui a ce problème.

**Comment by dbarzin** [comment]
Ce point est corrigé. Il manque les adresses IP du routeur pour pouvoir le visualiser dans la vue de l'infrastructure logique.

**Comment by dbarzin** [comment]
Les routeurs logique ont maintenant une adresse IP
