### ISSUE TITLE
Erreur SQL à la première ouverture

### ISSUE THREAD

**Issue by hcornuau** [dbarzin/mercator#35]
Bonjour,
Je viens de réaliser une installation.
Lorsque je m'identifie, j'obtiens l'erreur ci-dessous :
--------
/var/www/mercator/
Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'security_need_c' in 'where clause' (SQL: select count(*) as aggregate from `networks` where `description` is not null and `protocol_type` is not null and `responsible` is not null and `responsible_sec` is not null and `security_need_c` is not null and `security_need_i` is not null and `security_need_a` is not null and `security_need_t` is not null and `networks`.`deleted_at` is null)
--------
Les commandes de migration de sont pourtant bien exécutées et je n'ai eu aucune erreur lors de l'installation.
Il semble qu'il manque des éléments dans la base de données injectée par défaut.

Merci pour votre aide.

**Comment by dbarzin** [comment]
php artisan migrate

**Comment by dbarzin** [comment]
Bug qui a été corrigé hier. Il manquait une migration. Pour corriger :

**Comment by dbarzin** [comment]
Bug qui a été corrigé hier soir. Il manquait une migration. Pour corriger :
git pull
php artisan migrate

**Comment by hcornuau** [comment]
Merci, cela fonctionne.
