### ISSUE TITLE
Question : Lien Base de données et Serveur

### ISSUE THREAD

**Issue by ncastel-arvalis** [dbarzin/mercator#38]
Bonjour, 

Je suis le projet depuis quelques temps sans avoir pratiqué. Je me suis lancé aujourd'hui dans l'utilisation concrète dans un docker sur mon poste en local. 

Je souhaitais reproduire un schéma dans lequel il y a une dépendance entre une base et un serveur (La base de données est hébergée sur un serveur différent que celui de l'application).  Est-il possible de le faire dans cette version ? Si oui, comment le faire? si non est-ce prévu dans la roadmap?

Merci pour ce partage!

Nicolas

**Comment by dbarzin** [comment]
Bonjour Nicolas,
Une base de données est liée à une ou plusieurs applications.
L'application peut utiliser plusieurs serveurs logiques, dont un de ces serveurs est un serveur de base de données.
Tu peux consulter le guide de l'ANSSI sur la cartographie qui décrit le modèle qui a été implémenté.
Didier

**Comment by ncastel-arvalis** [comment]
Merci Didier pour cette réponse rapide.
Effectivement le guide de l'ANSSI sur la cartographie n'évoque pas cette dépendance.  Pour notre besoin, il va sembler manquer la vue  qui permet de lister l'ensemble des bases de données d'un serveur et de connaître rapidement sur quel serveur est hébergée une base de données.
Je poursuis la découverte de cet outil prometteur!
Nicolas

**Comment by dbarzin** [comment]
Une base de données est une application qui peut être installée sur plusieurs serveurs logiques.
Les flux permettent d'identifier quelles applications utilisent quelles bases de données.

**Comment by ncastel-arvalis** [comment]
si une base de données était  une application, cela répondrait à notre besoin, ce qui ne me semble pas être le cas  dans ce qui a été modélisé (Table Databases qui n'a aucun lien avec les serveurs logiques). Par contre, nous pouvons effectivement  créer des bases de données en tant qu'application.  je teste ça!
Merci!
