### ISSUE TITLE
Longueur de certains libellés

### ISSUE THREAD

**Issue by hcornuau** [dbarzin/mercator#39]
Je commence juste à utiliser votre application qui me semble de très bonne facture, Bravo !
Cependant premier souci : lorsque l'on enregistre une nouvelle entité, le libellé est limité à 32 caractères, ce qui est très court.
L'entité que j'ai cherché à enregistrer est "Communauté d'Agglomération du Bocage Bressuirais" ce qui comporte 48 caractères…
Peut-être serait-il judicieux de prévoir un libellé long et un acronyme ou libellé court ?
Cela répondrait aux différentes contraintes de présentation.

**Comment by dbarzin** [comment]
Merci pour la suggestion. La limite à 32 caractère a été introduite pour répondre aux contraintes de dessin des différents vues.
L'utilisation de libellé court et long est effectivement une bonne idée mais cela ajoute également du travail lors de la création des différents éléments de la cartographie. C'est une amélioration à retenir pour une prochaine version de l'application.

**Comment by Not-Skg** [comment]
Bonjour,

Je me demandais pourquoi les longueurs des champs "noms" des différents endpoints sont différentes. La seule pour laquelle je comprends que la longueur soit plus grande est celle pour "fluxes". Une augmentation/uniformisation de ces longueurs est-elle prévue ?

**Comment by dbarzin** [comment]
Au début du projet, la longueur des champs a été limitée à 32 caractères afin de garantir un affichage correct dans les différents graphes et schémas d’architecture. Cependant, de nombreux utilisateurs ont exprimé le besoin de champs texte plus longs. En réponse à ces demandes, les longueurs ont été progressivement étendues à 64 ou 128 caractères selon les besoins.

**Comment by Not-Skg** [comment]
D'accord,  je comprends mieux, merci pour les explications.
Pensez-vous qu'il serait possible d'étendre la longueur des noms des 'macro-processuses' et des 'tasks' de 32 à 64 caractères ?

**Comment by dbarzin** [comment]
OK, ce sera fait !

**Comment by Not-Skg** [comment]
Merci !
