### ISSUE TITLE
Problème Installation 404 not found

### ISSUE THREAD

**Issue by webchl** [dbarzin/mercator#40]
Bonjour,
malgré avoir suivi la procedure d'installation; impossible de lancer http://IP_MERCATOR:8000 --> 404 not found
 http://IP_MERCATOR sans le port renvoi a la page par defaut d'apache
 http://IP_MERCATOR/mercator ou  http://IP_MERCATOR:8000/mercator  -> 404 not found
merci

**Comment by dbarzin** [comment]
Cela semble être un problème de configuration Apache. 
Qu'est ce qui se passe lors du lancement de l'application avec la commande : 
php artisan serve 
dans le répertoire de Mercator ?

**Comment by webchl** [comment]
tout semble correct:
/var/www/mercator$ php artisan serve
Starting Laravel development server: http://127.0.0.1:8000
[Tue Oct  5 06:47:15 2021] PHP 7.4.3 Development Server (http://127.0.0.1:8000) started

**Comment by dbarzin** [comment]
L'application doit réponse à l'URL http://127.0.0.1:8000
Concernant Apache, il faut vérifier la configuration du virtual host et consulter les logs.

**Comment by webchl** [comment]
comment acceder a l'url puis un autre poste? comme toute page web doit fonctionner d'ailleurs.
ou se trouve la configuration a appliquer ? quelle est la methode? merci

**Comment by dbarzin** [comment]
J'ai trouvé une documentation ici :
https://www.rosehosting.com/blog/install-laravel-on-ubuntu-20-04/
Fin du setp 4 pour les droits et step 5 pour la configuration Apache.

**Comment by webchl** [comment]
alors pour info et correction sur tuto d'install. il faut
1 - creer un fichier mercator.conf ici --> nano /etc/apache2/sites-available/laravel.conf avec les paramtres suivants:
<VirtualHost *:8000>
ServerName nom_serveur.domain.fr
ServerAdmin admin@domain.fr
DocumentRoot /var/www/mercator/public
<Directory /var/www/mercator>
AllowOverride All
</Directory>
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

2 - puis : nano /etc/apache2
<Directory />
        Options FollowSymLinks
        AllowOverride All
        Require all denied
</Directory>

<Directory /usr/share>
        AllowOverride All
        Require all granted
</Directory>

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
3 - Puis nano /etc/apache2/ports.conf

Listen 8000

<IfModule ssl_module>
        Listen 443
</IfModule>

<IfModule mod_gnutls.c>
        Listen 443
</IfModule>

4 - refaire un sudo systemctl restart apache2

pour moi cela a fonctionné merci

**Comment by dbarzin** [comment]
La documentation d’installation a été mise à jour.
