### ISSUE TITLE
Première installation : erreur lors de l'exécution de php artisan migrate --seed

### ISSUE THREAD

**Issue by leManu** [dbarzin/mercator#400]
Hello,

Je tente un premier déploiement de Mercator, mais pendant l'initialisation de la base de données je tombe sur l'erreur suivante lors de l'exécution de la commande `php artisan migrate --seed` :

```
PHP Fatal error:  Cannot declare class AddLdapColumnsToUsersTable, because the name is already in use in /home/mercator/mercator/database/migrations/2023_06_05_112532_add_ldap_columns_to_users_table.php on line 8

In 2023_06_05_112532_add_ldap_columns_to_users_table.php line 8:
                                                                                       
  Cannot declare class AddLdapColumnsToUsersTable, because the name is already in use  
                                                                                       

```

Y a t'il quelque chose que j'ai oublié ou mal fait ?

Voici les spécifications de la plateforme de déploiement :

- OS : FreeBSD 13.2
- Version de PHP : 8.2
- Base de données : MariaDB 10.5

**Comment by dbarzin** [comment]
Tu as très probablement publier les librairies deux fois avec la commande

    composer publish --all

Tu peux supprimer le fichier 2023_06_05_112532_add_ldap_columns_to_users_table.php qui se trouve dans le répertoire database/migrations  puis relancer la commande

   php artisan migrate --seed

**Comment by leManu** [comment]
Merci @dbarzin , c'était bien ça !

Et il n'y avait pas qu'un seul fichier à supprimer d'ailleurs :wink:
