### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by webchl** [dbarzin/mercator#41]
Est il possible d'importer en masse des equipements? via csv, excel txt... ou mieux interface avec glpi? merci

**Comment by dbarzin** [comment]
Pas via l'application pour l'instant mais avec la commande load data :
https://dev.mysql.com/doc/refman/8.0/en/load-data.html
ou avec MySQL Workbench :
https://dev.mysql.com/doc/workbench/en/wb-admin-export-import-table.html

**Comment by moiiom59** [comment]
Bonjour,
Il est assez facile de se connecter en odbc sur la base mysql et de faire le lien avec le sgbd de votre solution d'inventaire. Chez nous c'est IVANTI sous sqlserver. J'ai une base accès qui  me permet d'aliment en masse mercator à partir de mon inventaire ou des scans reseau "Avanced IP SCANNER" en csv.
Je peux ainsi assez facilement générer des requetes de mise à jour sur l'ensemble des données.

**Comment by dbarzin** [comment]
Merci pour la réponse !

**Comment by webchl** [comment]
> Bonjour, Il est assez facile de se connecter en odbc sur la base mysql et de faire le lien avec le sgbd de votre solution d'inventaire. Chez nous c'est IVANTI sous sqlserver. J'ai une base accès qui me permet d'aliment en masse mercator à partir de mon inventaire ou des scans reseau "Avanced IP SCANNER" en csv. Je peux ainsi assez facilement générer des requetes de mise à jour sur l'ensemble des données.

Bonjour,
comment faites vous pour vous connecter en odbc sur le mysql de mercator?
j'ai pas réussi. quel connecteur odbc utilisez vous et quels en sont les parametres?
merci d'avance

**Comment by dbarzin** [comment]
C'est documenté sur le site de MySQL : https://dev.mysql.com/doc/connector-odbc/en/connector-odbc-configuration-dsn-windows-5-2.html Vérifie que les flux ne sont pas bloqués par le firewall.

**Comment by mqu** [comment]
NocoDB est une alternative sous forme de GUI, assez proche de MS-Access et qui permettrait de s'interfacer avec la base SQL : https://www.nocodb.com/

**Comment by webchl** [comment]
Bonjour,
Merci je vais regarder

De : Marc Quinton ***@***.***>
Envoyé : vendredi 7 janvier 2022 09:47
À : dbarzin/mercator ***@***.***>
Cc : webchl ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/mercator] Import (#41)


NocoDB est une alternative sous forme de GUI, assez proche de MS-Access et qui permettrait de s'interfacer avec la base SQL : https://www.nocodb.com/<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fwww.nocodb.com&umid=250c9c17-6edc-4093-8607-354e53779cc4&auth=1a3cb316522a2150df7bc4e6bd0090c1f2656ec1-59e91d15fb4078ced39b8280f0240ef8619b6c5e>

-
Reply to this email directly, view it on GitHub<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fdbarzin%2fmercator%2fissues%2f41%23issuecomment%2d1007234257&umid=250c9c17-6edc-4093-8607-354e53779cc4&auth=1a3cb316522a2150df7bc4e6bd0090c1f2656ec1-6039d72a7bb7a9e06b07d97cdef241ad6d31048c>, or unsubscribe<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe%2dauth%2fASKA2SJYET3APGCZC7IHO5LUU2R35ANCNFSM5FL24TJQ&umid=250c9c17-6edc-4093-8607-354e53779cc4&auth=1a3cb316522a2150df7bc4e6bd0090c1f2656ec1-b7f38018b877d7c41517bc29110d74e74edc53c6>.
Triage notifications on the go with GitHub Mobile for iOS<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fapps.apple.com%2fapp%2fapple%2dstore%2fid1477376905%3fct%3dnotification%2demail%26mt%3d8%26pt%3d524675&umid=250c9c17-6edc-4093-8607-354e53779cc4&auth=1a3cb316522a2150df7bc4e6bd0090c1f2656ec1-4b9ba3d6f71909889623f69ffdfa8900a9ccbb42> or Android<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fplay.google.com%2fstore%2fapps%2fdetails%3fid%3dcom.github.android%26referrer%3dutm%5fcampaign%253Dnotification%2demail%2526utm%5fmedium%253Demail%2526utm%5fsource%253Dgithub&umid=250c9c17-6edc-4093-8607-354e53779cc4&auth=1a3cb316522a2150df7bc4e6bd0090c1f2656ec1-bb867407ab43d8a43458640cc38455cd88b1da7a>.

**Comment by dbarzin** [comment]
Il existe maintenant une REST API pour importer en masse des équipements.
https://dbarzin.github.io/mercator/api/

**Comment by webchl** [comment]
Excellent merci

Je n’ai cependant pas compris comment faire pour l’installer ? s’en servir…
Doit on mettre a jour merctor ? si oui quel est la procedure
Dsl je ne trouva pas sur github….
De : Didier Barzin ***@***.***>
Envoyé : vendredi 25 février 2022 09:13
À : dbarzin/mercator ***@***.***>
Cc : webchl ***@***.***>; Author ***@***.***>
Objet : Re: [dbarzin/mercator] Import (#41)

ATTENTION: Ce courrier provient d’un expéditeur extérieur à l’établissement, Ne cliquez sur aucun lien suspect et n'ouvrez aucune pièce jointe d'un expéditeur ou d’un contenu qui vous parait inhabituel. Ne communiquez pas vos identifiants sur des sites internet ou à la demande d’un interlocuteur. En cas de doute, contactez le Service Informatique
'

Il existe maintenant une REST API pour importer en masse des équipements.
https://dbarzin.github.io/mercator/api/<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fdbarzin.github.io%2fmercator%2fapi%2f&umid=0c4211a3-e3c1-45ca-bd43-90c94554d9bf&auth=1a3cb316522a2150df7bc4e6bd0090c1f2656ec1-281779efd24aadab1732da5b1f94ae916fe9ff01>

—
Reply to this email directly, view it on GitHub<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fdbarzin%2fmercator%2fissues%2f41%23issuecomment%2d1050629463&umid=0c4211a3-e3c1-45ca-bd43-90c94554d9bf&auth=1a3cb316522a2150df7bc4e6bd0090c1f2656ec1-bca3fd8a3d58facb1977cc1d84d8f1b5bc44d5bd>, or unsubscribe<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fnotifications%2funsubscribe%2dauth%2fASKA2SKUCBPVCK7D6OYZ7I3U4422DANCNFSM5FL24TJQ&umid=0c4211a3-e3c1-45ca-bd43-90c94554d9bf&auth=1a3cb316522a2150df7bc4e6bd0090c1f2656ec1-b3ce265ed6039ef2bca05bba3e2d7f0f424a8f43>.
Triage notifications on the go with GitHub Mobile for iOS<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fapps.apple.com%2fapp%2fapple%2dstore%2fid1477376905%3fct%3dnotification%2demail%26mt%3d8%26pt%3d524675&umid=0c4211a3-e3c1-45ca-bd43-90c94554d9bf&auth=1a3cb316522a2150df7bc4e6bd0090c1f2656ec1-33dce8af779df871174f1dc4549d135d26a3d62d> or Android<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fplay.google.com%2fstore%2fapps%2fdetails%3fid%3dcom.github.android%26referrer%3dutm%5fcampaign%253Dnotification%2demail%2526utm%5fmedium%253Demail%2526utm%5fsource%253Dgithub&umid=0c4211a3-e3c1-45ca-bd43-90c94554d9bf&auth=1a3cb316522a2150df7bc4e6bd0090c1f2656ec1-033cad8d1141592a814caf85e036eefa2cb23757>.

**Comment by dbarzin** [comment]
Il faut mettre à jour comme décrit dans la procédure d'installation et configurer "Passport".
Voir : https://github.com/dbarzin/mercator/blob/master/INSTALL.fr.md

**Comment by mqu** [comment]
> 

il y a donc une incidence sur l'environnement docker. Merci pour l'évolution.

**Comment by webchl** [comment]
Bonjour,
comment peut on alors importer en masse via l'API apres avoir installé et configuré "Passport"?
si par exemple je saisie http://IP_MERCATORR/api/workstations cela me renvoie vers la page d'accueil
je n'ai pas compris le principe
merci

**Comment by mqu** [comment]
manifestement, quand je lis la doc en lien avec l'[API](https://dbarzin.github.io/mercator/api/), on peut constater qu'il est nécessaire de s'authentifier avant de faire un GET.

**Comment by dbarzin** [comment]
Voici un exemple d'utilisation de l'API en Python

```
#!/usr/bin/python3

import requests

vheaders = {}
vheaders['accept'] = 'application/json'
vheaders['content-type'] = 'application/x-www-form-urlencoded'
vheaders['cache-control'] = 'no-cache'

print("Login")
response = requests.post("http://127.0.0.1:8000/api/login", 
    headers=vheaders, 
    data= {'email':'admin@admin.com', 'password':'password'} )
print(response.status_code)

vheaders['Authorization'] = "Bearer " + response.json()['access_token']

print("Get entities")
response = requests.get("http://127.0.0.1:8000/api/entities", headers=vheaders)
print(response.json())
print(response.status_code)

```

**Comment by mqu** [comment]
et la même chose en bash:
```
# valid login and password
data='{"email":"admin@admin.com","password":"password"}'

# get a token after correct login
token=$(curl -s -d ${data} -H "Content-Type: application/json" http://localhost:8000/api/login | jq -r .access_token)

# query users and decode JSON data with JQ.
curl -s -H "Content-Type: application/json" -H "Authorization: Bearer ${token}" "http://127.0.0.1:8000/api/users" | jq .
```
