### ISSUE TITLE
ubuntu 23.04 : require composer-runtime-api ^2.2 -> found composer-runtime-api[2.0.0] but it does not match the constraint.

### ISSUE THREAD

**Issue by p92** [dbarzin/mercator#419]
Hello

on ubuntu 23.04  we encounter the following error at installation :

$ composer update 

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/framework[v10.0.0, ..., v10.14.1] require composer-runtime-api ^2.2 -> found composer-runtime-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires laravel/framework ^10.0 -> satisfiable by laravel/framework[v10.0.0, ..., v10.14.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
`
on my system :

$ dpkg -l composer
Souhait=inconnU/Installé/suppRimé/Purgé/H=à garder
| État=Non/Installé/fichier-Config/dépaqUeté/échec-conFig/H=semi-installé/W=attend-traitement-dé>
|/ Err?=(aucune)/besoin Réinstallation (État,Err: majuscule=mauvais)
||/ Nom            Version      Architecture Description
+++-==============-============-============-=================================
ii  composer       2.5.4-1      all          dependency manager for PHP

**Comment by dbarzin** [comment]
Could you try :

    composer -W update

**Comment by p92** [comment]
Hello, yes I already did this with same error. and yes I also did it on a fresh mercator pull from git.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/framework[v10.0.0, ..., v10.15.0] require composer-runtime-api ^2.2 -> found composer-runtime-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires laravel/framework ^10.0 -> satisfiable by laravel/framework[v10.0.0, ..., v10.15.0].

```

it is not an urgent problem, I just wanted to know if I am the only one to get this error on latest ubuntu.

**Comment by dbarzin** [comment]
The continuous integration process runs with ubuntu-latest. The last build was a success : 
https://github.com/dbarzin/mercator/actions/runs/5472306942/jobs/9964347643

I have Ubuntu 22.04.  Could you retry in a separated folder ?
In the meantime, I will put in place a test environment with Ubuntu 23.04.

**Comment by dbarzin** [comment]
"require composer-runtime-api ^2.2" -> you have to update composer :

    composer self-update

**Comment by p92** [comment]
great shot. Now it works ! Thanks.
maybe this could be added in the INSTALL* files ?

**Comment by p92** [comment]
a little error in the INSTALL:

```
## Importer la base de données des CPE

Décompresse la base de données

    gzip -d mercator_data.sql.gz

Importer la base de données

    sudo mysql mercator < mercator_cpe.sql
```

should be :

`## Importer la base de données des CPE

Décompresse la base de données

    gzip -d mercator_cpe.sql.gz <<<<<<<<<<<<<<<<<<<<<

Importer la base de données

    sudo mysql mercator < mercator_cpe.sql`

**Comment by dbarzin** [comment]
Documentation has been updated !
Thanks,
Didier
