### ISSUE TITLE
Missing required parameter for [Route: admin.entities.show] [URI: admin/entities/{entity}] [Missing parameter: entity].

### ISSUE THREAD

**Issue by willijm** [dbarzin/mercator#423]
Bonjour,

suite a mise a jour, j'ai cette erreur si je veux afficher le détail d'une application

resources /views /admin / applications / show.blade.php: 92 require

 <a href="{{ route('admin.entities.show', $application->entity_resp_id) }}">

Merci de votre aide.

**Comment by dbarzin** [comment]
C'est corrigé.
Merci,
Didier

**Comment by willijm** [comment]
merci c'est bon.
Mais encore une erreur dans:
 resources / views / admin / forestAds / show.blade.php : 58

    <a href="{{ route('admin.zone-admins.show', $forestAd->zone_admin->id) }}">

Merci encore pour votre travail.

**Comment by dbarzin** [comment]
Corrigé !
Merci,
Didier

**Comment by willijm** [comment]
c'est super ;-)
