### ISSUE TITLE
Exploration : fixer les éléments

### ISSUE THREAD

**Issue by Nebrium** [dbarzin/mercator#436]
Bonjour,

Je voulais pouvoir agencer un peu comme je veux le schéma dans la partie "Exploration". Si je laisse appuyer la touche MAJ et que je déplace un élément, ça fonctionne je peux l'étirer et le placer comme je veux. Par contre après, il est fixe et je ne peux plus le déplacer, est ce un bug ?

Cordialement.

**Comment by Nebrium** [comment]
Je vais regarder merci.
Autre question liée à Exploration.
Si j'ai une interface unidirectionnelle qui va du logiciel1 -> logiciel2 pour l'identité par exemple mais que j'ai une interface logiciel2 -> logiciel1 pour la gestion des absences, je n'ai qu'une interface qui apparait. Est ce un comportement normal ?
Merci 😉

**Comment by Nebrium** [comment]
J'ai trouvé cette option pour arrêter que les extrémités bougent une fois que l'on a mis en forme le schéma pour finaliser le composition : 
"nodes": {
    "physics": false,
  },

On pourrait avoir un menu genre : Option pour cocher et décocher des options comme sur cette page mais en plus synthétique : 
https://visjs.github.io/vis-network/examples/network/other/configuration.html

**Comment by Guerisan** [comment]
Je peux essayer de proposer un PR prochainement pour implémenter la possibilité de choisir quelques unes de ces options :-)

J'ai déjà une fonctionnalité de déploiement récursif sur le modèle de ce qui était [discuté ici](https://github.com/dbarzin/mercator/discussions/421), mais avec quelques bugs restants (les edges de type flux ne s'affichent pas encore correctement)

**Comment by dbarzin** [comment]
J'attends ton PR avec impatience !

**Comment by dbarzin** [comment]
Merci pour le PR ! 

Il faudrait pour voir explorer les lien physique ou logiques des objets de la cartographie. Pour le moment on ne fait pas la différence et je pense que cela a un véritable intérêt pour identifier les points unique de faille.

**Comment by Guerisan** [comment]
Comme une option de filtre relative aux edges ? (+ une distinction visuelle ?)

**Comment by Nebrium** [comment]
Super les nouveaux éléments ! J'ai trouvé 2 petits bugs.
- On ne peut plus faire de clic droit pour cacher un nœud comme avant.
- Quand on désactive la physique, les nœuds qui sont multi-liens (exemple une application avec 3 flux) se superposent et on ne peut pas les bouger.

**Comment by dbarzin** [comment]
> Comme une option de filtre relative aux edges ? (+ une distinction visuelle ?)

Oui, il existe déjà une légère distinction visuelle, les liens physiques sont affichés en gris sombre et plus large.
Il faudrait sans doute utiliser une autre couleur comme bleu afin de mieux les distinguer des autres liens.

**Comment by dbarzin** [comment]
> Super les nouveaux éléments ! J'ai trouvé 2 petits bugs.
> 
>     * On ne peut plus faire de clic droit pour cacher un nœud comme avant.
> 
>     * Quand on désactive la physique, les nœuds qui sont multi-liens (exemple une application avec 3 flux) se superposent et on ne peut pas les bouger.

1. Je n'arrive pas à reproduire cela ici.
2. Cela nécessite que la physique soit activée, peut-être faut-il réactiver la physique lors de l'ajout de nœuds ?

**Comment by Nebrium** [comment]
Exemple : Physique activé :
![2023-08-14_11h03_54](https://github.com/dbarzin/mercator/assets/127872260/e09e51ef-330a-4c60-8534-fafbbedb54a1)
Physique désactivé :
![2023-08-14_11h04_50](https://github.com/dbarzin/mercator/assets/127872260/572023de-5dd1-4085-aafb-245949edd813)

**Comment by Guerisan** [comment]
> Exemple : Physique activé : ![2023-08-14_11h03_54](https://user-images.githubusercontent.com/127872260/260405934-e09e51ef-330a-4c60-8534-fafbbedb54a1.png) Physique désactivé : ![2023-08-14_11h04_50](https://user-images.githubusercontent.com/127872260/260406042-572023de-5dd1-4085-aafb-245949edd813.png)

La désactivation de la physique désactive également le "smooth" des liens, qui est l'option qui leur donne l'aspect courbé.
C'est pour éviter qu'ils ne se tordent dans tous les sens au repositionnement quand le reste du schéma est statique.
Il doit y avoir d'autres paramètres à tweaker pour éviter la superposition, ou plus simplement rajouter une option pour réactiver le smooth.
Si les paramètres de customisation se multiplient, il faudra qu'on pense à changer le layout (comme un menu déroulant), et éventuellement un moyen de les sauvegarder :)

**Comment by dbarzin** [comment]
ou en réactivant la physique lors de l'ajout d'un nœud.

**Comment by dbarzin** [comment]
:tada: Le filter sur les nœuds dans l'explorer fonctionne !
