### ISSUE TITLE
Bug docker compose

### ISSUE THREAD

**Issue by protocolpaladin** [dbarzin/mercator#438]
The db image not use by app, because app use integrate db sqlite and the data is loose if restart docker-compose.

**Comment by protocolpaladin** [comment]
The . .env in entrypoint is not real apply if I connect manually to docker container with bash and check the variable the variable correspond to docker file

**Comment by protocolpaladin** [comment]
Temporary correct with modify function docker to map sql lite container app mercator to host to save in live. But the mysql container is not map with mercator app.

Correct in pull requests
#447

**Comment by protocolpaladin** [comment]
sorry this is not corrected but a workaround has been put in place to make the content functional

**Comment by dbarzin** [comment]
Thanks !
