### ISSUE TITLE
The images are not visible in report

### ISSUE THREAD

**Issue by protocolpaladin** [dbarzin/mercator#462]
The images are not visible in the views generated in the generation of .docx reports. Only the arrows are. (In docker version)

**Comment by dbarzin** [comment]
Is the folder "/var/www/mercator/public/images" accessible by php ?

**Comment by protocolpaladin** [comment]
The images is visible un web gui but not in report word and this folder is mercartor:www rwx rw

**Comment by dbarzin** [comment]
Corrigé !

**Comment by protocolpaladin** [comment]
Thanks what was the problem and the part of the code that fixed the problem please.

**Comment by dbarzin** [comment]
It needed three pateches to fix the problem : 

Problem with Apache2 and graphviz
https://github.com/dbarzin/mercator/commit/8b38573d25a60eba5793f960cc74464e4274f31f

A problem with the fonts that where not installed
https://github.com/dbarzin/mercator/commit/27ba7531459156ffc70c29ffcf6976648d8eba1b

Then specify the free font to use
https://github.com/dbarzin/mercator/commit/a647f4fb6fa68cdb1626e45228cbc0dab0e31116
