### ISSUE TITLE
Nombre de caratères

### ISSUE THREAD

**Issue by Nebrium** [dbarzin/mercator#463]
Je ne suis pas très doué avec git... Ayant peur de faire une boulette je vais poser la question ici 😅 Je ne sais pas comment soumettre une modification... 

Pourquoi limiter les caractères de la colonne "name" à 32 caractères dans le script et la mettre à 255 sur la base ? Ne pourrait-on pas mettre un peu plus de caractère ? Exemple je voulais créer un bloc applicatif ou encore un macro-processus type "Partager des informations avec le patient", c'est top long 😣

On ne pourrait pas agrandir un peu la taille du champ s'il te plait ? 😇

**Comment by dbarzin** [comment]
La taille de 255 caractères dans la base de données provient du framework Laraval pas de la conception de l'application.
Cette limitation a été introduite pour pouvoir afficher le nom des objets dans les schémas de la cartographie.
Le nom peut être résumé aux initiales et le nom complet de l'objet peut être mis dans la description.
Tout doit pouvoir se résumer en 32 caractères.

**Comment by Nebrium** [comment]
Ok c'est noté ;-)
