### ISSUE TITLE
Fix cursor position in drop-down

### ISSUE THREAD

**Issue by Guerisan** [dbarzin/mercator#489]
Hello Didier !
J'ai des cartographes qui ont fait remonter que certains champs de sélection (les select2 amenés par jQuery) ne sont pas pratiques à utiliser car le curseur ne se positionne pas automatiquement dans le champs de recherche quand on les déroule.

La cause revient à un bug dans cette version de jQuery (mercator utilise aujourd'hui la 3.6.4), une issue a d'ailleurs été ouverte :
https://github.com/select2/select2/issues/5993

J'ai testé en local, et mettre à jour jquery.min.js vers la 3.7.1 corrige effectivement le problème !

Si la maj n'est pas possible, il existe un fix que l'on peut rajouter au fichier public/main.js :
```js
$(document).on('select2:open', e => {
    const select2 = $(e.target).data('select2');
    if (!select2.options.get('multiple')) {
        select2.dropdown.$search.get(0).focus();
    }
  });
```
Qui fonctionne correctement sur les pages ayant plusieurs champs de sélection.

Toutefois, je recommanderais la mise à niveau de jquery, plus simple :-)

**Comment by dbarzin** [comment]
jquery a été mis à jour à la version 3.7.1 :tada:
