### ISSUE TITLE
Problème "contenu mixte actif" & "requête multiorigines"

### ISSUE THREAD

**Issue by etienne-64** [dbarzin/mercator#502]
Bonjour,

Après migration, problème de blocages avec Firefox (notamment login) dû à des problèmes de  "contenu mixte actif" & "requête multiorigines"

![image](https://github.com/dbarzin/mercator/assets/10651729/1c02bdbf-f358-4649-8a77-a15aab9d8108)

Je n'ai fait aucun changement de configuration côté Apache. L'application de fonctionne correctement qu'en http. 

Ai-je râté quelque chose au niveau de la config ?

Merci d'avance pour les pistes.

**Comment by dbarzin** [comment]
Je pense qu'il faut mettre en place une rewrite rule http vers https.

**Comment by etienne-64** [comment]
Je me suis peut-être mal exprimé. La bascule auto vers https est en place depuis le début, mais en https j'obtiens ce qui est contenu dans la capture et qui provoquent des dysfonctionnements (bloquage chargement styles et scripts).
Je suis donc pour le moment obligé de revenir en http pour utiliser Mercator.

**Comment by dbarzin** [comment]
J'avais bien compris. Voici une explication plus complète  : 
- https://cwiki.apache.org/confluence/display/httpd/RewriteHTTPToHTTPS
- https://httpd.apache.org/docs/2.4/rewrite/remapping.html

Il doit également être possible de le faire plus simplement via la variable APP_URL du fichier .env

**Comment by etienne-64** [comment]
Je pense avoir presque "tout essayé"  ... APP_URL sans résultat ... Je sèche. J'y reviendrai plus tard.
Merci pour les pistes.

**Comment by etienne-64** [comment]
J'ai refait une installation manuelle complète avec données de l'install sur vps. J'ai généré le certificat avec certbot ...
![image](https://github.com/dbarzin/mercator/assets/10651729/d4262c82-90dd-4c7c-b849-56d9c87b05f5)

**Comment by dbarzin** [comment]
Chez moi on a une rewrite rule.

**Comment by etienne-64** [comment]
A quelle niveau ? Config Apache ? .htaccess ?

Par défaut Let's Encrypt génère : 
```apache
RewriteEngine on
RewriteCond %{SERVER_NAME} =mercator.mon-site.ovh
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
````
Je n'ai jamais été confronté à ce problème. Si tu peux me partager les config. , ça devrait m'aider .

**Comment by dbarzin** [comment]
On a un firewall applicatif qui gère cela.
Le module rewrite Apache est-il chargé ?

**Comment by etienne-64** [comment]
Le serveur qui héberge mercator héberge d'autres apps servies en https (par ex. Zabbix)

```sh
Loaded Modules:
...
 proxy_fcgi_module (shared)
...
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)
````

**Comment by dbarzin** [comment]
Essaye de mettre dans le fichier .env :

    APP_ENV=production

**Comment by etienne-64** [comment]
Après changement, purge et redémarrage divers, pas de changement.

**Comment by dbarzin** [comment]
Une configuration a été ajoutée pour forcer http -> https lorsque APP_ENV=production.
Testé, cela fonctionne.

**Comment by etienne-64** [comment]
Merci pour le suivi.
Ça fonctionne mais je dois désactiver la protection "mixed content" de Firefox.
![image](https://github.com/dbarzin/mercator/assets/10651729/f6b28b83-0b2d-4b74-907b-0e5e019c58ff)

**Comment by dbarzin** [comment]
Ce problème n'est pas présent lors de mes tests. 
As-tu la dernière version du code ? Il a été modifié aujourd'hui.
As-tu positionné la variable APP_ENV=production dans le fichier .env ?

**Comment by etienne-64** [comment]
Oui. J'ai procédé à des installations de "zero" avec la dernière version (avec mes données comme avec les données de tests fournies sur le repository), sur deux serveurs distincts.

Je vais faire une réinstallation complète sur une VM (OS + apps) pour éliminer tout problème de configuration d'Apache ou autres.
Pour infos, je suis sur Debian 11 + apache 2.4 + php8.1-fpm .

**Comment by dbarzin** [comment]
Commence par faire un git pull sur mercator. Le reste ne devrait pas avoir d'impact.

**Comment by etienne-64** [comment]
Effectivement, j'ai vu passé quelques nouvelles mises à jour ... retour à la normale.
Merci.
