### ISSUE TITLE
[emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)

### ISSUE THREAD

**Issue by arnaudluti** [dbarzin/mercator#504]
Bonjour,

Impossible de démarrer le conteneur avec la configuration par défaut
`docker run -it --rm --name mercator -p "127.0.0.1:8000":80 ghcr.io/dbarzin/mercator:latest`
Erreur : 
```
  2021_09_19_125048_relation-inportance ............................2023-09-17 16:11:26,634 INFO spawned: 'nginx' with p
id 21
 59ms DONE
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /e
tc/nginx/nginx.conf:3
  2021_09_21_161028_add_router_ip nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/http.d/default.conf:8
2023/09/17 16:11:26 [emerg] 21#21: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
.................................. 30ms DONE
2023-09-17 16:11:26,682 INFO exited: nginx (exit status 1; not expected)
  2021_09_22_114706_add_security_ciat 2023-09-17 16:11:26,696 INFO gave up: nginx entered FATAL state, too many start re
tries too quickly
```

**Comment by dbarzin** [comment]
Impossible de reproduire le problème.
Testé avec : 

    $ docker -v 
    Docker version 20.10.25, build 20.10.25-0ubuntu1~22.04.1

**Comment by luciolebrillante** [comment]
Même problème ici :

<code>
2023-09-21 08:35:48,189 INFO exited: migrate (exit status 0; not expected)
2023-09-21 08:35:49,190 INFO gave up: migrate entered FATAL state, too many start retries too quickly
2023-09-21 08:35:49,191 INFO spawned: 'nginx' with pid 19
2023-09-21 08:35:49,191 INFO success: php entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:3
nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/http.d/default.conf:8
2023/09/21 08:35:49 [emerg] 19#19: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
2023-09-21 08:35:49,195 INFO exited: nginx (exit status 1; not expected)
[21-Sep-2023 08:35:49] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[21-Sep-2023 08:35:49] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[21-Sep-2023 08:35:49] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[21-Sep-2023 08:35:49] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[21-Sep-2023 08:35:49] NOTICE: fpm is running, pid 5
[21-Sep-2023 08:35:49] NOTICE: ready to handle connections
2023-09-21 08:35:51,418 INFO spawned: 'nginx' with pid 25
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:3
nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/http.d/default.conf:8
2023/09/21 08:35:51 [emerg] 25#25: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
2023-09-21 08:35:51,422 INFO exited: nginx (exit status 1; not expected)
2023-09-21 08:35:54,426 INFO spawned: 'nginx' with pid 26
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:3
nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/http.d/default.conf:8
2023/09/21 08:35:54 [emerg] 26#26: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
2023-09-21 08:35:54,431 INFO exited: nginx (exit status 1; not expected)
2023-09-21 08:35:55,432 INFO gave up: nginx entered FATAL state, too many start retries too quickly
^C2023-09-21 08:36:54,496 WARN received SIGINT indicating exit request
2023-09-21 08:36:54,497 INFO waiting for php to die
[21-Sep-2023 08:36:54] NOTICE: Terminating ...
[21-Sep-2023 08:36:54] NOTICE: exiting, bye-bye!
2023-09-21 08:36:54,499 INFO stopped: php (exit status 0)
[luciolebrillante ~]$ docker -v 
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
podman version 4.6.2
</code>

**Comment by dbarzin** [comment]
@pdurandfr, peux-tu regarder ce qui se passe ?

**Comment by dbarzin** [comment]
> Bonjour,
> 
> Impossible de démarrer le conteneur avec la configuration par défaut `docker run -it --rm --name mercator -p "127.0.0.1:8000":80 ghcr.io/dbarzin/mercator:latest` Erreur :
> 
> ```
>   2021_09_19_125048_relation-inportance ............................2023-09-17 16:11:26,634 INFO spawned: 'nginx' with p
> id 21
>  59ms DONE
> nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /e
> tc/nginx/nginx.conf:3
>   2021_09_21_161028_add_router_ip nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/http.d/default.conf:8
> 2023/09/17 16:11:26 [emerg] 21#21: bind() to 0.0.0.0:80 failed (13: Permission denied)
> nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
> .................................. 30ms DONE
> 2023-09-17 16:11:26,682 INFO exited: nginx (exit status 1; not expected)
>   2021_09_22_114706_add_security_ciat 2023-09-17 16:11:26,696 INFO gave up: nginx entered FATAL state, too many start re
> tries too quickly
> ```
Le port 80 est déjà utilisé sur la machine locale ou vous n'avez pas le droit d'utiliser ce port.

**Comment by dbarzin** [comment]
Pas de réponse, impossible à reproduire.

**Comment by pdurandfr** [comment]
Bonjour Didier,

Je vois ton mail à l'instant. J'essaye de regarder ça ce WE.

Bonne journée,



Philippe Durand

Explorateur Scientifique et Directeur de Programmes IT

+33.(0)6.73.16.36.09

_________________________________________


Le jeu. 21 sept. 2023 à 10:53, Didier Barzin ***@***.***> a
écrit :

**Comment by pdurandfr** [comment]
Hello Didier,

En fait j'avais lu bien vite le mail vendredi, pas vu l'historique des
dates etc. ... en théorie je n'avais rien à faire de particulier :-).

Bon, j'ai quand même regardé deux choses:

   1. le plus important, c'est que la ligne suivant ne fonctionne plus :
   docker run -it --rm --name mercator -p "127.0.0.1:8000":80
   ghcr.io/dbarzin/mercator:latest
      - Pourquoi? car l'URL que retient mercator est https.
      - Pourquoi? => test de rajouter -e APP_URL=http://127.0.0.1:8000 pour
      "forcer" http ne fonctionne pas : cela reste en https.
      - Pourquoi? => test de rajouter -e APP_ENV=development fonctionne :
      on revient bien en http.
      - Pourquoi? depuis ta modif de forcer en https en prod (force http ->
      https in production by dbarzin · Pull Request #503 · dbarzin/mercator ·
      GitHub <https://github.com/dbarzin/mercator/pull/503>), je pense que
      que le schéma par défaut est "production" donc ... forcé en https.
      - Pistes pour traiter ce point :
         - ne rien changer et juste indiquer dans la doc de rajouter -e
         APP_ENV=development (ou sinon d'utiliser le docker-compose
qui présente en
         https)
            - ce qui donne "docker run -it --rm --name mercator -p "
            127.0.0.1:8000":80 -e APP_ENV=development
            ghcr.io/dbarzin/mercator:latest" pour l'exemple ci-dessus ;-)
         - ou, si on a un scheme http en prod, sortir avec un message
         d'erreur...
      2. il n'y a qu'un tag "latest" sur l'image docker.
      - cela ne facilite pas la comprehension des pbms
         - lorsque quelqu'un a un souci, difficile de savoir quelle version
         il a téléchargé
         - et, tant qu'il a la latest dans sa registry locale, il ne va pas
         chercher une nouvelle donc ne pourra pas upgrader.
      - il faudrait taguer l'image avec la même version que celle mercator
         - et "déplacer" le tag latest toujours sur la dernière poussée

Voilà, à ta dispo pour en parler à l'occasion :-)

Bonne journée,,



Philippe Durand

Explorateur Scientifique et Directeur de Programmes IT

+33.(0)6.73.16.36.09

_________________________________________

**Comment by pdurandfr** [comment]
Bonjour Didier,

Je viens d'updater le README.md pour ajouter le -e APP_ENV=development et
indiquer de pointer sur le docker-compose si on veut du https / un peu plus
robuste.

Bonne journée,



Philippe Durand

Explorateur Scientifique et Directeur de Programmes IT

+33.(0)6.73.16.36.09

_________________________________________

**Comment by dbarzin** [comment]
Bonjour Philippe,

1.
Merci pour ton intervention sur ce point, tu peux faire une PR.

2.
Tu as raison, il est préférable de fixer la version d'Ubuntu utilisée.
Tu peux également ajouter cela au PR ?

Merci,
Didier

Le lun. 30 oct. 2023 à 08:15, Philippe Durand ***@***.***> a
écrit :

> Bonjour Didier,
>
> Je viens d'updater le README.md pour ajouter le -e APP_ENV=development et
> indiquer de pointer sur le docker-compose si on veut du https / un peu
> plus
> robuste.
>
> Bonne journée,
>
>
>
> Philippe Durand
>
> Explorateur Scientifique et Directeur de Programmes IT
>
> +33.(0)6.73.16.36.09
>
> _________________________________________
>
>

**Comment by dbarzin** [comment]
Merci, la version README.fr.md a été mise à jour.
Cordialement,
Didier

Le lun. 30 oct. 2023 à 08:15, Philippe Durand ***@***.***> a
écrit :

> Bonjour Didier,
>
> Je viens d'updater le README.md pour ajouter le -e APP_ENV=development et
> indiquer de pointer sur le docker-compose si on veut du https / un peu
> plus
> robuste.
>
> Bonne journée,
>
>
>
> Philippe Durand
>
> Explorateur Scientifique et Directeur de Programmes IT
>
> +33.(0)6.73.16.36.09
>
> _________________________________________
>
>
