### ISSUE TITLE
Mauvais lien vers les processus, sur la page de descriptif d'une activité

### ISSUE THREAD

**Issue by knightdogg** [dbarzin/mercator#548]
Pré-requis : il faut disposer d'un processus, découpé en activités

Mode opératoire :
Consulter le détail d'une activité du processus (https://.../admin/activities/<ID_activite>)

Résultat attendu :
La page de détail s'affiche, avec des liens vers les processus et opérations associées.

Résultat obtenu :
La page s'affiche bien. Le liens vers les opérations qui composent l'activité est correct.
Le lien vers les processus que l'activité compose est incorrect : ils dirigent vers https://.../admin/operations/<ID_process>

**Comment by dbarzin** [comment]
Corrigé dans https://github.com/dbarzin/mercator/pull/549
