### ISSUE TITLE
Flux manquants dans la fonction Exploration

### ISSUE THREAD

**Issue by sowhatkob** [dbarzin/mercator#550]
Bonjour,

Dans le cas de 2 flux entre 2 applications (un entrant et l'autre sortant), si je choisis les 2 applications dans la fonction exploration, le graphe retourné n'affiche que l'un des 2 flux.
Le flux apparait par contre correctement (2 flux avec la bonne orientation) dans la vue Flux.

Concernant les flux dans le volet exploration, cela serait intéressant de pouvoir arriver sur le formulaire du flux à partir du lien comme pour les autres objets.

Merci beaucoup

**Comment by dbarzin** [comment]
Les deux points sont corrigés !
