### ISSUE TITLE
Erreur lors de la génération des rapports vues infrastructures

### ISSUE THREAD

**Issue by moiiom59** [dbarzin/mercator#57]
Bonjour,
En core bravo pour cet outil.
Je rencontre un problème a la génération des rapports sur les vues infrasctructure logique et physique.
"ErrorException
DOMDocument::loadXML(): Opening and ending tag mismatch: p line 1 and body in Entity, line: 1"

Auriez vous une idée du problème ? merci à vous

**Comment by dbarzin** [comment]
Bonjour,
Avez-vous la dernière version du code ?
Quel OS utilisez-vous avec quelle base de données ?
Merci,
Didier

**Comment by moiiom59** [comment]
Bonjour,
OUi j'ai fait la dernière MAJ (via GIT). J'utilise Ubuntu 20.04 et mysql 8.0.27

**Comment by dbarzin** [comment]
Tu peux envoyer une capture d'écran ?
Est-il possible d'avoir le stack complet lors de l'erreur ?
Merci,

**Comment by moiiom59** [comment]
Voici https://flareapp.io/share/VP69x9em#F56

**Comment by moiiom59** [comment]
En effet merci beaucoup.

**Comment by moiiom59** [comment]
J'ai le même problème sur l'infrastructure physique, mais je ne vois pas quelle table est concernée ?
Pouvez vous me trouver la table avec cette trace https://flareapp.io/share/o7AnrKB5#F56

**Comment by dbarzin** [comment]
C'est le champ description d'un périphérique.  La commande SQL: "select id, description from peripherals;"

**Comment by moiiom59** [comment]
Perfect !!!
Merci beaucoup
