### ISSUE TITLE
insertion d'image

### ISSUE THREAD

**Issue by webchl** [dbarzin/mercator#571]
Bonjour,
Lorsque j'utilise le bouton Insert Image dans les champs de description d'une application (je n'ai pas essayé sur les autres formulaires), rien ne se passe 
y a t-il un format ou une taille particulière a respecter?
sera t'elle ensuite affiché sur les rapports?
merci

**Comment by dbarzin** [comment]
C'est désactive. Cela pose des problèmes dans la génération des rapports et l'export de ces champs dans des tableurs.
