### ISSUE TITLE
Certificat CSS - HTTPS

### ISSUE THREAD

**Issue by victorgyt** [dbarzin/mercator#573]
Bonjour, 
Je vous écris aujourd'hui car nous essayons depuis peu de chiffrer notre mercator, 

Le certificat de société est bien passé, cependant nous avons remarqué que l'interface de connexion est "cassé". 

![image](https://github.com/dbarzin/mercator/assets/152492865/10833e9c-7633-4cb4-a7a4-6008e8b5506d)

Pouvez vous me dire comment mettre en place le chiffrement HTTPS afin que mercator soit chiffré et fonctionne correctement ? 

Merci de votre aide 

Cordialement 

V.G

**Comment by dbarzin** [comment]
essaye de mettre la clé 

    APP_DEBUG=false

dans le fichier .env

**Comment by victorgyt** [comment]
Merci pour votre retour rapide, 
Mon collègue m'a dit que c'est pareil. 
avez vous une autre solution ?

**Comment by victorgyt** [comment]
Mon collègue me dit que c'est pareil. 

![image](https://github.com/dbarzin/mercator/assets/152492865/39bec225-7285-4e98-ba24-778b2560ad73)


A savoir, nous utilisons Apache pour démarrer le service. 

Je vous met en pièce jointe la configuration d'apache. 

<VirtualHost *:443>

ServerName carto.XXXXXXXX

ServerAdmin 

DocumentRoot /var/www/mercator/public

SSLEngine on

SSLProtocol all -SSLv2 -SSLv3

SSLCipherSuite HIGH:3DES:!aNULL:!MD5:!SEED:!IDEA
 
SSLCertificateFile /etc/apache2/certs/certs/carto.XXXXX.crt

SSLCertificateKeyFile /etc/apache2/certs/private/private.key

SSLCertificateChainFile /etc/apache2/certs/certs/XXXXXCA.crt
 
<Directory /var/www/mercator/public>

AllowOverride All

</Directory>
 
ErrorLog ${APACHE_LOG_DIR}/mercator_error.log

CustomLog ${APACHE_LOG_DIR}/mercator_access.log combined
 
</VirtualHost>

**Comment by dbarzin** [comment]
Il faut mette cette clé dans le fichier .env

    APP_ENV=production

**Comment by victorgyt** [comment]
C'est corrigé, merci de votre aide !

**Comment by sowhatkob** [comment]
Merci. J'étais bloqué sur le même problème.

**Comment by dbarzin** [comment]
Cela a été ajouté dans la documentation d'installation.
