### ISSUE TITLE
Gestion d'un cluster HyperV

### ISSUE THREAD

**Issue by sowhatkob** [dbarzin/mercator#58]
Bonjour, 
Merci pour cette belle application.
Je bute sur la modélisation d'un cluster HyperV. 
Comment gérez-vous le lien entre une application, la machine virtuelle sur laquelle elle est installée, le cluster hyperV qui héberge la VM et les serveurs physiques qui composent le cluster ? J'ai essayé différentes modélisations mais sans succès ou alors il faudrait faire le lien entre chaque VM et le serveur physique qui l'héberge mais c'est une information extrêmement volatile. 
Il faudrait que un serveur logique (VM) puisse s'appuyer sur un autre serveur logique (Cluster).
Merci de votre aide

**Comment by dbarzin** [comment]
Dans la cas d'un cluster, comme il n'est pas possible de savoir sur quelle serveur physique du cluster tourne la machine virtuelle, vous pouvez dire qu'elle fonctionne toujours sur un des noeuds du cluster et donc associer toutes la machines physique du cluster à votre machine virtuelle.

**Comment by sowhatkob** [comment]
Bonjour,
Merci. 
J'ai préféré pour ne pas avoir à maintenir chaque VM à chaque ajout d'hôtes dans le cluster (16 actuellement), avoir le cluster HyperV à la fois en serveur physique et en serveur logique.  
Cordialement

**Comment by dbarzin** [comment]
Nous avons plus de 400 serveurs logiques déployés sur 8 serveurs physiques.

**Comment by dbarzin** [comment]
:tada: La gestion des clusters est disponible ! :tada:

**Comment by sowhatkob** [comment]
Merci beaucoup
