### ISSUE TITLE
Applications : Search CPE Common Plateforme Enumeration

### ISSUE THREAD

**Issue by lynch4fr** [dbarzin/mercator#581]
Bonjour,
Quand je souhaite qualifier une application avec le "CPE" : Editeur | Produit | Version. Je commence à saisir le nom dans  "Start typing to search" mais je n'ai aucun retour dans le champ ? Savez vous comment il faut s'en servir correctement ?
Merci beaucoup.

![cpeeditor](https://github.com/dbarzin/mercator/assets/27801633/ea504d98-6fb1-4f32-b9ff-02b759cc310a)

**Comment by dbarzin** [comment]
Avez-vous importé la base de données avec les CPE ?
https://github.com/dbarzin/mercator/blob/master/INSTALL.fr.md#importer-la-base-de-donn%C3%A9es-des-cpe

**Comment by lynch4fr** [comment]
Merci ça marche maintenant. J'avais oublié cette etape dans mon installation, desolé.
Encore merci pour ton aide
Bon week end
