### ISSUE TITLE
[Docker] Impossibilité d'utiliser l'extension PHP LDAP dans l'image docker par défaut

### ISSUE THREAD

**Issue by krptg0** [dbarzin/mercator#582]
Salut,

En phase de mise en production, je me suis penché sur le docker-compose existant dans ce repo.
Je remarque que même lorsque les variables LDAP_* sont peuplées, rien ne se passe côté applicatif (aucun log en stdout).

Lorsque je rentre dans le conteneur et exécute un `php artisan ldap:test` j'obtiens ceci : 

![image](https://github.com/dbarzin/mercator/assets/45569465/69ec7375-d69e-426e-97e0-6e1d1dceaaad)

Je note également qu'une fois dans le conteneur, lorsque j'exécute `php -m | grep ldap`, je n'ai pas de retour, quand bien il y a bien le package alpine php8-ldap d'installé dans le Dockerfile.

J'ai donc modifié le Dockerfile en utilisant https://github.com/mlocati/docker-php-extension-installer afin de "forcer" l'installation de l'extension ldap.

A présent, lorsque j'exécute `php artisan ldap:test`, j'ai une erreur de credentials, ce qui me laisse penser cette fois que l'extension ldap est bien chargée, et que j'ai encore du boulot de mon côté 🤡 .

J'aimerai proposer une PR en ce sens, mais je ne suis pas développeur PHP, et ai peur que ce problème concerne également d'autres extensions php installées via les packages alpine ?

J'attends vos retours :)

A+,

PS: Ceci n'a pas d'incidence sur l'utilisation de l'application, mais je déploie mercator dans kubernetes, si interessé je pourrai également faire une PR avec les manifests utiles à ce déploiement.

**Comment by dbarzin** [comment]
La version de Docker fournie n'était pas prévue pour fonctionner avec LDAP, cela n'avait jamais été testé. Il faut probablement uniquement ajouter les extensions PHP manquantes. Vous pouvez faire un PR pour améliorer cela.

**Comment by krptg0** [comment]
Salut,

Pour recouper avec #334 , je vais préparer une PR qui modifiera le Dockerfile pour y intégrer (et migrer 2 ext) l'extension ldap, et faire un vendor publish juste au moment du build de l'image Docker. J'y intégre également les 2 fichiers PHP qui sont montés manuellement dans le docker-compose, sauf si @dbarzin tu sais m'expliquer pourquoi ces 2 fichiers PHP sont différents entre Docker et non-Docker ?

Petite parenthèse: Pourquoi l'intégration LDAP est déjà "prête" dans le repo mais n'est pas mise à dispo dans le Docker directement via publish & migrate ? Etait-ce instable ?

Merci,

**Comment by dbarzin** [comment]
Les deux fichiers montés servent à conserver la base de données en dehors du Docker. Ces fichiers sont différents car la base de données utilisée est en Postgres SQL dans la version Docker au lien de mySQL dans la version non-Docker.

Il n'y a pas de raison particulière à ne pas intégrer LDAP dans la version Docker. La seule raison que je vois est de limiter la taille de la VM nécessaire si LDAP n'est pas utilisé.
