### ISSUE TITLE
Problème sur liste

### ISSUE THREAD

**Issue by moiiom59** [dbarzin/mercator#59]
Serveurs logiques : Liste des serveurs logiques par applications et responsables

Pourriez vous me dire sur quelles table l'extraction bloc ?
Le stack ici https://flareapp.io/share/17W68lYP

merci beaucoup

**Comment by dbarzin** [comment]
C'est un bug. Une application ne se trouve pas dans un bloc applicatif. Ce sera corrigé ce soir.

**Comment by moiiom59** [comment]
Il s'agira de lancer un GIT  pour corriger ?

**Comment by dbarzin** [comment]
oui  "git pull origin master"

**Comment by dbarzin** [comment]
Corrigé.

**Comment by moiiom59** [comment]
Parfait merci
