### ISSUE TITLE
procédure de recouvement compte administrateur

### ISSUE THREAD

**Issue by mqu** [dbarzin/mercator#6]
bonjour,

il serait souhaitable de disposer d'une procédure de recouvrement du (d'un) compte admin, de préférence en CLI plutôt que par mail. De nombreuses applications disposent d'une CLI pour la gestion des users et certaines opérations un peu rares ou spécifiques.

cordialement, Marc.

**Comment by dbarzin** [comment]
Voici la solution : 
- ne pas utiliser une adresse email valide pour l'administrateur (ex: admin@localhost)
- pour restaurer le mot de passe, la commande est ;
    mysql mercator -e "update users set password=$(php -r "echo password_hash('new_password', PASSWORD_BCRYPT, ['cost' => 10]);") where id=1;"
