### ISSUE TITLE
Connexion d'une base de données à un service applicatif ou un module

### ISSUE THREAD

**Issue by Schirrms** [dbarzin/mercator#60]
Bonjour,

Je découvre en ce moment Mercator, et le produit me plait beaucoup. Je 'joue' avec Mercator, tout en lisant le doc de l'ANSSI, c'est très intéressant.
L'idée étant de voir (bien entendu) s'il est possible de faire adhérer mon organisation à un modèle de données commun, et si possible celui-ci :)
Cependant, pour représenter notre SI, je suis un peu embêté par la seule possibilité d'attacher une base de données à une application.

Ceci provient peut-être de mon incompréhension du modèle.
Soit un portail WEB : j'associe mon portail WEB à 'bloc applicatif'
Dans ce portail se trouve une solution de commandes en ligne : c'est pour moi une application
En pratique, cette application de commandes unique est elle-même un portail, et va consolider dynamiquement des données provenant de différents services.
On aura donc un (ou plusieurs) service assurant l'interface graphique ( = service applicatifs) et autant de services applicatifs que de sources de données à mettre en vente. Evidemment, dans ce cas, il n'y aura aucun accès en direct aux différentes bases de données, les accès se faisant via des API, entre services. 
Potentiellement, d'ailleurs, il est possible d'envisager qu'un des sous-catalogues soit conçu via des modules (par exemple un module qui contient les description des produits et un autre qui a accès au stock réel des données disponibles) Dans ce cas, c'est un module qui aurait accès à la base de données.

Ouf, longue question :)

Logique/pas logique ?

Plus généralement, existe-t-il un moyen d'échange (un forum) des utilisateurs de cette solution ?

Merci,

Pascal

**Comment by dbarzin** [comment]
Bonjour Pascal,

Le modèle de données utilise dans Mercator est basé sur celui proposé par l’ANSSI. Si le système d’information qui doit être modélisé est grand, complexe, comporte de nombreux systèmes hétéroclites, ce modèle peut s’avérer incomplet.
Cependant en faisant quelques concessions sur la complétude de la cartographie, il est souvent possible de modéliser le système d’information avec le modèle proposé par Mercator.

Dans ton exemple, ce portail Web est plutôt une application qui peut faire partie du bloc applicatif "Applications de gestion clients". Dans le modèle Mercator, il n'existe qu'un lien entre l'application et la base de données. Disposer d'un modèle plus complet n'apporte pas grand choses à la cartographie du SI. Ici le mieux est de respecter la règle du KISS.

Merci pour la question,
Didier

**Comment by dbarzin** [comment]
Bonjour,
Il est maintenant possible d'attacher une base de donnnées à un serveur logique.
Cordialement,
Didier
