### ISSUE TITLE
Bug Flux 

### ISSUE THREAD

**Issue by victorgyt** [dbarzin/mercator#615]
Bonjour, 
Je vous écris aujourd'hui pour vous signaler un bug. Lorsque que nous cliquons sur les flux par exemple sur la partie "Transfert" (cf screen) qui se trouve dans la catégorie Flux, ce dernier nous retourne une erreur 500. 

![image](https://github.com/dbarzin/mercator/assets/152492865/d9bd7e76-fbb9-4c82-8677-e9cbd12560a1)

J'ai activé le mode debug. Et voici ce qu'il me retourne : 

![image](https://github.com/dbarzin/mercator/assets/152492865/f5e90b8d-b9c8-4e85-87de-793aef685dd1)
![image](https://github.com/dbarzin/mercator/assets/152492865/ba128966-a5a3-4ac5-92e2-3d3fe58e89ba)
![image](https://github.com/dbarzin/mercator/assets/152492865/9a894d69-7841-4d25-a8fb-6f0cec2014fe)

![image](https://github.com/dbarzin/mercator/assets/152492865/a43e6462-28d2-4f9d-9a0f-bc87e4981410)

![image](https://github.com/dbarzin/mercator/assets/152492865/734be818-8c93-4c79-8ecc-84ba8cbec477)

![image](https://github.com/dbarzin/mercator/assets/152492865/6db6dba2-a9c5-49d8-a1e9-063cbfc4d086)

Pouvez vous nous aider à résoudre ce soucis ? 

Merci ! 

V.G

**Comment by dbarzin** [comment]
Merci, corrigé ici https://github.com/dbarzin/mercator/pull/616

**Comment by victorgyt** [comment]
Bonjour, êtes vous sûr d'avoir corrigé le soucis ? 
Je rencontre encore le même problème malgré les update réalisé. 
![image](https://github.com/dbarzin/mercator/assets/152492865/fbf41b4d-b27d-4c98-99ac-dcfd68ae76e6)

**Comment by dbarzin** [comment]
OK, corrigé ici : https://github.com/dbarzin/mercator/pull/630

**Comment by dbarzin** [comment]
Corrigé ici : https://github.com/dbarzin/mercator/pull/631
Merci !
Didier
