### ISSUE TITLE
Spécificité IOT

### ISSUE THREAD

**Issue by moiiom59** [dbarzin/mercator#62]
Bonjour,
Même si le modèle est basé sur les propositions de l'ANSSI ne serait il pas intéressant de prévoir les particularités des matériels industriels ou Biomédicaux ?
La table périphérique est à mon sens trop limitée pour ces matériels, comme un lien avec d'autre actifs ?
merci

**Comment by dbarzin** [comment]
Quels liens faudrait-il ajouter à la table périphériques pour satisfaire ce besoin ?

**Comment by dbarzin** [comment]
La gestion des périphérique a été améliorée et devrait couvrir les besoins spécifiques aux IOT.
