### ISSUE TITLE
Erreur 500 Menu Serveurs Logiques

### ISSUE THREAD

**Issue by kuroboshi** [dbarzin/mercator#624]
Bonjour,

Lorsque je tentes d'accéder aux serveurs logiques dans la section "Vue Infra Logiques" j'ai une erreur 500.
Voici ce que j'ai après avoir activé le mode debug :
![2024_02_05_16_18_29_Mercator](https://github.com/dbarzin/mercator/assets/22149432/484dba2d-ce1e-4822-b311-7489aa43e3e4)

J'avais effectué l'installé de Mercator le 7 janvier dernier et lorsque j'ai effectué le git et lorsque je tente de mettre à jour la DB, il m'affiche ceci : INFO  Nothing to migrate.

cdt

**Comment by kuroboshi** [comment]
Pour info, je peux accéder au serveur virtuel de cette façon :
https://serveur.lan/admin/logical-servers/3

**Comment by dbarzin** [comment]
Le problème ne se produit pas dans l'environnement de développement.

Peux-tu essayer de vider les caches :

    php artisan optimize:clear

et réessayer d'accéder à la page.

**Comment by kuroboshi** [comment]
Malgré le résultat "Done" cela n'a pas résolu le problème.
Pour ce mettre environnement de dev, il faut renseigner quoi dans "APP_ENV" ?

**Comment by dbarzin** [comment]
Tu peux mettre APP_ENV=local mais cela n'a pas d'impact.

**Comment by dbarzin** [comment]
Je viens de pousser un patch qui va régler le problème.

**Comment by dbarzin** [comment]
Tu peux mettre APP_ENV=local mais cela n'a pas d'impact.
