### ISSUE TITLE
Insertion d'image

### ISSUE THREAD

**Issue by sowhatkob** [dbarzin/mercator#63]
Bonjour, 
Lorsque j'utilise le bouton Insert Image dans les champs de description, rien ne se passe après avoir choisi l'image que l'on souhaite insérer. J'ai essayé avec Edge, Firefox et Chrome avec le même résultat.
Est-ce un problème d'installation ou une fonction non encore disponible ?
Merci
Marc

**Comment by dbarzin** [comment]
Cette fonction a été désactivée car cela posait des problèmes avec les listes Excel et les rapports en Word.
Le bouton va être supprimé de ce composant.

**Comment by dbarzin** [comment]
CKEditor a été mis à jours en version 5 sans l'ajout d'images.
