### ISSUE TITLE
Chiffrement base de données

### ISSUE THREAD

**Issue by krptg0** [dbarzin/mercator#636]
Bonjour,

Est-il prévu un mécanisme de chiffrement des données en base ?
Ceci pourrait être requis lors des audits ISO27001/HDS.

Merci,

**Comment by dbarzin** [comment]
C'est facile à mettre en œuvre avec une base de données mySQL. Je t'invite à consulter la documentation à ce sujet.

**Comment by krptg0** [comment]
Exact, je ne l'avais pas vu du point de vue DB, merci !
