### ISSUE TITLE
Serveurs DNS et DHCP en double-pile

### ISSUE THREAD

**Issue by leManu** [dbarzin/mercator#642]
Hello,

Nos serveurs DNS et DHCP sont en double-pile IPv4/IPv6, mais il n'est pas possible d'indiquer deux adresses dans le formulaire d'édition, qui n'autorise à priori qu'une seule adresse.

Serait-il possible d'autoriser l'ajout de plusieurs adresses pour ces serveurs ?

**Comment by dbarzin** [comment]
En place  : https://github.com/dbarzin/mercator/pull/644
