### ISSUE TITLE
Problèmes rencontrés avec les API Mercator 

### ISSUE THREAD

**Issue by BadaouiMu** [dbarzin/mercator#649]
Bonjour,

Je travaille actuellement sur un script en Python visant à automatiser le remplissage des bases de données Mercator en utilisant les API disponibles. Cependant, je rencontre des problèmes avec certaines des API qui retournent des erreurs.

Pour mieux identifier les API qui génèrent des erreurs, j'ai développé un petit script Python pour détecter et répertorier les API rencontrant des problèmes. J'ai extrait la liste complète de toutes les API à partir de la page suivante : [Mercator API](https://dbarzin.github.io/mercator/api/).

Voici le résultat de l'exécution du script :
```
Login
200
Les API qui retournent :
{
    "message": "403 Forbidden"
}
['macro-processuses', 'application-services', 'zone-admins', 'forest-ads', 'network-switches', 'security-devices', 'wifi-terminals']


Les API qui retournent :
{
    "message": "The route api/roles could not be found."
}
['data_processing', 'security_devices', 'macro-processes', 'permissions', 'roles']

```

Le script Python : 
```
import requests
headers = {
    'accept': 'application/json',
    'content-type': 'application/x-www-form-urlencoded',
    'cache-control': 'no-cache'
}
print("Login")
login_data = {'email': 'admin@admin.com', 'password': 'password'}
login_response = requests.post("http://172.20.10.2:8000/api/login", headers=headers, data=login_data)
print(login_response.status_code)

if login_response.status_code == 200:
    access_token = login_response.json().get('access_token')
    headers['Authorization'] = "Bearer " + access_token
    url = "http://172.20.10.2:8000/api/"
    ll = ['data_processing', 'security_devices','entities','relations','macro-processes','macro-processuses','processes','operations','actors','activities','tasks','information','application-blocks','applications','application-modules','application-services','databases','fluxes','zone-admins','annuaires','forest-ads','domaine-ads','networks','subnetworks','gateways','external-connected-entities','network-switches','routers','security-devices','dhcp-servers','dnsservers','logical-servers','certificates','sites','buildings','bays','physical-servers','workstations','storage-devices','peripherals','phones','physical-switches','physical-routers','wifi-terminals','physical-security-devices','wans','mans','lans','vlans','users','permissions','roles']
    F = []
    N = []
    for i in ll: 
        security_device_response = requests.get(url+i, headers=headers)
        if "403 Forbidden" in security_device_response.text: 
            F.append(i)
            forbid = security_device_response.text
        elif "could not be found" in security_device_response.text:
            N.append(i)
            notfound = security_device_response.text
else:   
    print("Login failed")

print ("Les API qui retournent : \n" + forbid)
print (F)
print ("\n \n Les API qui retournent : \n" + notfound)
print ( N)
```

Le script tente d'accéder à chaque API répertoriée, mais il semble rencontrer des problèmes avec certaines d'entre elles. J'aimerais avoir des suggestions sur la manière de résoudre ces problèmes ou des conseils sur la façon de travailler avec ces API.

Toute aide serait grandement appréciée. Merci d'avance!

Cordialement,
Mustapha

**Comment by dbarzin** [comment]
Merci, je regarde cela rapidement.

**Comment by BadaouiMu** [comment]
Merci pour la correction. Il reste juste un petit souci avec les mesures de sécurité (RGPD). Dans la documentation, ils ont une API : api/security_device, mais cela ne fonctionne pas. L'API api/security-device est plutôt pour les équipements de sécurité.

**Comment by dbarzin** [comment]
Tu parles sans doute des security-controls qui ne se trouvaient effectivement pas dans l'API ( :smile: ). Pour obtenir la liste des routes, la commande Laravel est :

    php artisan route:list

**Comment by BadaouiMu** [comment]
Parfait, merci pour la clarification et pour la commande Laravel !

**Comment by BadaouiMu** [comment]
Bonjour,

Je reviens vers vous concernant notre précédent échange. Dans le cadre de mon travail d'automatisation pour Mercator, j'ai pu avancer, mais j'ai rencontré quelques défis. Plutôt que de vous solliciter à chaque fois, j'ai essayé de les résoudre moi-même. Vous trouverez l'ensemble des modifications apportées (sur la dernière version disponible) à l'adresse suivante : [https://github.com/dbarzin/mercator/compare/master...BadaouiMu:mercator:master](url)

J'attends votre retour pour savoir si mes modifications seront intégrées à votre version (afin que je puisse adapter le code d'automatisation).

Par ailleurs, voici quelques améliorations qui pourraient être envisagées à l'avenir :

1. Pour le contrôle de sécurité, j'ai préféré suivre les mesures de l'ISO 27002, donc j'ai supprimé dans mon code la règle des moins de 32 caractères pour celle-ci.
2. Il serait préférable que le processus soit identifié avec l'attribut "name" plutôt que "identifiant" dans le JSON (pour une uniformité avec les autres vues).
3. Je me demande s'il est possible de ne pas imposer de filtres IP. Parfois, les adresses IP sont sous forme de plage (par exemple 192.168.1.1-5) et ne sont pas acceptées par l'application.
4. Établir des connexions entre la vue des switchs logiques et la vue des switchs physiques, entre la vue des routeurs logiques et la vue des routeurs physiques, ainsi qu'entre la vue des switchs et la vue des VLANs (conformément aux recommandations du guide de cartographie du SI).
5. J'ai eu du mal à comprendre comment connecter les différentes vues (par exemple, associer des entités à des processus). J'ai dû analyser le code et utiliser des applications externes (comme Burp Suite) pour comprendre comment le faire. Une amélioration consisterait à mieux documenter cette partie.
6. En ce qui concerne les liens physiques, il serait préférable que si la source ou la destination est supprimée, le lien soit également supprimé.

Merci d'avance pour votre attention.

**Comment by dbarzin** [comment]
Bonjour Moustapha,

1. Pour le contrôle de sécurité, j'ai préféré suivre les mesures de l'ISO 27002, donc j'ai supprimé dans mon code la règle des moins de 32 caractères pour celle-ci.

_Je propose de garder une limite à 255 caractères_ 

2. Il serait préférable que le processus soit identifié avec l'attribut "name" plutôt que "identifiant" dans le JSON (pour une uniformité avec les autres vues).

__Une migration va être créée pour changer le nom de ce champ__

3. Je me demande s'il est possible de ne pas imposer de filtres IP. Parfois, les adresses IP sont sous forme de plage (par exemple 192.168.1.1-5) et ne sont pas acceptées par l'application.

__ Je préfère conserver un filtre strict sur les plages IP, car cela peut poser des problèmes dans l'algorithme qui calcule sur une adresse IP appartient à une plage donnée.__

4. Établir des connexions entre la vue des switchs logiques et la vue des switchs physiques, entre la vue des routeurs logiques et la vue des routeurs physiques, ainsi qu'entre la vue des switchs et la vue des VLANs (conformément aux recommandations du guide de cartographie du SI).

__Oui, tout à fait.__

5. J'ai eu du mal à comprendre comment connecter les différentes vues (par exemple, associer des entités à des processus). J'ai dû analyser le code et utiliser des applications externes (comme Burp Suite) pour comprendre comment le faire. Une amélioration consisterait à mieux documenter cette partie.

__Il me manque de temps pour tout documenter. Les contributions sont les bienvenues.__

6. En ce qui concerne les liens physiques, il serait préférable que si la source ou la destination est supprimée, le lien soit également supprimé.

__Tu as sans doute remarqué que cela fonctionne avec des "soft delete", les objets supprimés ne le sont pas réellement mais seulement marqués comme supprimés. Lorsqu'ils sont supprimés physiquement de la DB, pour que le lien physique soit aussi supprimé, il faut changer l'index et mette l'option "on delete cascade". Cela sera fait dans la prochaine migration DB.__

Petit conseil, essaye de pousser tes changements dans GitHub via un pull request dans la branche dev.

Merci pour ta contribution au projet.
Didier

**Comment by BadaouiMu** [comment]
Bonjour Didier,

Merci pour tes retours détaillés.

Pour ce qui est de la documentation, je vais essayer de m'y atteler dès que j'aurai terminé mon script d'automatisation en cours.

Et merci pour le conseil concernant GitHub.

Bien à toi,
Mustapha

**Comment by dbarzin** [comment]
Je reviens sur ce point : 

4. Établir des connexions entre la vue des switchs logiques et la vue des switchs physiques, entre la vue des routeurs logiques et la vue des routeurs physiques, ainsi qu'entre la vue des switchs et la vue des VLANs (conformément aux recommandations du guide de cartographie du SI).


Les switchs logiques et physiques ne sont pas liés. Un switch logique se trouve dans une infrastructure virtuelle et effectue la connexion entre machine virtuelle dans l'environnement virtualisé. Il en va de même pour les routeurs logiques et physiques.

**Comment by BadaouiMu** [comment]
Oui, je suis d'accord avec toi. Cependant, selon les directives de l'ANSSI, il est vraiment nécessaire de faire une séparation claire entre la vue logique et la vue physique. Dans la partie logique, nous devons inclure des éléments tels que l'adresse IP et les règles de filtrage, tandis que dans la partie physique, nous devons spécifier des détails tels que le modèle, la version et l'emplacement.

Et dans le cas où le switch est virtualisé, il devrait être possible de saisir son serveur physique dans la vue logique.

![Screenshot 2024-04-29 105022](https://github.com/dbarzin/mercator/assets/154766036/da92bc0d-b55d-4e55-87f6-6d06e3653ca3)

**Comment by dbarzin** [comment]
OK, je vais ajouter ces liens.

**Comment by BadaouiMu** [comment]
Pour les routeurs, c'est un lien 1-1. Pour les commutateurs, c'est 1 (physique) - n (logiques). Et pour les VLAN, c'est bien n-m.

![image](https://github.com/dbarzin/mercator/assets/154766036/12de96f1-7300-47ad-951d-ec6a1d2c7827)

**Comment by BadaouiMu** [comment]
Oui, tu as raison, c'est possible.
