### ISSUE TITLE
mise a jour Mercator

### ISSUE THREAD

**Issue by ChevaucheurDeVague** [dbarzin/mercator#65]
Bonjour,

je viens de suivre la procédure de mise a jour de l'application.
cela bloque à **compose update** : Error: no "compose" mailcap rules found for type "cannot open 'update' (no such files or directory)"

j'ai ignoré l'étape et nettoyer le cache.
quand je me connecte à l'appli maintenant cela me fait l'erreur suivante :
Symfony\Component\ErrorHandler\Error\FatalError
Cannot use ::class with dynamic class name 

Symfony\Component\ErrorHandler\Error\FatalError::__construct
app/Traits/Auditable.php:28

**Comment by dbarzin** [comment]
Essaye ceci 

    composer update

Cela a été corrigé dans la doc.

**Comment by ChevaucheurDeVague** [comment]
ha ok ;)
et du coup je met a jour php 8.0 ...
merci

**Comment by dbarzin** [comment]
Problème de permission d'accès au fichier composer.lock

    ls -l composer.lock

**Comment by dbarzin** [comment]
Puis installer PHP v8 et les librairies

Install CA certificates

    sudo apt install  ca-certificates apt-transport-https software-properties-common

Add php v8 repository

    sudo add-apt-repository ppa:ondrej/php

Install PHP v8.0 and some libraries

    sudo apt install php8.0 libapache2-mod-php8.0 php8.0-zip php8.0-curl php8.0-mbstring php8.0-dom php8.0-ldap php8.0-soap php8.0-xd

Bon amusement

**Comment by ChevaucheurDeVague** [comment]
bonjour,

j'ai mis a jour vers php8.0 mais j'ai eu des problèmes après.
ce matin j'ai remis a jour l'appli, fais un back-up / restore de la base comme indiqué dans la doc.
Résultat :
mon navigateur m'affiche ça :
=> " */ define('LARAVEL_START', microtime(true)); /* |-------------------------------------------------------------------------- | Register The Auto Loader |-------------------------------------------------------------------------- | | Composer provides a convenient, automatically generated class loader for | our application. We just need to utilize it! We'll simply require it | into the script here so that we don't have to worry about manual | loading any of our classes later on. It feels great to relax. | */ require __DIR__.'/../vendor/autoload.php'; /* |-------------------------------------------------------------------------- | Turn On The Lights |-------------------------------------------------------------------------- | | We need to illuminate PHP development, so let us turn on the lights. | This bootstraps the framework and gets it ready for use, then it | will load up this application so that we can run it and send | the responses back to the browser and delight our users. | */ $app = require_once __DIR__.'/../bootstrap/app.php'; /* |-------------------------------------------------------------------------- | Run The Application |-------------------------------------------------------------------------- | | Once we have the application, we can handle the incoming request | through the kernel, and send the associated response back to | the client's browser allowing them to enjoy the creative | and wonderful application we have prepared for them. | */ $kernel = $app->make(Illuminate\Contracts\Http\Kernel::class); $response = $kernel->handle( $request = Illuminate\Http\Request::capture() ); $response->send(); $kernel->terminate($request, $response); "


j'ai relevé quelques erreurs dans la doc :
- il y a des "compose update" encore (procédure d'update et après aussi)
- dans le "backup database" user il manque un antislash sur une ligne

dans la mise a jour de php8.0 cette librairie n'a pas l'air d’exister : php8.0-xd

**Comment by dbarzin** [comment]
Il semble que php8.0 ne soit pas installé.
Quel OS utilises tu ?

**Comment by ChevaucheurDeVague** [comment]
ubuntu 20.04.3 64bit sur VM hyperV

php -v me renvoie :  PHP 8.0.14

**Comment by ChevaucheurDeVague** [comment]
oui je pense que je vais réinstaller, du coup avec Ubuntu 21.10 comme conseillé
ça sera plus rapide...
je met de coté mes sauvegardes sql et je fais ça
