### ISSUE TITLE
probleme mise a jour

### ISSUE THREAD

**Issue by webchl** [dbarzin/mercator#657]
bonjour,

suite a la mise a jour ce jour je ne peux plus accès au registre
`Symfony
 \ 
Component
 \ 
Routing
 \ 
Exception
 \ 
RouteNotFoundException
PHP 8.1.2-1ubuntu2.14
10.48.3
Route [admin.data-processing.create] not defined.

Expand vendor frames
Illuminate
 \ 
Routing
 \ 
UrlGenerator
 
: 477
route
vendor
 / 
laravel
 / 
framework
 / 
src
 / 
Illuminate
 / 
Foundation
 / 
helpers
.php
 
: 811
route
resources
 / 
views
 / 
admin
 / 
dataProcessing
 / 
index.blade
.php
 
: 6
require
13 vendor frames
App
 \ 
Http
 \ 
Middleware
 \ 
SetLocale
 
: 28
handle
1 vendor frame
App
 \ 
Http
 \ 
Middleware
 \ 
AuthGates
 
: 32
handle
16 vendor frames
App
 \ 
Http
 \ 
Middleware
 \ 
ForceXForwardedProto
 
: 17
handle
22 vendor frames
resources
 / 
views
 / 
admin
 / 
dataProcessing
 / 
index.blade
.php
 
: 6

@extends('layouts.admin')

@section('content')

@can('data_processing_register_create')

    <div style="margin-bottom: 10px;" class="row">

        <div class="col-lg-12">

            <a class="btn btn-success" href="{{ route('admin.data-processing.create') }}">

                {{ trans('global.add') }} {{ trans('cruds.dataProcessing.title_singular') }}

            </a>

        </div>

    </div>

@endcan

<div class="card">

    <div class="card-header">

        {{ trans('cruds.dataProcessing.title_singular') }} {{ trans('global.list') }}

    </div>

    <div class="card-body">

        <div class="table-responsive">

            <table class=" table table-bordered table-striped table-hover datatable datatable-Activity">

                <thead>

                    <tr>

                        <th width="10">

                        </th>

                        <th>

                            {{ trans('cruds.dataProcessing.fields.name') }}

                        </th>

                        <th>

                            {{ trans('cruds.dataProcessing.fields.description') }}

                        </th>
REQUEST
Browser
Headers
Body
APP
Routing
Views
CONTEXT
User
Git
Versions
REQUEST
http://XX.XX.XX.XX/admin/data-processings
GET
curl "http://XX.XX.XX.XX/admin/data-processings" \
   -X GET \
   -H 'host: XX.XX.XX.XX' \
   -H 'connection: keep-alive' \
   -H 'upgrade-insecure-requests: 1' \
   -H 'dnt: 1' \
   -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36' \
   -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
   -H 'referer: http://XX.XX.XX.XX/admin/bays' \
   -H 'accept-encoding: gzip, deflate' \
   -H 'accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
   -H 'cookie: <CENSORED>';

Browser
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

Headers
host
XX.XX.XX.XX

connection
keep-alive

upgrade-insecure-requests
1

dnt
1

user-agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

accept
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7

referer
http://XX.XX.XX.XX/admin/bays

accept-encoding
gzip, deflate

accept-language
fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7

cookie
<CENSORED>

Body
[]

APP
Routing
Controller
App\Http\Controllers\Admin\DataProcessingController@index

Route name
admin.data-processings.index

Middleware
web

auth

Views
View
resources
 / 
views
 / 
admin
 / 
dataProcessing
 / 
index.blade
.php
Data
CONTEXT
User
adresse@mail.fr
91103

adresse@mail.fr

{
    "id": 1,
    "name": "91103",
    "email": "adresse@mail.fr",
    "email_verified_at": null,
    "granularity": 3,
    "language": "fr",
    "created_at": null,
    "updated_at": "2021-12-20 13:43:38",
    "deleted_at": null,
    "guid": null,
    "domain": null,
    "roles": [
        {
            "id": 1,
            "title": "Admin",
            "created_at": null,
            "updated_at": null,
            "deleted_at": null,
            "pivot": {
                "user_id": 1,
                "role_id": 1
            }
        }
    ]
}

Git
Update INSTALL.md
e1b5173876d108392017d3e8741ce58d49d0d0f8

View commit e1b5173
Last commit is dirty. (Un)staged changes have been made since this commit.

Latest tag
v1.c

Versions
Php Version
8.1.2-1ubuntu2.14

Laravel Version
10.48.3

Laravel Locale
fr

Laravel Config Cached
false
App Debug
true
App Env
local

5
QUERIES

5
LOGS
09:55:27
1.85MS
MYSQL
SELECT * FROM `users` WHERE `id` = 1 AND `users`.`deleted_at` IS NULL limit 1

1 QUERY PARAMETER
09:55:27
0.51MS
MYSQL
SELECT * FROM `roles` WHERE `roles`.`deleted_at` IS NULL

09:55:27
2.16MS
MYSQL
SELECT `permissions`.*, `permission_role`.`role_id` AS `pivot_role_id`, `permission_role`.`permission_id` AS `pivot_permission_id` FROM `permissions` INNER JOIN `permission_role` ON `permissions`.`id` = `permission_role`.`permission_id` WHERE `permission_role`.`role_id` IN (1, 2, 3) AND `permissions`.`deleted_at` IS NULL

09:55:27
0.7MS
MYSQL
SELECT `roles`.*, `role_user`.`user_id` AS `pivot_user_id`, `role_user`.`role_id` AS `pivot_role_id` FROM `roles` INNER JOIN `role_user` ON `roles`.`id` = `role_user`.`role_id` WHERE `role_user`.`user_id` = 1 AND `roles`.`deleted_at` IS NULL

1 QUERY PARAMETER
09:55:27
0.58MS
MYSQL
SELECT * FROM `data_processing` WHERE `data_processing`.`deleted_at` IS NULL ORDER BY `name` ASC

·
SOURCE
·
DOCS
·
LARAVEL
Ignition is built byFlare, the Laravel error reporting service.`

IDEM POUR LA PAGES DES CORRECIFS:

`Undefined variable $patching_group_list

Expand vendor frames
Illuminate
 \ 
Foundation
 \ 
Bootstrap
 \ 
HandleExceptions
 
: 11
handleError
1 vendor frame
resources
 / 
views
 / 
admin
 / 
patching
 / 
index.blade
.php
 
: 11
require
13 vendor frames
App
 \ 
Http
 \ 
Middleware
 \ 
SetLocale
 
: 28
handle
1 vendor frame
App
 \ 
Http
 \ 
Middleware
 \ 
AuthGates
 
: 32
handle
16 vendor frames
App
 \ 
Http
 \ 
Middleware
 \ 
ForceXForwardedProto
 
: 17
handle
22 vendor frames
resources
 / 
views
 / 
admin
 / 
patching
 / 
index.blade
.php
 
: 11

@extends('layouts.admin')

@section('content')

<div style="margin-bottom: 10px;" class="row">

    <div class="col-lg-3">

        <form method="get" action="/admin/patching/index">

            <label class="recommended" for="patching_group">{{ trans('cruds.logicalServer.fields.patching_group') }}</label>

            <select name="group" class="form-control select2 {{ $errors->has('patching_group') ? 'is-invalid' : '' }}"

                    name="patching_group" id="patching_group"

                    onchange="this.form.submit()">

                <option value="None">&nbsp;</option>

                @foreach($patching_group_list as $group)

                    <option {{ session()->get('patching_group') == $group ? 'selected' : '' }}>{{ $group }}</option>

                @endforeach

            </select>

        </form>

    </div>

</div>

<div class="card">

    <div class="card-header">

        {{ trans('panel.menu.patching') }}

    </div>

    <div class="card-body">

        <div class="table-responsive">

            <table class=" table table-bordered table-striped table-hover datatable datatable-LogicalServer">

                <thead>

                    <tr>

                        <th width="10">`

merci+++

surement d'autres pages inaccessible dont je vais me rendre comtre en me baladant sur mercator
bon courage a vous

PS: les fonctionnalités prévues vont nous etre très utiles notamment la liaison avec MONARC, ou bien encore l'annuaire de crise. Bravo!! Avez vous de la visu sur les délais de ces prochaines évolutions merci ;-)

**Comment by dbarzin** [comment]
L'erreur provient de  _Undefined variable $patching_group_list_
C'est sans doute un problème de cache. Pour vider la cache :

    php artisan optimize:clear

**Comment by webchl** [comment]
non désolé toujours même erreur et après reboot également

**Comment by dbarzin** [comment]
Tu peux poster une capture d'écran de l'erreur ?

**Comment by webchl** [comment]
![Capture d’écran 2024-03-20 144804](https://github.com/dbarzin/mercator/assets/76811593/aea62215-d33f-423d-aa31-fbffa8ce89d2)

**Comment by webchl** [comment]
meme probleme

**Comment by webchl** [comment]
du coup je suis reparti d'un snapshot fonctionnel
et fait les commandes suivantes:

cd /var/www/mercator
sudo git clone https://github.com/dbarzin/mercator
sudo -u www-data php artisan migrate
sudo -u www-data composer update
sudo -u www-data php artisan config:clear &&  php artisan view:clear

et tout fonctionne de nouveau
merci
