### ISSUE TITLE
docker-compose deployment

### ISSUE THREAD

**Issue by hadhub** [dbarzin/mercator#660]
Bonjour @dbarzin

Je prévois de déployer mercator via docker-compose sur un serveur de test en utilisant sqlite par défaut, après avoir modifié les différents fichiers de config :
./docker-compose.yml
./env/mercator.env
./PV/nginx/nginx.conf 

j'ai également précisé les 2 lignes suivantes dans mercator.env :
```
# Database connexion
DB_CONNECTION=sqlite
DB_DATABASE=/var/www/mercator/sql/db.sqlite
```

le démarrage des 2 ct sont OK mais impossile d'utiliser le login par défaut _admin@admin.com:password_. 

A quel moment les données de la base sont importés dans db.sqlite ?

<img width="1440" alt="Capture d’écran 2024-03-27 à 2 45 18 PM" src="https://github.com/dbarzin/mercator/assets/85348372/e1990d49-ed2f-4a1d-8cc0-69aac65109df">

**Comment by dbarzin** [comment]
La base de données et les données initiales nécessaires pour l'utilisation de l'application (création de l'utilisation admin, droits d'accès, roles...) sont créés avec cette commande : 

    php artisan migrate --seed
