### ISSUE TITLE
Erreur sur l'écran d'édition de flux pour les sources et destinations de type Database

### ISSUE THREAD

**Issue by j-ova** [dbarzin/mercator#662]
Bonjour,

Lorsqu'on manipule des Flux, si la source ou la destination sont de type Base de donnée, la valeur n'est pas correctement chargée dans l'écran d'édition du flux.

En creusant les sources, j'ai détecté que l'objet Flux renvoie un identifiant nommé "DATABASE_XXX" et que l'écran d'édition tente de le mapper avec une valeur nommée "DB_XXX" : 
- https://github.com/dbarzin/mercator/blob/master/app/Flux.php#L47
- https://github.com/dbarzin/mercator/blob/master/app/Flux.php#L66
- https://github.com/dbarzin/mercator/blob/master/app/Http/Controllers/Admin/FluxController.php#L169
- https://github.com/dbarzin/mercator/blob/master/app/Http/Controllers/Admin/FluxController.php#L180

Le chargement de la liste ne met donc jamais aucun élément en "selected" par défaut lorsqu'il s'agit d'une base de données : 
- https://github.com/dbarzin/mercator/blob/master/resources/views/admin/fluxes/edit.blade.php#L62
- https://github.com/dbarzin/mercator/blob/master/resources/views/admin/fluxes/edit.blade.php#L79

Ce bug oblige à devoir re-sélectionner systématiquement la source et la destination d'un flux lorsqu'on l'ouvre en édition sous peine de perdre la donnée lorsqu'on sauvegarde la page.

Au-delà de ça, merci pour cet outil très fonctionnel qui va beaucoup m'aider à formaliser et maintenir la cartographie de notre SI !

**Comment by dbarzin** [comment]
Merci, c'est corrigé ici : https://github.com/dbarzin/mercator/pull/664/commits/716478e69caab06cf332ae35e3469ca015b9b836

**Comment by j-ova** [comment]
Super réactivité, merci :)

**Comment by j-ova** [comment]
@dbarzin je ne sais pas si j'ai mal fait quelque chose mais la mise à jour a l'air d'avoir appliqué un patch de db qui n'a pas de traduction dans le code.

Le fichier /database/migrations/2024_03_19_195927_contracts.php a été appliqué à mon redémarrage d'instance mais le code php cherchait toujours la colonne "importance" qui a été renommée dans ce patch.

J'ai un peu galéré à rollback car je ne connais pas les mécaniques php/Laravel. 
J'ai tenté des choses manuellement et j'ai fini par y arriver. J'ai découvert au milieu du chemin qu'un "php artisan migrate:rollback --path=./database/migrations/2024_03_19_195927_contracts.php" aurait pu suffire mais j'avais cassé trop de choses déjà pour que ça marche...

**Comment by dbarzin** [comment]
Cette modification n'aurait pas dû passer déjà passer en production.

**Comment by dbarzin** [comment]
Corrigé ici : https://github.com/dbarzin/mercator/commit/4f3f17ce9ce9e58a0a200311a70ce506ccc21b50

**Comment by j-ova** [comment]
Migration réappliquée avec succès. Merci !
