### ISSUE TITLE
Limitation du nombre de caractères lors de la création d'une application

### ISSUE THREAD

**Issue by Siruv** [dbarzin/mercator#663]
Bonjour,

Lors de la saisie d'une nouvelle application, j'ai une erreur sur la limitation du nombre de caractères sur le nom de l'application que je souhaite renseigner.

Est-ce un fonctionnement voulu ?

Cordialement,

![Capture d’écran du 2024-03-29 15-53-30](https://github.com/dbarzin/mercator/assets/2051135/5565d0b4-4c8f-4579-94cb-cbce3144e723)

**Comment by Siruv** [comment]
Je ne comprends pas, car en lisant la documentation, on voit bien que la valeur du nombre de caractères est de 255

![Capture d’écran du 2024-03-29 16-10-20](https://github.com/dbarzin/mercator/assets/2051135/d6c01327-bd08-47ad-8a5d-69aa75dd82a8)

**Comment by dbarzin** [comment]
Le nom des objets a été limité à 32 caractères pour pouvoir les afficher correctement sur les graphiques.
Le `varchar(255)` provient de la déclaration d'un string dans Laravel.

**Comment by Siruv** [comment]
Merci, je comprends mieux.
