### ISSUE TITLE
[API] La terminaison /api/data-processing semble absente

### ISSUE THREAD

**Issue by merlin-lepiaf** [dbarzin/mercator#665]
Bonjour, 
je suis désolé de vous solliciter de la sorte, je découvre avec plaisir votre application, et envisage de l'utiliser à terme pour une structure de santé, à but non lucratif. 

En prévision du peuplement de l'application, je m'essaye à l'usage du webservice, et mon premier essais me conduit au message
{'message': 'The route api/data-processing could not be found.'}. Je dois reconnaitre que je ne suis pas développeur et que j'ai sans doutes loupé une étape. Toutefois; Je parviens bien à consulter la terminaison /api/entities par exemple.

Merci de votre aide, 

Ralph.

**Comment by dbarzin** [comment]
Cette api est effectivement manquante, elle va être ajoutée rapidement. 
Avez-vous l'intention de peupler automatiquement le registre des traitements ?

**Comment by merlin-lepiaf** [comment]
Bonjour, je compte effectivement proposer aux collaborateurs d'importer les différents éléments via les api disponibles, en récuperant les informations depuis leurs sources respectives et en formalisant des fichiers csv, que nous pourrons alors faire vivre dans le temps. L'idée est de maintenir le travail de mises à jour régulières des éléments meme apres le gros travail initial de formalisation. 
Mais la partie RGPD peut attendre, ce n'est pas le plus urgent pour le moment. :-)
J'en profite pour vous féliciter pour cet énorme travail que vous avez réalisé avec vos équipes !!! Je pense parler prochainement Mercator aux autres structures de santé du territoire.  :-)

**Comment by dbarzin** [comment]
Cette API existe bien, elle s'appelle "/api/data-processings". La liste des API se trouve dans le fichier /route/api.php. 
On peut également exécuter cette commande pour avoir la liste de toutes les URL de l'application :

```sh
php artisan route:list
```

**Comment by merlin-lepiaf** [comment]
ah ok, la page de doc api en français https://github.com/dbarzin/mercator/blob/master/docs/api.fr.md indiquait : 

Vue du RGPD
/api/data-processing

D'ou mon erreur. Thanks a lot.

**Comment by dbarzin** [comment]
Merci !
