### ISSUE TITLE
Ajout de la modélisation des flux réseaux

### ISSUE THREAD

**Issue by chlcarto** [dbarzin/mercator#666]
Bonjour, 

Suite aux discussions que nous avions eues sur la possibilité de modéliser les flux réseaux dans Mercator, j'aurais aimé savoir s'il est toujours prévu de les ajouter selon les informations suivantes : 

- ID (UID automatique) **Obligatoire**
- Source **Obligatoire**
- Destination **Obligatoire**
- Port (destination) **Obligatoire**
- Protocole **Facultatif**
- Description **Facultatif**

Merci d'avance.

**Comment by dbarzin** [comment]
La source et destination des flux sont-ils modélisés par l'adresse IP (ou un range) ou une référence vers l'objet ?

**Comment by dbarzin** [comment]
Je propose pouvoir mettre plusieurs range IP pour les sources ou destination d'un flux. Cela permet de modéliser plus facilement un plus grand nombre de cas d'utilisation, par exemple un serveur et plusieurs clients sans devoir dupliquer les flux pour chaque client.

**Comment by dbarzin** [comment]
Je propose également d'ajouter le port source en facultatif.

**Comment by dbarzin** [comment]
Une partie de la gestion des flux logique est en place. Il est possible de créer, consulter et modifier des flux logiques ainsi que de les voir dans l'explorateur. Reste toute la partie reporting à développer.

**Comment by dbarzin** [comment]
En place !
