### ISSUE TITLE
Demande Evolution : bloc de sélection des "Bases de données" dans la vue des flux applicatifs

### ISSUE THREAD

**Issue by j-ova** [dbarzin/mercator#667]
Bonjour,

J'utilise l'objet Flux pour modéliser mes traitements d'échanges de données qui vont souvent directement lire/écrire dans les bases de données de notre SI Legacy. Quand je créé un objet "Flux", j'ai bien la possibilité de sélectionner une base de données. Par contre dans la vue de synthèse des flux applicatifs, je ne peux plus sélectionner que des blocs applicatifs ou des applications, même si les bases de données apparaissent dans la vue en dessous : 
![image](https://github.com/dbarzin/mercator/assets/123064435/77ced07d-f0a3-475d-b71a-858ca5656e5d)

En l'état j'ai donc de nombreux flux qui ne pourront jamais apparaitre dans cette vue de synthèse. 
Est-ce qu'il est possible d'avoir un bloc de sélection des bases de données au même titre que les applications/blocs applicatifs ?

Merci.

**Comment by dbarzin** [comment]
Lorsque tu double-cliques sur un objet de la cartographie, cela ouvre tous les objets liés.

**Comment by j-ova** [comment]
Dans la page report/explore effectivement on a cette possibilité et ça facilite bien l'exploration, mais la vue report/application_flows propose un affichage plus structuré et détaille textuellement les éléments affichés, donc je trouvais cette vue plus intéressante pour du reporting/de la documentation.

Maintenant, si l'évol est trop complexe, je m'en sortirai avec les visualisations/exports déjà existant.

**Comment by dbarzin** [comment]
C'est possible, cela va être implémenté.

**Comment by dbarzin** [comment]
Tu peux mettre toutes les applications dans le même bloc applicatif. Les applications seront présentes si elles ont un lien avec ce bloc applicatif.

**Comment by j-ova** [comment]
Bonjour,

Juste pour comprendre le workflow, le passage en "Completed" n'implique pas forcément immédiatement un nouveau package ?

Merci.

**Comment by dbarzin** [comment]
Ajouter un bloc de sélection des bases de données au même titre que les applications/blocs applicatifs satisferait-il ta demande ?

**Comment by j-ova** [comment]
Bonjour,
Oui c'est exactement ça :)
Merci.

**Comment by dbarzin** [comment]
C'est changé ici : https://github.com/dbarzin/mercator/commit/3c6e72fe611cf85da636db151f294a156ac65a5f

**Comment by j-ova** [comment]
Déployé et validé ! Merci !

**Comment by dbarzin** [comment]
Je viens de corriger un bug concernant ce change.
