### ISSUE TITLE
[API] Terminaison /api/processes

### ISSUE THREAD

**Issue by merlin-lepiaf** [dbarzin/mercator#670]
Lors d'un GET, la terminaison /api/processes retourne des données de la forme:
`{'id': 18, 'identifiant': 'processus8', 'description': '<p><strong>Je decris mon processus</strong></p>', 'owner': 'Merlin', 'security_need_c': 3, 'in_out': '<p>Ma description Inputs/outPut</p>', **'dummy': None**, 'created_at': '2024-04-05 18:35:00', 'updated_at': '2024-04-05 18:39:24', 'deleted_at': None, 'macroprocess_id': 12, 'security_need_i': 2, 'security_need_a': 4, 'security_need_t': 2}`

- Le champs 'dummy' n'est pas décrit dans le modele. 
- Bien que saisis dans l'application, il n'est pas prévu de remonter les valeurs Activités, Entités, ... ? 

Merci de votre retour.

**Comment by dbarzin** [comment]
C'est une erreur lors de la création de cette table. Le champ "dummy" va être supprimé.

**Comment by dbarzin** [comment]
Corrigé !

**Comment by merlin-lepiaf** [comment]
cool, si vous le voulez bien je continue à vous remonter mes observations sur les api :-)
Merci encore.
