### ISSUE TITLE
Vue Metiers > Taches

### ISSUE THREAD

**Issue by merlin-lepiaf** [dbarzin/mercator#671]
- Le champs description est un simple champs text, il ne permet pas de mise en forme html comme les champs description dans les autres modules comme Operations ou Activites par exemple. 
- Au niveau de la terminaison /api/tasks le champs requis est 'nom' contrairement à tous les autres modules où c'est 'name' qui est attendu, comme indiqué de plus dans le modele de données. Il y a une petite incohérence à ce niveau.

**Comment by dbarzin** [comment]
Corrigé !

**Comment by merlin-lepiaf** [comment]
:-D

**Comment by merlin-lepiaf** [comment]
Rebonsoir, 
je ne sais pas si c'est lié, mais la vue Operations n'affiche pas l'intitulé des Taches, comme visible sur la capture d'écran. 
Je ne sais pas si c'etait le cas avant la mise à jour, je m'en excuse. 
<img width="1205" alt="Capture d’écran 2024-04-07 à 19 43 58" src="https://github.com/dbarzin/mercator/assets/81599930/4e26da7c-5d36-4b2b-8f25-7610e595fd1d">
Parvenez-vous à reproduire ce comportement ou ce serait un probleme sur mon install ? 
Cordialement.

**Comment by dbarzin** [comment]
Corrigé !
Merci.
