### ISSUE TITLE
Mauvaise redirection sur édition d'un macro-processus en vue Exploration

### ISSUE THREAD

**Issue by chlcarto** [dbarzin/mercator#693]
Bonjour, 

Lorsqu'on souhaite modifier un macro-process à partir de la vue "Exploration" il y a une redirection erronée sur 
![image](https://github.com/dbarzin/mercator/assets/165758782/210f2aac-3eed-4f4e-8f19-111ab9d13991) (**macro_processuses**)

au lieu de

![image](https://github.com/dbarzin/mercator/assets/165758782/d04b6b1c-29c3-49de-826b-f44ec6bba845) (**macro-processuses**)

à partir de **Application -> Macro-processus**, donnant lieu à une Erreur 404 Not Found bien que le macro-process existe.

Merci d'avance, fais moi savoir si tu as besoin de plus d'informations.

**Comment by dbarzin** [comment]
Corrigé ici : https://github.com/dbarzin/mercator/commit/bbc18d469aabc0a8748811e0c05eecf7275a0e93
