### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by ChevaucheurDeVague** [dbarzin/mercator#70]
bonjour,

j'ai pas réussi a reprendre la main sur Mercator depuis.
j'ai recrée une VM hyperV avec le dernier Ubuntu 21.10.

sur le déroulé de l'install mon premier blocage  :
le dossier www n’existe pas sur une installation neuve.
quel droits dois-je accordé à ce dossier?

j'ai commencé a tâtonner a partir de là et au final cela ne fonctionne pas(apache installé et configuré)
composer update me dit que composer.lock  ne peut pas être ouvert car Permission denied
quand je fais git pull : permission non accordée impossible d'ouvrir .git/Fetch_head

**Comment by dbarzin** [comment]
Je vais rejouer la procédure d'installation et revoir la documentation.

**Comment by dbarzin** [comment]
La procédure a été modifiée. Il manquait quelques sudo.
Le répertoire /var/www était bien présent sur le serveur après l'installation avec ubuntu-21.10-desktop-amd64
Pas de problème avec git.
Comme on dit : "il faut bien suivre la recette".

**Comment by ChevaucheurDeVague** [comment]
ok je recommence depuis le bédut

**Comment by ChevaucheurDeVague** [comment]
epilogue :
à mon premier essai de reinstall j'avais opter pour l'installation minimale d'Ubuntu et il ne faut pas....
au second essai avec install complète pas de souci.
là je viens de m'y remettre et c'est fonctionnel pour moi.
Juste Apache a finir de configurer correctement pour pouvoir consulter sur intranet.
