### ISSUE TITLE
Fonctionnalité oubli de mot de passe

### ISSUE THREAD

**Issue by rafutek** [dbarzin/mercator#702]
Bonjour,

Il semblerait que la fonctionnalité d'oubli de mot de passe ait un problème : quand j'indique avoir perdu mon mot de passe, il me dit ne pas trouver d'utilisateur avec cette adresse, pourtant mon utilisateur a bien cette adresse. Cela dit, l'email de mon utilisateur n'est pas vérifié.

![image](https://github.com/dbarzin/mercator/assets/47695845/b88b7afa-e950-46b0-9cac-45e21c734a13)

Cela vous dit quelque chose ? Y a-t-il une mauvaise configuration de ma part ?

Merci d'avance

**Comment by dbarzin** [comment]
Je suis occupé sur ce point, mais cela me prend un peu de temps. Le problème semble se trouver dans l'intégration d'une librairie Laravel au projet.

**Comment by dbarzin** [comment]
Corrigé ici : https://github.com/dbarzin/mercator/pull/819
