### ISSUE TITLE
[API] Webservice Flux Logiques

### ISSUE THREAD

**Issue by merlin-lepiaf** [dbarzin/mercator#703]
Bonjour
le webservice pour les Flux Logiques est absent. (pour la vue Infrastructures Logiques)
Est-il prévu de le développer ? Il n'est pas annoncé dans `routes/api.php` et le model n'y fait pas non plus référence dans la doc. 
Merci beaucoup de vos infos.

**Comment by dbarzin** [comment]
:tada: C'est disponible !

**Comment by merlin-lepiaf** [comment]
vous etes décidément hyper réactif :-) 👍🏿 
Merci merci !!

**Comment by merlin-lepiaf** [comment]
Je reviens sur le sujet car le modele de données n'est pas à jour avec logical-flows.
J'essaye donc de recouper les éléments.
Avec app/Http/Requests/StoreLogicalFlowRequest.php je devine les entrées nécessaires, mais me confirmez-vous que le protocole, le port source et le port destination ne sont pas intégrables via l'API ?

**Comment by dbarzin** [comment]
OK, typo corrigée. Voici le test

```python
#!/usr/bin/python3
import requests

vheaders = {}
vheaders['accept'] = 'application/json'

print("Login")
response = requests.post("http://127.0.0.1:8000/api/login",
    headers=vheaders,
    data= {'email':'admin@admin.com', 'password':'password'} )
print(response)
print(response.status_code)

vheaders['Authorization'] = "Bearer " + response.json()['access_token']

data = {'name': 'QuickChat', 'description': 'Rapid exchange of gossip', 'protocol': 'tcp', 'source_ip_range': '192.168.1.0/24', 'source_port': 1234, 'dest_ip_range': '192.168.2.0/24', 'dest_port': 5678}
response = requests.post('http://127.0.0.1:8000/api/logical-flows', data=data, headers=vheaders)
print(response.json())
print(response.status_code)
```

**Comment by merlin-lepiaf** [comment]
ok pour moi

**Comment by dbarzin** [comment]
Je viens d'ajouter le bouton "explore" sur la vue d'un flux logique.
