### ISSUE TITLE
[API] Clusters

### ISSUE THREAD

**Issue by merlin-lepiaf** [dbarzin/mercator#707]
Bonjour, la route /api/clusters n'est pas définie. 
`{'message': 'The route api/clusters could not be found.'}
404`

Est-elle planifiée ? Elle n'est pas encore définie dans routes/api.php ni dans docs/model.md.

Merci de votre retour.

**Comment by dbarzin** [comment]
:tada: C'est disponible !

**Comment by merlin-lepiaf** [comment]
ok, petit point d'attention cependant : sur l'interface utilisateur, il n'y a pas de champs **adress_ip** pour les clusters, toutefois le champs est présent en base de données et disponible via l'API. 
C'est dommage que les champs en liens avec les autres tables ne soient pas dispos via l'API, mais il est vrai que cela pourrait compliquer énormément les choses.

**Comment by dbarzin** [comment]
OK, corrigé !

**Comment by dbarzin** [comment]
Concernant les liens avec les autres objets, la difficulté est de peupler les tables intermédiaires (n-m). 
L'API a été mise à disposition principalement pour mettre à jour quelques éléments technique, mais pas pour peupler entièrement la cartographie. La cartographie reste un processus manuel durant lequel on confronte ce que l'on pense être en place avec ce qui est réellement en place. C'est un processus continu que le RSSI doit régulièrement effectuer.

**Comment by merlin-lepiaf** [comment]
> OK, corrigé !

super, merci à vous. 
Toutefois, j'ai constaté que la fonction "Delete Selected Items" sur la vue Clusters semble ne pas fonctionner. Le bouton supprimer de chaque ligne est ok, mais en sélectionnant plusieurs lignes, on ne peut pas supprimer. 

Souhaitez-vous que j'ouvre un autre ticket là-dessus plutôt ?

**Comment by dbarzin** [comment]
Je n'arrive pas à reproduire le problème de suppression de plusieurs clusters. Si tu arrives à le reproduire, tu peux créer un nouveau ticket et éventuellement poster l'erreur qui se trouve dans `storage/logs/laravel.log`.

**Comment by merlin-lepiaf** [comment]
👍🏿
