### ISSUE TITLE
apache application introuvable

### ISSUE THREAD

**Issue by denisght71** [dbarzin/mercator#71]
Bonjour,
Je rencontre un pb avec le serveur apache. Tout a l'air de fonctionner correctement en lançant php artisan serve. J'accède bien à la page de défaut d'apache mais impossible de trouver l'uri correspondante (erreur 404). Je précise que j'utilise ubuntu 20.04. Ci-dessous la config apache de mon site (j'ai commenté le serverName car il s'agit d'un test pour l'instant, je passe par l'ip).

```
<VirtualHost *:80>
#ServerName mercator.local
ServerAdmin admin@example.com
DocumentRoot /var/www/mercator/public
<Directory /var/www/mercator>
AllowOverride All
</Directory>
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**Comment by dbarzin** [comment]
Si tu accès à la page par défaut d'Apache c'est que le site Apache par défaut n'a pas été désactivé

    sudo a2dissite 000-default.conf

Activer le site Mercator

    sudo a2ensite mercator.conf

Enfin, redémarrez le service Apache pour activer les modifications :

    sudo systemctl restart apache2

**Comment by denisght71** [comment]
En effet je ne l'ai pas activé (peut être l'ajouter dans la proc). Ensuite j'ai eu un message :

`ErrorException
file_put_contents(/var/www/mercator/storage/framework/sessions/KVUTKGjdky8IuEnfmkoh2cFMO0dljo79GR650SWj): Failed to open stream: Permission denied `

résolu en repassant : 

`sudo chown -R www-data:www-data /var/www/mercator
sudo chmod -R 775 /var/www/mercator/storage`

Au final j'ai obtenu ce message:

`Illuminate\Database\QueryException
could not find driver (SQL: select * from `users` where `id` = 1 and `users`.`deleted_at` is null limit 1)`

Au final j'ai installé le module php8.0-mysql et ça roule ;-) ( attention au utilisateurs d'ubuntu 20.04LTS, il faut installer php8 manuellement car la version par défaut est la 7.4).

Merci pour ton aide.
