### ISSUE TITLE
Vue Cluster : probleme suppression multiple

### ISSUE THREAD

**Issue by merlin-lepiaf** [dbarzin/mercator#711]
Bonjour

sur la vue des clusters, je rencontre un problème de suppression lors d'une sélection multiple. 

Testé sous chrome et safari.
Je joins le fichier `storage/logs/laravel.log`, mais les différentes actions sur l'interface ne génerent pas de logs d'erreurs visibles.

[laravel.log](https://github.com/dbarzin/mercator/files/15095091/laravel.log)

**Comment by dbarzin** [comment]
La suppression multiple pose-t-elle des problèmes sur d'autres pages ?

**Comment by dbarzin** [comment]
Ne se reproduit pas avec Firefox et Chromium

**Comment by merlin-lepiaf** [comment]
😫 je viens de tester sous firefox 125.0.2 (mac), et je reproduis le même problème. 
Il ne se présente que pour la vue clusters :-(
J'ai supprimé manuellement mes clusters, puis ressaisis. Idem.
Je suis en local sur ma machine de dev, je vais essayer sur un autre serveur et je te dis. 👍🏿

**Comment by dbarzin** [comment]
Cela ne se produit pas avec la version actuelle. Peux-tu essayer la solution proposée ici : https://github.com/dbarzin/mercator/issues/743#issuecomment-2169132444
