### ISSUE TITLE
Vue Infrastructures Logiques - Certificats

### ISSUE THREAD

**Issue by merlin-lepiaf** [dbarzin/mercator#712]
Bonjour Didier, 
je ne retrouve pas la vue sur les certificats, tels que mentionnés dans le modèle. 
Est-elle prévue ? 
Cordialement,

-- 
RR

**Comment by dbarzin** [comment]
Dans la vue de l'infrastructure logique ?

**Comment by merlin-lepiaf** [comment]
oui, tout à fait. 
<img width="203" alt="image" src="https://github.com/dbarzin/mercator/assets/81599930/7844dd3e-38f0-406a-b979-d6a43ae999f1">

**Comment by dbarzin** [comment]
Il doit y avoir un problème de droits d'accès. Les certificats se trouvent en dessous des VLAN.
![image](https://github.com/dbarzin/mercator/assets/43208232/acc9c15b-7983-4848-bc37-0d936ec0add5)
