### ISSUE TITLE
Liens vue logique et la vue physique

### ISSUE THREAD

**Issue by dbarzin** [dbarzin/mercator#725]
Selon les directives de l'ANSSI, il est vraiment nécessaire de faire une séparation claire entre la vue logique et la vue physique. Dans la partie logique, nous devons inclure des éléments tels que l'adresse IP et les règles de filtrage, tandis que dans la partie physique, nous devons spécifier des détails tels que le modèle, la version et l'emplacement.

Et dans le cas où le switch est virtualisé, il devrait être possible de saisir son serveur physique dans la vue logique.

![Screenshot 2024-04-29 105022](https://github.com/dbarzin/mercator/assets/154766036/da92bc0d-b55d-4e55-87f6-6d06e3653ca3)

_Originally posted by @BadaouiMu in https://github.com/dbarzin/mercator/issues/649#issuecomment-2082199337_

**Comment by dbarzin** [comment]
C'est disponible ! 
https://github.com/dbarzin/mercator/pull/723

**Comment by BadaouiMu** [comment]
Merci beaucoup !
