### ISSUE TITLE
Erreur 500 / Vue Infra Physique / Bâtiments Salles

### ISSUE THREAD

**Issue by Aldujard1n** [dbarzin/mercator#726]
Bonjour Didier,

Nouvelle installation ce jour pour moi, et des erreurs 500 lors d'une modification d'un bâtiments /salles

![image](https://github.com/dbarzin/mercator/assets/170625876/4f8197d9-39e9-4140-a7b8-cc88f4e4d6cd)

![image](https://github.com/dbarzin/mercator/assets/170625876/3d17b92b-2b6e-474d-af6b-7ae2cc708d01)

Une idée sur la cause de cette panne ? elle ne semble pas ce produire sur toutes les pages

En tout cas merci pour cet outil :)

**Comment by dbarzin** [comment]
Merci, corrigé ici : https://github.com/dbarzin/mercator/pull/728

**Comment by Aldujard1n** [comment]
Je viens de lancer la MAJ et cela semble fonctionner sans anomalies (plusieurs créations et changements sans erreurs 500 pour le moment sur l'onglet "Sites")
merci beaucoup pour votre intervention !!!!
Puis-je remonter par ce même canal si je constate d'autres erreurs 500 ou il es préférable de créer un nouvel incident ?

Alex.

**Comment by dbarzin** [comment]
Tu peux faire un nouveau ticket pour chaque problème, c'est plus facile à suivre.
Merci,
Didier
