### ISSUE TITLE
Licence des images?

### ISSUE THREAD

**Issue by devnewton** [dbarzin/mercator#736]
Bonjour,

J'aurais aimé utiliser les images de ce projet https://github.com/dbarzin/mercator/tree/master/public/images pour faire une bibliothèque pour Draw.io ( https://github.com/jgraph/drawio-libs/tree/review ).

Quelle est la licence de ces images?

**Comment by dbarzin** [comment]
Je ne recommande pas d'utiliser ces icônes dans un autre projet.
Un nouveau jeu d'icône va être disponible prochainement qui sera sous licence GVPv3.

**Comment by dbarzin** [comment]
Les images disponibles maintenant sont sous licence GPLV3. Il est donc tout à fait autorisé de les utiliser les images de ce projet https://github.com/dbarzin/mercator/tree/master/public/images pour en faire une bibliothèque pour Draw.io ( https://github.com/jgraph/drawio-libs/tree/review ).
