### ISSUE TITLE
Install is with Ubuntu 20.04 - Composer not updated

### ISSUE THREAD

**Issue by Arnaud-Askee** [dbarzin/mercator#738]
Hi,
I've created a VM on azure (Linux (ubuntu 20.04)) and follow the installation procedure.

The process is stop with composer : 
In French procedure, the command : composer self-update does not exist

In both Fr / En procedure, the next steps composer update does not work (dependencies issue).

Then, the installation process can not continue (php artisan ... does not work).

Could you update the installation procedure ? 

Thanks a lot :)

**Comment by Arnaud-Askee** [comment]
FYI, procedure works very fine with ubuntu 22.04. 
(small mistake with french procedure : skip composer self-update step, just as En procedure)

The previous error was due to php 7 release (Instead if PHP 8 with ubuntu 22)

**Comment by dbarzin** [comment]
I will retest the installation in a new VM.
Thanks,
Didier

**Comment by Arnaud-Askee** [comment]
hi,
Just finished installation with 22.04.

In installation process, for https, 1 command is missing 
`sudo a2enmod ssl `

Should be added before apache configuration definition of <VirtualHost *:443>
In addition, with you sample, there is no value for ServerAdmin. It should be easier to have a default value. For exemple : 
```
<VirtualHost *:443>
ServerName yourdomain.com
ServerAdmin admin@yourdomain.com
...
</VirtualHost>
```

**Comment by dbarzin** [comment]
Merci, la procédure a été mise à jour
