### ISSUE TITLE
Ajout de sous-buildings

### ISSUE THREAD

**Issue by Melvin5858** [dbarzin/mercator#741]
Bonjour,

Il y aura t-il à l'avenir la possibilité d'ajouter un type d'objet entre le building et les équipements finaux (exemple : salles, étages...) ?

**Comment by dbarzin** [comment]
Il est recommandé d'implémenter une nomenclature structurée pour les locaux au sein de votre organisation. Par exemple : P1-32 peut signifier Paris - 1er étage - local 32. Cette méthode offre de nombreux avantages pour diverses applications, et pas uniquement pour les besoins informatiques.

En adoptant une telle nomenclature, il devient inutile d'ajouter un type d'objet intermédiaire entre le bâtiment et les équipements finaux (comme les salles ou les étages). Cela simplifie la gestion et l'identification des espaces de manière efficace et cohérente.

**Comment by Melvin5858** [comment]
D'accord, merci pour les informations. J'ai effectivement fait comme votre recommandation et j'en suis satisfait.
Bien à vous
