### ISSUE TITLE
Ajouter un objet utilisateur

### ISSUE THREAD

**Issue by dbarzin** [dbarzin/mercator#742]
Oui, l'idée serait de pouvoir ajouter un objet utilisateur. Ce dernier serait rattaché à un annuaire si ce n'est pas un compte local à une machine. L'objectif serait de pouvoir se mettre en conformité avec la [directive NIS](https://cyber.gouv.fr/la-directive-nis) (dont les règles de sécurité sont définies dans [l'arrêté du 14 septembre 2018](https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000037444012&dateTexte=&categorieLien=id)) et donc ici de constituer une liste des comptes disposant de droits d'accès privilégiés au système d'information (appelés «comptes privilégiés»). Cette liste préciserait pour chaque compte le niveau de droits et le type de compte (comptes utilisateur, compte de messagerie, compte de processus, etc).

Les différents attributs d'un objet utilisateur pourraient donc être :
- Nom
- Prénom
- Compte local (oui / non)
- Compte privilégié (oui / non)
- Type (compte utilisateur, compte de messagerie, compte de processus, etc)
- Description

_Originally posted by @mnotin in https://github.com/dbarzin/mercator/discussions/731#discussioncomment-9571590_

**Comment by dbarzin** [comment]
En cours: https://github.com/dbarzin/mercator/commit/483109d22ff0a6a50b387d440abd46a619336e6f

**Comment by dbarzin** [comment]
C'est disponible !

**Comment by mnotin** [comment]
Merci beaucoup pour tout le travail réalisé sur cette fonctionnalité.
Je viens de mettre à jour Mercator mais je ne trouve pas comment ajouter un utilisateur à un domaine AD. Je ne cherche probablement pas au bon endroit, pourriez-vous m'indiquer la démarche à suivre pour en ajouter un s'il vous plaît ?

**Comment by dbarzin** [comment]
Dans la vue de l'administration, il y a une nouvelle entrée "Administrateur" :

![image](https://github.com/dbarzin/mercator/assets/43208232/88b708e9-c51f-4e79-9d4c-a6a642450538)

Les administrateurs sont présentas dans la vue arborescente :

![image](https://github.com/dbarzin/mercator/assets/43208232/9323ac65-9ccc-4b06-8153-2eaefc753da5)

**Comment by mnotin** [comment]
D'accord merci. J'ai bien mis à jour l'application mais je ne vois pas cette nouvelle section dans la vue d'administration. Faut-il exécuter des commandes en plus de celles présentes dans la procédure de mise à jour de Mercator ?

**Comment by dbarzin** [comment]
Vérifie que tu as les accès dans la partie rôles.

![image](https://github.com/dbarzin/mercator/assets/43208232/6da7debf-991a-42a2-9159-d6a8a41c7b53)

**Comment by mnotin** [comment]
Je ne peux plus modifier ou créer un rôle, je reçois une erreur "Undefined array key 'admin_user'".

**Comment by dbarzin** [comment]
J'ai fait une erreur dans une migration DB qui est montée en prod avant d'avoir été testé. Pour rétablir la situation, il faut annuler la migration 2024_06_03_165236_add_user avec cette commande :

    php artisan migrate:rollback

Il faudra éventuellement lancer cette commande deux fois afin d'annuler cette migration 

Puis la relancer la migration avec :

    php artisan migrate

**Comment by mnotin** [comment]
Merci, la procédure a effectivement corrigé le problème. Je peux désormais créer des objets administrateur.
Merci plus généralement pour tout le travail réalisé sur la fonctionnalité.
