### ISSUE TITLE
Date de mise à jour Application en erreur

### ISSUE THREAD

**Issue by psecheresse** [dbarzin/mercator#743]
Bonjour, dans la fiche Application, si je saisi la date de mise à jour, j'ai une erreur 500 lors de l'enregistrement de la fiche.
![image](https://github.com/dbarzin/mercator/assets/38957502/acccb15a-4f93-4460-a3b3-6d1ed556b991)

Dans le log, j'ai trouvé cela
![image](https://github.com/dbarzin/mercator/assets/38957502/a2ba5289-757f-4c46-b25e-e8bb837d18b0)
Mon installation a été faite hier sur Ubuntu suivant le manuel d'installation.

**Comment by dbarzin** [comment]
Cela a été corrigé il y a quelques semaines. Il faut mettre à jour Mercator.

**Comment by psecheresse** [comment]
J'ai fait un pull et ce qui va avec suivant la documentation sans noter de changement, toujours "500 server error". 
Est-ce qu'il faut passer sur la branche dev puisque mon installation est toute fraiche donc devrait fonctionner si la correction a été faite la semaine dernière (installation avant hier).

**Comment by pcano65** [comment]
idem pour moi.
Merci pour tout le boulot déjà fait !

**Comment by pcano65** [comment]
bonjour, 
voici le résultat :
+----------------------+--------------+------+-----+---------+----------------+
| Field                | Type         | Null | Key | Default | Extra          |
+----------------------+--------------+------+-----+---------+----------------+
| id                   | int unsigned | NO   | PRI | NULL    | auto_increment |
| name                 | varchar(255) | NO   | MUL | NULL    |                |
| description          | longtext     | YES  |     | NULL    |                |
| vendor               | varchar(255) | YES  |     | NULL    |                |
| product              | varchar(255) | YES  |     | NULL    |                |
| security_need_c      | int          | YES  |     | NULL    |                |
| responsible          | varchar(255) | YES  |     | NULL    |                |
| functional_referent  | varchar(255) | YES  |     | NULL    |                |
| type                 | varchar(255) | YES  |     | NULL    |                |
| technology           | varchar(255) | YES  |     | NULL    |                |
| external             | varchar(255) | YES  |     | NULL    |                |
| users                | varchar(255) | YES  |     | NULL    |                |
| editor               | varchar(255) | YES  |     | NULL    |                |
| created_at           | timestamp    | YES  |     | NULL    |                |
| updated_at           | timestamp    | YES  |     | NULL    |                |
| deleted_at           | timestamp    | YES  |     | NULL    |                |
| entity_resp_id       | int unsigned | YES  | MUL | NULL    |                |
| application_block_id | int unsigned | YES  | MUL | NULL    |                |
| documentation        | varchar(255) | YES  |     | NULL    |                |
| security_need_i      | int          | YES  |     | NULL    |                |
| security_need_a      | int          | YES  |     | NULL    |                |
| security_need_t      | int          | YES  |     | NULL    |                |
| version              | varchar(255) | YES  |     | NULL    |                |
| rto                  | int          | YES  |     | NULL    |                |
| rpo                  | int          | YES  |     | NULL    |                |
| install_date         | datetime     | YES  |     | NULL    |                |
| update_date          | datetime     | YES  |     | NULL    |                |
| attributes           | varchar(255) | YES  |     | NULL    |                |
| patching_frequency   | int          | YES  |     | NULL    |                |
| next_update          | date         | YES  |     | NULL    |                |
+----------------------+--------------+------+-----+---------+----------------+

**Comment by dbarzin** [comment]
Merci, ce n'est déjà pas lié à une migration de la base de données.

Pouvez-vous m'envoyer une capture de l'écran de modification d'une application juste après avoir changé la date de mise à jour, mais juste avant avoir envoyé le formulaire, ainsi que le log complet de l'erreur : soit sur l'écran, soit dans le fichier `storage/logs/laravel.log`.

**Comment by pcano65** [comment]
![Capture d’écran 2024-06-06 122133](https://github.com/dbarzin/mercator/assets/8719556/ce4e1a27-e9d9-4a03-8f31-006d55f395fa)
[laravel.log](https://github.com/user-attachments/files/15613571/laravel.log)
Voici la capture et les log.
A priori je n'ai l'erreur que sur ce champs là. 
Sur le champs "date d'installation" de l'application, je n'ai pas d'erreur.

**Comment by dbarzin** [comment]
Impossible de reproduire dans l'environnement de test.
Il me faudrait plus d'information sur votre environnement :
- Nom de l'OS et version 
- Base de données et version
- Version de PHP

**Comment by psecheresse** [comment]
Les informations de pcano65 sont exactement les même que pour mon système.

Voici les versions :
* ubuntu : 24.04 LTS (GNU/Linux 6.8.0-35-generic x86_64)
* mysql : 8.0.36-2ubuntu3
* PHP : PHP 8.3.6 (cli) (built: Apr 15 2024 19:21:47)

**Comment by dbarzin** [comment]
Merci pour les informations, je vais essayer de reproduire le bug.

**Comment by dbarzin** [comment]
Je viens de réinstaller Mercator dans une VM et le problème ne se reproduit pas. Je soupçonne que c'est un problème de cache PHP, et que tu utilises du code qui a été modifié depuis. Peux-tu essayer récupérer une nouvelle version de Mercator :

Tu peux d'abords essayer de vider la cache avec ;

    php artisan optimize:clear

Si cela ne fonctionne pas, déplacer l'installation actuelle :

    cd /var/www
    mv mercator mercator.old

Cloner le projet

    git clone https://www.github.com/dbarzin/mercator

Installer les librairies

    cd /var/www/mercator
    composer self-update
    composer update
    php artisan vendor:publish --all

Copier la configuration

    cp ../mercator.old/.env .

Générer la clé de l'application

    php artisan key:generate

Puis refaire des tests

Si tout fonctionne, tu peux supprimer le répertoire /var/www/mercator.old

**Comment by psecheresse** [comment]
Désolé, j'ai essayé mais déjà, le 1er problème est que composer self-update émet l'erreur `Command "self-update" is not defined`.
Ensuite j'ai eu des problèmes de répertoire storage/logs inexistant donc plantage au niveau d'Apache. J'ai essayé de bidouiller mais j'ai rencontré des problèmes de droits. A la fin, plus rien ne fonctionne. Je pense que ce sera plus simple que je refasse une nouvelle VM. Je vais essayer lorsque j'aurais du temps.
Merci en tout cas de tout le temps déjà apporté.

**Comment by psecheresse** [comment]
Bonjour, j'ai refait l'installation à partir d'une VM vierge et j'ai le même problème. C'est toujours le message d'erreur de timezone concerne le champ install_date (alors que c'est la date de modification qui est saisie).

**Comment by dbarzin** [comment]
@BadaouiMu Pourrais-tu regarder ce point ? Je ne trouve pas ce qui cause ce problème.

**Comment by dbarzin** [comment]
Merci à @BadaouiMu d'avoir amélioré les logs : https://github.com/dbarzin/mercator/pull/775
Peux-tu mettre à jour la Mercator, refaire un test et poster les logs ?

**Comment by dbarzin** [comment]
Est-ce que le problème est toujours présent ?
