### ISSUE TITLE
Comportement LDAP / Mercator

### ISSUE THREAD

**Issue by victorgyt** [dbarzin/mercator#744]
Bonjour, 

Actuellement, la communication entre le service Mercator et LDAP sont en clair. Nous aimerons chiffrer ce flux LDAPs dans le but de sécuriser ces authentifications. 
Comment pouvons nous le réaliser? 
Merci

Cordialement 

VG

**Comment by dbarzin** [comment]
C'est possible, il faut aller voir dans la documentation de [LdapRecord](https://ldaprecord.com/docs/laravel/v2/configuration/#using-an-environment-file-env).

**Comment by kuroboshi** [comment]
Pour ma part, j'ai importé le certificat de mon DC dans le serveur linux puis ajouté ceci dans /etc/ldap/ldap.conf :
```
TLS_CACERT /etc/ssl/certs/DC.cer
TLS_CACERTDIR /etc/ssl/certs
TLS_REQCERT ALLOW
```

Et dans le fichier .env, j'ai ceci :
```
LDAP_TYPE="AD"
LDAP_LOGGING=true
LDAP_CONNECTION=default
LDAP_HOST=DC.local.it
LDAP_USERNAME="CN=svc_mercator,OU=CPT2Svc,OU=LOCAL,DC=LOCAL,DC=it"
LDAP_PASSWORD=Motdepass
LDAP_PORT=636
LDAP_BASE_DN="OU=Utilisateurs,OU=LOCAL,DC=LOCAL,DC=it"
LDAP_TIMEOUT=5
LDAP_SSL=true
LDAP_TLS=false
LDAP_SCOPE="OU=Utilisateurs,OU=LOCAL,DC=LOCAL,DC=it"
```
On peut tester la validité de la configuration depuis le dossier d'installation mercator avec cette commande
`php artisan ldap:test`
