### ISSUE TITLE
erreur lors mise a jour

### ISSUE THREAD

**Issue by webchl** [dbarzin/mercator#762]
Bonjour,
je ne peux pas faire de mise a jour de la solution
une idée:

`root@INF04-VMERCA-P1:/var/www/mercator# git pull
warning: redirection vers https://github.com/dbarzin/mercator.git/
Mise à jour e1b51738..111b17fd
error: Vos modifications locales aux fichiers suivants seraient écrasées par la fusion :
        .env.example
        .github/workflows/ci.yaml
        .gitignore
        Dockerfile
        INSTALL.fr.md
        INSTALL.md
        README.fr.md
        README.md
        ROADMAP.md
        app/Activity.php
        app/Actor.php
        app/Annuaire.php
        app/ApplicationBlock.php
        app/ApplicationModule.php
        app/ApplicationService.php
        app/AuditLog.php
        app/Building.php
        app/Certificate.php
        app/Cluster.php
        app/DataProcessing.php
        app/Database.php
        app/DhcpServer.php
        app/Dnsserver.php
        app/DomaineAd.php
        app/Entity.php
        app/ExternalConnectedEntity.php
        app/Flux.php
        app/ForestAd.php
        app/Gateway.php
        app/Http/Controllers/API/ActivityController.php
        app/Http/Controllers/API/ActorController.php
        app/Http/Controllers/API/AnnuaireController.php
        app/Http/Controllers/API/ApplicationBlockController.php
        app/Http/Controllers/API/ApplicationModuleController.php
        app/Http/Controllers/API/ApplicationServiceController.php
        app/Http/Controllers/API/BayController.php
        app/Http/Controllers/API/BuildingController.php
        app/Http/Controllers/API/CertificateController.php
        app/Http/Controllers/API/DatabaseController.php
        app/Http/Controllers/API/DhcpServerController.php
        app/Http/Controllers/API/DnsserverController.php
        app/Http/Controllers/API/DomaineAdController.php
        app/Http/Controllers/API/EntityController.php
        app/Http/Controllers/API/ExternalConnectedEntityController.php
        app/Http/Controllers/API/FluxController.php
        app/Http/Controllers/API/ForestAdController.php
        app/Http/Controllers/API/GatewayController.php
        app/Http/Controllers/API/InformationController.php
        app/Http/Controllers/API/LanController.php
        app/Http/Controllers/API/LogicalServerController.php
        app/Http/Controllers/API/MacroProcessusController.php
        app/Http/Controllers/API/ManController.php
        app/Http/Controllers/API/NetworkController.php
        app/Http/Controllers/API/NetworkSwitchController.php
        app/Http/Controllers/API/OperationController.php
        app/Http/Controllers/API/PeripheralController.php
        app/Http/Controllers/API/PhoneController.php
        app/Http/Controllers/API/PhysicalRouterController.php
        app/Http/Controllers/API/PhysicalSecurityDeviceController.php
        app/Http/Controllers/API/PhysicalServerController.php
        app/Http/Controllers/API/PhysicalSwitchController.php
        app/Http/Controllers/API/ProcessController.php
        app/Http/Controllers/API/RouterController.php
        app/Http/Controllers/API/SecurityDeviceController.php
        app/Http/Controllers/API/SiteController.php
        app/Http/Controllers/API/StorageDeviceController.php
        app/Http/Controllers/API/SubnetworkController.php
        app/Http/Controllers/API/TaskController.php
        app/Http/Controllers/API/UserController.php
        app/Http/Controllers/API/VlanController.php
        app/Http/Controllers/API/WanController.php
        app/Http/Controllers/API/WifiTerminalController.php
        app/Http/Controllers/API/WorkstationController.php
        app/Http/Controllers/API/ZoneAdminController.php
        app/Http/Controllers/Admin/ActivityController.php
        app/Http/Controllers/Admin/BuildingController.php
        app/Http/Controllers/Admin/CartographyController.php
        app/Http/Controllers/Admin/DataProcessingController.php
        app/Http/Controllers/Admin/DomaineAdController.php
        app/Http/Controllers/Admin/EntityController.php
        app/Http/Controllers/Admin/ExplorerController.php
        app/Http/Controllers/Admin/GlobalSearchController.php
        app/Http/Controllers/Admin/HomeController.php
        app/Http/Controllers/Admin/InformationController.php
        app/Http/Controllers/Admin/LogicalServerController.php
        app/Http/Controllers/Admin/MApplicationController.php
        app/Http/Controllers/Admin/MApplicationLogController.php
        app/Http/Controllers/Admin/MacroProcessusController.php
        app/Http/Controllers/Admin/NetworkSwitchController.php
        app/Http/Controllers/Admin/OperationController.php
        app/Http/Controllers/Admin/PatchingController.php
        app/Http/Controllers/Admin/PhysicalLinkController.php
        app/Http/Controllers/Admin/PhysicalRouterController.php
        app/Http/Controllers/Admin/PhysicalServerController.php
        app/Http/Controllers/Admin/PhysicalSwitchController.php
        app/Http/Controllers/Admin/ProcessController.php
        app/Http/Co
Abandon
`

merci

**Comment by dbarzin** [comment]
Il semble que tu aies involontairement modifié des fichiers locaux. Pour récupérer les sources et écraser les modifications locales, il faut exécuter ces commandes : 

    git fetch
    git reset --hard HEAD
    git merge origin/master  

source : https://www.freecodecamp.org/news/git-pull-force-how-to-overwrite-local-changes-with-git/

**Comment by webchl** [comment]
top merci cela fonctionne 
commandes saisies en root:
```
cd /var/www/mercator
git fetch
git reset --hard HEAD
git merge origin/master  
git pull
php artisan migrate
composer update
git pull
```

Merci
