### ISSUE TITLE
[ENHANCEMENT] Modifications pour le support de postgreSQL dans mercator

### ISSUE THREAD

**Issue by MCF241** [dbarzin/mercator#764]
Tout d'abords merci pour cette application.

Le support de postgresql est de plus en plus simple 👍 

Il manque toutefois le support de postgres directement dans la Dockerfile. Pourrai-t-on ajouter les elements manquants 👍 

1. postgresql-dev postgresql-client dans **# system deps** (postgresql-dev semble mandatory pour le support de la commande **_docker-php-ext-install_**)
`RUN apk add postgresql-dev postgresql-client`
2. ajouter **pdo_pgsql** dans la section **# Install PHP extensions**
`RUN docker-php-ext-install gd zip ldap pdo pdo_mysql pdo_pgsql`

Avec cela la command `docker compose up -d --build` fonctionne correctement à partir du repertoire **docker**.
non tester à partir du repertoire **docker-compose**

**Comment by dbarzin** [comment]
Cela sera fait rapidement.

**Comment by MCF241** [comment]
Super merci

**Comment by dbarzin** [comment]
C'est fait : https://github.com/dbarzin/mercator/pull/783
