### ISSUE TITLE
Flux - Règles firewall

### ISSUE THREAD

**Issue by salleman33** [dbarzin/mercator#765]
Bonjour, 

Merci pour cet outil très utile ! 
Dans la documentation, je lis ici https://dbarzin.github.io/mercator/model/#flux qui ne faut pas utiliser les flux pour les règles de filtrages de firewall. Que conseillez-vous à la place ?

**Comment by dbarzin** [comment]
Je vous conseille de ne répertorier que les flux essentiels, car vous risquez de vous devoir répertorier plusieurs centaines (milliers) de règles de filtrage firewall.
