### ISSUE TITLE
erreur lors de la mise à jour

### ISSUE THREAD

**Issue by lynch4fr** [dbarzin/mercator#766]
Bonjour,
Je n'avais jamais mis à jour Mercator depuis sa premiere installation :
J'ai suivi la procedure "Update" pour faire une mise à jour qui n'a pas bien fonctionnée sur ma version (J'ai mon backup de DB _mercator_backup.sql_
J'ai donc appliqué la procedure "Repair the problems of migration" (J'ai bien mes 2 backups de DB _backup_mercator_data.sql_ et _backup_mercator_users.sql_) et l'import s'arrete sur le message suivant :
`sudo mysql mercator < backup_mercator_data.sql`
`'ERROR 1054 (42S22) at line 1043927: Unknown column 'identifiant' in 'field list'`

Comment puis je corriger ou poursuivre l'import ? Merci

Voici le contenu de la ligne 1043927 dans le  -- Dumping data for table processes --
`INSERT INTO `processes` (`id`, `identifiant`, `description`, `owner`, `security_need_c`, `in_out`, `dummy`, `created_at`, `updated_at`, `deleted_at`, `macroprocess_id`, `security_need_i`, `security_need_a`, `security_need_t`) VALUES (1,'GIP','<p>GIP: Impression, photocopie et numerisation</p>',NULL,NULL,NULL,NULL,'2023-12-22 13:09:22','2024-01-09 13:34:17',NULL,8,NULL,NULL,NULL),
`

**Comment by dbarzin** [comment]
Cette erreur provient du fait que vous essayez d'importer une version de la base de données dans une autre version de celle-ci.
Avez-vous toujours un full backup de la VM ? Est-il possible d'essayer de corriger le problème de mise à jour d'origine ?

**Comment by lynch4fr** [comment]
Merci pour votre aide, en effet je viens de comprendre l'erreur  et je viens de corriger 3 differences entre les 2 versions de BD (directement dans le fichier backup.sql :

- ERROR 1054 (42S22) at line 1043927: Unknown column 'identifiant' in 'field list
- ERROR 1054 (42S22) at line 1043927: Unknown column 'dummy' in 'field list'
- ERROR 1054 (42S22) at line 1044156: Unknown column 'nom' in 'field list'

Le tout semble bien refonctionner
Merci !!! :-)
