### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by Arnaud-Askee** [dbarzin/mercator#767]
I'd like to be able to customize icons.
For example, for application view, I'd like to see "SAP" or "SALESFORCE" icon (Instead of standard default Icon).
It would be also interesting for Infrastructure level.

My 2 cents,
Arnaud

**Comment by dbarzin** [comment]
This in now on the short term roadmap.

**Comment by dbarzin** [comment]
:tada: This is now available for applications and soon for entities, sites, workstations, peripherals and administrators !

**Comment by dbarzin** [comment]
In place
