### ISSUE TITLE
Utiliser l'authentification LDAP

### ISSUE THREAD

**Issue by lynch4fr** [dbarzin/mercator#768]
Bonjour,
Je viens de rajouter l'authentification LDAP pour les utilisateurs et la connexion au LDAP est vérifiée "Successfully connected." par la commande ` php artisan ldap:test`

- Quel login faut il utiliser : l'adresse mail ou l'identifiant LDAP dont la forme est assez specifique à l'entreprise ?
- Comment le rôle de l'utilisateur est choisi ?

Pour le moment j'ai testé plusieurs combinaisons de login/password et j'ai le message " These identifiers are not recognized. "

Merci à vous
Cordialement

**Comment by dbarzin** [comment]
Il faut utiliser l'adresse mail et le mot de passe pour s'identifier.
L'utilisateur doit se trouver dans un des groupes configuré dans la variable LDAP_GROUPS
Voir ici : https://ldaprecord.com/docs/laravel/v2/configuration/#using-an-environment-file-env

**Comment by lynch4fr** [comment]
J'utilise donc bien mon email pour l'authentification qui ne fonctionne pas encore.
Mais jai des logs avec un message d'erreur que je ne comprends pas ?

_[2024-07-10 13:37:16] local.INFO: LDAP (ldap://ldap.prod.xxx.fr:389) - Operation: Search - Base DN: dc=ldap,dc=xxx,dc=fr - Filter: (&(objectclass=\74\6f\70)(objectclass=\70\65\72\73\6f\6e)(objectclass=\6f\72\67\61\6e\69\7a\61\74\69\6f\6e\61\6c\70\65\72\73\6f\6e)(objectclass=\69\6e\65\74\6f\72\67\70\65\72\73\6f\6e)(mail=\73\79\6c\76\61\69\6e\2e\61\6e\74\6f\69\6e\65\40\75\6e\69\76\2d\72\65\6e\6e\65\73\32\2e\66\72)) - Selected: (entryuuid,*) - Time Elapsed: 14.16  
[2024-07-10 13:37:16] local.INFO: User [nom_p] has been successfully discovered for authentication.  
[2024-07-10 13:37:16] local.INFO: Object with name [nom_p] is being synchronized.  
[2024-07-10 13:37:16] local.INFO: Object with name [nom_p] has been successfully synchronized.  
[2024-07-10 13:37:16] local.INFO: User [nom_p] is authenticating._  
**[2024-07-10 13:37:16] local.INFO: User [nom_p] was denied authentication because their model is soft-deleted.**  

Une idée de votre coté ? Merci ;)

**Comment by dbarzin** [comment]
Il semble que l'utilisateur est supprimé dans la DB. 
Peux-tu vérifier le champ deleted_at de cet utilisateur. 
Il devrait être null.

    php artisan db
    select * from users;

**Comment by lynch4fr** [comment]
Effectivement, j'avais encore le meme ancien utilisteur que j'avais supprimé pour ne pas faire un conflit.
Et ça marche bien maintenant !
Merci
