### ISSUE TITLE
Link SAAS application

### ISSUE THREAD

**Issue by b-keller** [dbarzin/mercator#776]
Hi,

For on-premise hosted applications, the current data model shows that applications can be linked to physical or logical servers, workstations or entities...

How do you recommend modeling the links between the information system and SAAS-hosted applications?

thx

**Comment by dbarzin** [comment]
When you are using a cloud based solution to host your applications, you are simply using someone else computer.
So you can create a cloud site with the physical and logical servers in it.

**Comment by dbarzin** [comment]
You may describe it as it :

- Site : HAL Datacenter
- Room : HAL Computer room
- Bay : HAL Main bay
- Server : HAL Physical Server

(Ref. : Space Odyssey)

**Comment by b-keller** [comment]
OK, I understand
thx

PS: sorry, I didn't see that Discussions was activated on this repository
