### ISSUE TITLE
IP poste de travail et affichage dans vue infrastructure logique

### ISSUE THREAD

**Issue by seb976** [dbarzin/mercator#796]
Bonjour,

j'ai une interrogation sur les IP renseignées dans les postes de travail, a quoi servent-elles ? Je ne vois pas les postes de travail dans la vue infrastructure logique. Serait-il possible de les ajouter ?

De la même manière, serait-il possible de rajouter un champ IP pour les périphériques et de les afficher dans la vue infrastructure logique. Dans mon cas, j'ai un réseau spécifique pour l'automatisme, donc j'aimerais faire apparaitre les périphériques rattachés à ce réseau.

Enfin, j'aimerais aussi faire apparaitre les bornes Wi-Fi dans la vue infrastructure logique, car il s'agit d'un point d'entrer dans le réseau.
Dans mon cas, j'utiliserais aussi les bornes Wi-Fi pour toutes les autres émissions sans fil.

merci.

**Comment by dbarzin** [comment]
Je pense qu'il s'agit de cette même amélioration : https://github.com/dbarzin/mercator/discussions/733

**Comment by seb976** [comment]
Oui effectivement, je n'avais pas vu que l'amélioration avait déjà été demandée.
