### ISSUE TITLE
Problème d'installation Docker

### ISSUE THREAD

**Issue by gqs** [dbarzin/mercator#8]
Bonjour,

OS : CentOS 7 (7.9.2009)
Docker : 20.10.6
docker-compose : 1.18.0-4

Plusieurs petits problèmes lors de l'installation sous Docker.

- docker-compose build : impossible sans changer la version dans `docker-compose.yml`,
- app et db : ne sont pas démarrés automatiquement,
- connexion : impossible de se connecter à l'application pas de compte "admin" et les commandes `php artisan admin:*` ne fonctionnent pas.

Merci.

**Comment by dbarzin** [comment]
Après vérification :
- essaye "docker-compose build" à la place à la place de "docker-compose build"
- app et db démarrent automatiquement après le lancement de la commande "docker-compose build"
- la commande "php artisan admin:* " ne doit pas être utilisée.
Essaye de suivre le README.md dans le répertoire docker
Testé sous Ubuntu 20.04 avec Docker-compose version 1.25.0

**Comment by dbarzin** [comment]
impossible de reproduire le problème.
