### ISSUE TITLE
Retour Erreur 500

### ISSUE THREAD

**Issue by Aldujard1n** [dbarzin/mercator#801]
Bonjour Didier,
Nouvelle installation sur un AlmaLinux et j'ai de nouveau l'erreur 500 dans le module Exploration.

L'installation date de hier et j'ai importés mon ancienne base SQL, toutes les données sont bien présentes mais impossible d'utiliser le module "Exploration". (les autres modules semblent OK)

J'ai suivi la correction de ce fix: dans le doute https://github.com/dbarzin/mercator/pull/567 et celui-ci https://github.com/dbarzin/mercator/pull/570

De mon côté:
-Le cache artisan à bien été purgé
- Ma version PHP
<img width="299" alt="image" src="https://github.com/user-attachments/assets/83be56b8-792b-4d54-a218-06e9691dd775">
-Apache2
<img width="331" alt="image" src="https://github.com/user-attachments/assets/bb90d1a7-dad4-4600-ab26-8674b1ff60f2">
Serait-ce lié aucun mods supplémentaire visible sur ma plateforme ?

J'ai tenté une installation de Mercator sur un Alma, je ne voyais pas trop de contrainte, il y'en à peut-être finalement, je n'avais de soucis sur une Ubuntu.

Merci à toi.

**Comment by dbarzin** [comment]
Est-ce que l'installation s'est bien passée ? As-tu eu des erreurs durant celle-ci ?
Y a-t-il des erreurs dans storage/logs/laravel.log ?

**Comment by Aldujard1n** [comment]
Oui l'installation c'est plutôt déroulés sans encombre (il a fallu adapter certaines commandes évidemment)
Mais j'ai une erreur récurrente dans mon Laravel.log

[2024-08-23 08:23:14] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'domain_id' in 'field list' (Connection: mysql, SQL: select `id`, `name`, `address_ip`, `cluster_id`, `domain_id` from `logical_servers`) {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'domain_id' in 'field list' (Connection: mysql, SQL: select `id`, `name`, `address_ip`, `cluster_id`, `domain_id` from `logical_servers`) at /var/www/mercator/vendor/laravel/framework/src/Illuminate/Database/Connection.php:829)
[stacktrace]

J'ai également dans Laravel:
[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'domain_id' in 'field list' at /var/www/mercator/vendor/laravel/framework/src/Illuminate/Database/Connection.php:423)

Un problème lié dans l'import de la base MySQL ?

**Comment by dbarzin** [comment]
Il semble que cette migration n'a pas été exécutée : 
database/migrations/2024_06_18_125723_link_domain_lservers.php

Peux-tu lancer cette commande : 

    php artisan migrate

et aussi

    php artisan db

puis :

    describe logical_servers;

et me donner les résultats de ces commandes.

**Comment by Aldujard1n** [comment]
[root@17SRVADM3 mercator]# php artisan migrate
PHP Fatal error:  Cannot declare class AddLdapColumnsToUsersTable, because the name is already in use in /var/www/mercator/database/migrations/2024_08_23_081607_add_ldap_columns_to_users_table.php on line 0

   Symfony\Component\ErrorHandler\Error\FatalError

  Cannot declare class AddLdapColumnsToUsersTable, because the name is already in use

  at database/migrations/2024_08_23_081607_add_ldap_columns_to_users_table.php:0
      1▕ <?php
      2▕
      3▕ use Illuminate\Support\Facades\DB;
      4▕ use Illuminate\Support\Facades\Schema;
      5▕ use Illuminate\Database\Schema\Blueprint;
      6▕ use Illuminate\Database\Migrations\Migration;
      7▕
      8▕ class AddLdapColumnsToUsersTable extends Migration
      9▕ {


   Whoops\Exception\ErrorException

  Cannot declare class AddLdapColumnsToUsersTable, because the name is already in use

  at database/migrations/2024_08_23_081607_add_ldap_columns_to_users_table.php:0
      1▕ <?php
      2▕
      3▕ use Illuminate\Support\Facades\DB;
      4▕ use Illuminate\Support\Facades\Schema;
      5▕ use Illuminate\Database\Schema\Blueprint;
      6▕ use Illuminate\Database\Migrations\Migration;
      7▕
      8▕ class AddLdapColumnsToUsersTable extends Migration
      9▕ {

      +1 vendor frames

  2   [internal]:0
      Whoops\Run::handleShutdown()

[root@17SRVADM3 mercator]# php artisan db
mysql: [Warning] Using a password on the command line interface can be insecure.
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 46
Server version: 8.0.36 Source distribution

Copyright (c) 2000, 2024, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
<img width="340" alt="image" src="https://github.com/user-attachments/assets/53385e21-d4df-46c7-b89e-b7b989e2bdfb">

**Comment by dbarzin** [comment]
I faut supprimer le fichier /var/www/mercator/database/migrations/2024_08_23_081607_add_ldap_columns_to_users_table.php
Puis relancer la migration avec

    php artisan migrate

et tout va rentrer dans l'ordre.

**Comment by Aldujard1n** [comment]
Super merci, cela fonctionne :) 

J'ai eu aussi cette anomalie 
<img width="844" alt="image" src="https://github.com/user-attachments/assets/438a9b6f-0fd4-41e5-b25e-67f4361563a0">

Que j'ai corrigé avec la même méthode que fournis précédemment, merci pour ta disponibilité.
