### ISSUE TITLE
Duplication des flux lors de l'exploration

### ISSUE THREAD

**Issue by Blemaire-ssi** [dbarzin/mercator#852]
En lançant une exploration, sur une application "A" qui a un flux "test" **vers** une application B, quand on double clique sur l'application B, le flux se retrouve dupliqué dans la représentation. Le même comportement survient lorsque on utilise la fonction "déployer"

Affichage initial des applications A et B:
![image](https://github.com/user-attachments/assets/9c13f8d8-8947-4e7c-b181-9203ee10aff3)

Après double clic sur B : 
![image](https://github.com/user-attachments/assets/7a999d41-0364-4c20-8b09-662215dbbf27)

**Comment by dbarzin** [comment]
As-tu bien déployé la dernière version de Mercator ?
Peux-tu poster une capture d'écran de la liste des flux logiques ?

**Comment by Blemaire-ssi** [comment]
En déployant la nouvelle version, le problème est en effet corrigé, désolé...
