### ISSUE TITLE
php artisan migrate : ErrorException 2024_09_24_044657_move_icons_to_docs

### ISSUE THREAD

**Issue by lynch4fr** [dbarzin/mercator#853]
Bonjour,

Comme tous les jours je fais une mise à jour de Mercator pour profiter de toutes les dernieres nouveautés merci !!!
Et aujourd'hui je me retrouve avec l'erreur ci dessous lors du lancement _"php artisan migrate "_ .

Concrètement dans l'interface GUI, je ne retrouve pas mes icones personalisés que j'ai mise en place et egalement une erreur _500:server error_ quand j'utilise l'outil d'exploration.

Merci d'avance.

-------------------
php artisan migrate

   INFO  Running migrations.  

  2024_09_24_044657_move_icons_to_docs .................................................................................................. 333ms FAIL

   ErrorException 

  file_put_contents(/var/www/mercator/storage/docs/1): Failed to open stream: No such file or directory

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:204
    200▕      * @return int|bool
    201▕      */
    202▕     public function put($path, $contents, $lock = false)
    203▕     {
  ➜ 204▕         return file_put_contents($path, $contents, $lock ? LOCK_EX : 0);
    205▕     }
    206▕ 
    207▕     /**
    208▕      * Write the contents of a file, replacing it atomically if it already exists.

      +2 vendor frames 

  3   database/migrations/2024_09_24_044657_move_icons_to_docs.php:45
      Illuminate\Support\Facades\Facade::__callStatic()
      +24 vendor frames 

  28  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by dbarzin** [comment]
Il faut créer le répertoire de stockage avec la commande : 

    php artisan storage:link

Cela devrait régler le problème.

**Comment by lynch4fr** [comment]
Je viens de creer le repertoire manquant. Maintenant il y a une nouvelle erreur lorsque je fais un "php artisan migrate"
-----------
  INFO  Running migrations.  

  2024_09_24_044657_move_icons_to_docs ................................................................................................... 13ms FAIL

   Illuminate\Database\QueryException 

  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'icon_id' (Connection: mysql, SQL: alter table `m_applications` add `icon_id` int unsigned null after `type`)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:829
    825▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    826▕                 );
    827▕             }
    828▕ 
  ➜ 829▕             throw new QueryException(
    830▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    831▕             );
    832▕         }
    833▕     }

      +9 vendor frames 

  10  database/migrations/2024_09_24_044657_move_icons_to_docs.php:19
      Illuminate\Support\Facades\Facade::__callStatic()
      +24 vendor frames 

  35  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by dbarzin** [comment]
La migration s'est partiellement exécutée et la création de la colonne icon_id a déjà été exécuté.
Il faut mettre cette ligne en commentaire puis exécuter la migration.
Cela va poser des problèmes lors du prochain `git pull`. Pour cela, il faut faire `git reset --hard origin/master` après la modification pour annuler la modification. 
Je vais mettre ce code en commentaire pour éviter les problèmes.

**Comment by lynch4fr** [comment]
Parfait, j'ai recuperé l'outil d'exploration et je n'ai plus d'erreur de migration.
_Je vais recharger mes icons personnalisées et les attribuer à mes applications, car elles ne sont plus disponible_
Merci
