### ISSUE TITLE
Création d'une Chart Helm

### ISSUE THREAD

**Issue by siddjellali** [dbarzin/mercator#864]
La création d'une chart Helm standardisée permettrait de faciliter le déploiement, l'intégration continue, et l'évolutivité du projet Mercator dans des environnements de production Kubernetes.

**Comment by dbarzin** [comment]
Merci pour la suggestion ! L'ajout d'une chart Helm pour Mercator est une excellente idée pour simplifier le déploiement et améliorer l'intégration continue dans Kubernetes. Nous l'ajoutons cette demande dans à la roadmap. Si quelqu'un maitrise ce sujet, c'est une excellente opportunité de devenir contributeur du projet. Référence : https://helm.sh/docs/topics/charts/

**Comment by siddjellali** [comment]
https://github.com/dbarzin/mercator/pull/905

**Comment by siddjellali** [comment]
https://github.com/dbarzin/mercator/pull/909
