### ISSUE TITLE
[SUGGESTION] Ajout de colonne IP dans la vue globale des périphériques physiques

### ISSUE THREAD

**Issue by victorgyt** [dbarzin/mercator#871]
Bonjour, 

Je suggère de rajouter une colonne "IP" dans la vue des informations des périphériques. Cette idée nous aiderait à prendre une capture d'écran et à mettre à jour notre documentation d'infrastructure. 
Actuellement il n'est pas possible d'avoir la colonne "IP" 

![image](https://github.com/user-attachments/assets/7ab4b1b1-b422-4577-872d-c2fee848b9d6)

**Comment by dbarzin** [comment]
Corrigé ici : https://github.com/dbarzin/mercator/pull/873
