### ISSUE TITLE
[ERREUR 500]  Vue logique infrastructure 

### ISSUE THREAD

**Issue by victorgyt** [dbarzin/mercator#872]
Bonjour, 
Quand je tente d'afficher les IP sur mercator, la page me retourne une erreur 500 : 

Je clique dessus 
![image](https://github.com/user-attachments/assets/a1e821ff-96d9-4d5a-b3f7-01665926b1d3)

La page se recharge et me retourne une erreur 500 
![image](https://github.com/user-attachments/assets/f21ad0ec-b1fc-464d-99e8-fe982f39214c)

Voici le debug

![image](https://github.com/user-attachments/assets/b4b0f1e5-4ed7-4394-853f-eb6efd78b37e)

![image](https://github.com/user-attachments/assets/cc04714f-901a-45a4-90df-ecaf89bf6939)

![image](https://github.com/user-attachments/assets/69dbeff3-7c85-4da1-ba6c-a35ae0b7eec4)

![image](https://github.com/user-attachments/assets/2f798d00-d78e-4bda-9320-531fce07070c)

![image](https://github.com/user-attachments/assets/175794ae-1279-4f5a-9833-a096af53dff0)

Merci pour votre aide ! 
Cordialement, 
VG

**Comment by dbarzin** [comment]
Corrigé ici : https://github.com/dbarzin/mercator/pull/873
