### ISSUE TITLE
Titre de colonne dans l'affichage d'une "Information"

### ISSUE THREAD

**Issue by flapvhd** [dbarzin/mercator#88]
Pas grand chose...

Juste un titre de colonne qui s'initialise à cruds.information.fields.process dans  l'affichage d'une "Information".

Merci encore pour cette magnifique application.

**Comment by dbarzin** [comment]
Corrigé !
Merci,
Didier

**Comment by flapvhd** [comment]
Merc Didier pour cette efficacité! ;-)
