### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by b-keller** [dbarzin/mercator#882]
Bonjour,

Nous avons constaté une différence entre l'heure de création et de modification affiché par exemple pour un Site et la valeur réelle dans la base de donnée. 

Je n'ai pas vérifié si le problème est présent pour d'autre type d'élément. 
Je n'ai pas vérifié non plus si le problème est présent aussi pour l'heure de suppression.

![CaptureEcran241004](https://github.com/user-attachments/assets/68d5b767-7e71-48b3-88ab-a5ad375fc9dd)

```
|id |name |description |created_at |updated_at |deleted_at|
|---|----------------------|----------------------|-----------------------|-----------------------|----------|
|58 |MySite|Mydescription|2024-07-26 16:43:41.000|2024-10-04 16:30:31.000| |
```

Un bug ?

Cordialement

**Comment by dbarzin** [comment]
Les dates de création et de modification sont différentes, cela me semble normal.

**Comment by b-keller** [comment]
sur la capture on voit "créé le" 16:**07** alors que dans la base de données 16:**43**:41.000
idem pour "modifié le" 16:**10**  et dans la base 16:**30**:31.000

**Comment by dbarzin** [comment]
Bien vu  ! C'est corrigé ici : https://github.com/dbarzin/mercator/pull/883
Double erreur : formatage de l'heure incorrect et mauvais timezone

**Comment by b-keller** [comment]
Super !

Merci
