### ISSUE TITLE
Audits Logs - Consultation via le menu

### ISSUE THREAD

**Issue by etienne-64** [dbarzin/mercator#89]
Bonjour,

Tout d'abord merci pour la réalisation de cette application qui peut largement couvrir le besoin de cartographie du SI pour une PME.

Je la découvre ce matin et je vois arriver le premier message d'erreur. 

Contexte: 
- utilisateur avec les rôle admin et cartographer
- sélection du menu "Audits Logs"

La page s'affiche avec un message d'erreur:

![image](https://user-images.githubusercontent.com/10651729/164970094-3dbe59d1-4792-4299-abc5-7ea6bf66c3c3.png)

Je poursuis ma découverte de Mercator.

**Comment by dbarzin** [comment]
Corrigé !
Merci,
Didier

**Comment by etienne-64** [comment]
C'est parfait. Merci.
