### ISSUE TITLE
[REQUEST/IDEA] Création d'objets médicaux

### ISSUE THREAD

**Issue by cartomedical** [dbarzin/mercator#894]
Bonjour Didier, 

Dans le cadre de la cartographie des systèmes d'information de nos laboratoires médico-techniques, nous aimerions modéliser les analyseurs médicaux (et les analyses qu'ils effectuent) en plus des différentes applications, postes de travail et serveurs que nous utilisons.

Or ces objets ("chaîne de laboratoire", "automate médical" et "analyse/tâche médicale") n'existent pas dans Mercator et nous trouverions très utile de les avoir afin d'avoir un lien direct avec ce que l'on souhaite modéliser.

Nous aimerions également garder la possibilité de lier ces analyseurs avec des applications (si ils en utilise une pour de l'envoi de résultats par exemple…), postes de travail (qui contrôle les analyseurs) et serveurs logiques.

Penses-tu possible l'ajout de ces objets dans Mercator ?

Merci d'avance.

**Comment by cartomedical** [comment]
Pour ajouter un peu plus d'informations, nous aimerions décrire une chaîne de laboratoire par son nom, sa description et les automates médicaux qu'elle comprend.

Un automate médical (s'il ne fait pas partie d'une chaîne) serait également décrit par un nom, une description, les tâches qu'il effectue ainsi que l'application qui lui est lié (s'il y en a une).

Enfin, la tâche serait décrite par un nom, une description et l'analyseur qui effectue cette tâche.

(Et comme énoncé dans le premier message, nous aimerions idéalement lier l'application à un poste de travail et à des serveurs logiques si nécessaire ; choses qui sont déjà possibles dans Mercator.)

Si tu as besoin d'autres d'informations ou de clarifications je serais ravi de te les apporter.

**Comment by dbarzin** [comment]
Vous pouvez cartographier vos automates comme des "postes de travail". Il est alors possible de spécifier le type ("automate") et les applications qui s'y trouvent. On pourra également bientôt changer l'icône pour chaque poste de travail, ce qui sera plus clair lors de l'exploration de la cartographie.

Concernant le second point, Mercator n'est pas encore bien adapté pour décrire des processus. C'est un changement majeur
qui va arriver dans les prochaines versions. Pour le moment, vous ne pouvez qu'en faire l'inventaire.

**Comment by dbarzin** [comment]
Il est maintenant possible de changer les icônes des postes de travail.

**Comment by wolicape** [comment]
Bonjour, 

Je me permet de rouvrir la demande car la proposition ne convient pas totalement dans ce cas de figure je trouve. Je rencontre une problématique similaire où l'on aimerait ajouter des automates programmables physiques dans la cartographie et les lier a des automates programmables logiques. Or on ne peut pas vraiment lier des postes de travail à un élément de la vue logique. 

Je pense que le meilleur compromis serait de les créer dans les serveurs physiques et logiques, où l'on peut faire le lien entre ces deux objets. Cependant, on ne peut pas modifier les icônes de ces éléments pour le moment. Est-ce réalisable que de permettre cette modification a minima ?

**Comment by dbarzin** [comment]
Merci pour cette précision, c’est une très bonne suggestion. En effet, permettre de représenter les automates physiques et logiques via les vues serveur, tout en personnalisant les icônes, est une solution souple et claire pour ce type de besoin.

C’est noté, cette amélioration sera implémentée dans le mois à venir. Je vous tiens au courant dès que c’est disponible. Merci encore pour votre retour constructif !

**Comment by dbarzin** [comment]
Cette amélioration est disponible !
