### ISSUE TITLE
Vue Infrastructure - MAN - Suppression multiple impossible

### ISSUE THREAD

**Issue by etienne-64** [dbarzin/mercator#90]
URL : /admin/mans

Si après sélection de plusieurs MAN, je souhaite les supprimer avec le bouton "delete selected items", le message d'avertissement s'affiche et si je choisis "OK", il ne se passe rien.

![image](https://user-images.githubusercontent.com/10651729/165103174-9be51916-4faf-4353-ba29-aa409a1420fa.png)

Après

![image](https://user-images.githubusercontent.com/10651729/165103307-dd1c8912-ad14-4d66-9991-3a4687ef3760.png)

En revanche, la suppression unitaire fonctionne correctement.

**Comment by dbarzin** [comment]
Corrigé ! Merci, Didier
