### ISSUE TITLE
Deploiement mercator php via subfolder et non subdomain

### ISSUE THREAD

**Issue by elkekou** [dbarzin/mercator#907]
Bonjour,
j'essaye de déployer mercator sur un serveur php, j'ai suivi les infos du readme, pour faire une install sans docker et directement avec php composer.... SI je reste sur une URL dédié via un hostname a mercator pas de soucis ca marche ex
http://mercator.domaine.fr  

En revanche si je veux passer par un subfolder ca coince : http://outils.domaine.fr/mercator 

Dès la première connexion je suis rediriger vers  http://outils.domaine.fr/login alors que ca devrait plutot etre https://outils.domaine.fr/mercator/login 

Je pense que j'ai du raté un truc quelque part pourtant dans le .env j'ai bien mis http://outils.domaine.fr/mercator 

Serveur : debian 12 php 8.2 et apache en frontal.

Conf apache : 

    DocumentRoot /var/www/
    <Directory /var/www/mercator>
        AllowOverride All
    </Directory>

Merci d'avance.

**Comment by dbarzin** [comment]
Cela n'a jamais été testé, mais cela doit être possible en standard avec Laravel.
Une solution va être trouvée et implémentée rapidement.

**Comment by dbarzin** [comment]
Voici un exemple de fichier de configuration Apache qui héberge plusieurs applications Laravel dans différents sous-répertoires sur le même serveur et domaine. Cela permet de gérer plusieurs applications sur une seule configuration.

### Exemple de fichier `.conf` avec plusieurs applications :

```apache
<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html

    # Application 1 - Hébergée dans le sous-répertoire /app1
    Alias /app1 /var/www/html/app1/public
    <Directory /var/www/html/app1/public>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted

        # Activer mod_rewrite et la redirection pour l'application 1
        RewriteEngine On
        RewriteBase /app1/
        RewriteRule ^index\.php$ - [L]
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . /app1/index.php [L]
    </Directory>

    # Application 2 - Hébergée dans le sous-répertoire /app2
    Alias /app2 /var/www/html/app2/public
    <Directory /var/www/html/app2/public>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted

        # Activer mod_rewrite et la redirection pour l'application 2
        RewriteEngine On
        RewriteBase /app2/
        RewriteRule ^index\.php$ - [L]
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . /app2/index.php [L]
    </Directory>

    # Application 3 - Hébergée dans le sous-répertoire /app3
    Alias /app3 /var/www/html/app3/public
    <Directory /var/www/html/app3/public>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted

        # Activer mod_rewrite et la redirection pour l'application 3
        RewriteEngine On
        RewriteBase /app3/
        RewriteRule ^index\.php$ - [L]
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule . /app3/index.php [L]
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

### Explications :
- **Alias** : Chaque application est hébergée dans un sous-répertoire (par exemple, `/app1`, `/app2`, etc.). Le chemin réel des fichiers de l'application est mappé à un alias dans le sous-répertoire.
  
- **RewriteEngine et RewriteRule** : Chaque application a ses propres règles de réécriture configurées directement dans le fichier `.conf` pour gérer la redirection vers `index.php` comme avec Laravel.

- **AllowOverride None** : L’utilisation des fichiers `.htaccess` est désactivée pour des raisons de performance et de sécurité, toutes les règles sont centralisées dans le fichier de configuration Apache.

### Étapes supplémentaires :
- **Activer les modules Apache nécessaires** (comme `mod_rewrite`) si cela n’a pas déjà été fait :
    ```bash
    sudo a2enmod rewrite
    sudo systemctl restart apache2
    ```

Avec cette configuration, tu peux héberger plusieurs applications Laravel dans des sous-répertoires différents tout en centralisant toute la configuration dans un seul fichier `.conf`.

**Comment by elkekou** [comment]
Super merci je vais essayer ca il me manquer quelque rewrite rules.
