### ISSUE TITLE
Vue infrastructure logique - Commutateur réseau - Mise à jour impossible

### ISSUE THREAD

**Issue by etienne-64** [dbarzin/mercator#91]
Path : /admin/network-switches

Aucune difficulté pour créer un switch. En revanche, si on souhaite mettre à jour des données, ça plante !

![image](https://user-images.githubusercontent.com/10651729/165110289-75e325b3-46dd-4228-ad3f-45b72f1abf9c.png)

**Comment by dbarzin** [comment]
Corrigé ! Merci, Didier

**Comment by etienne-64** [comment]
Super.
