### ISSUE TITLE
bug : "Undefined variable $site"

### ISSUE THREAD

**Issue by PhilippeAccorsi** [dbarzin/mercator#919]
I seen this error each time I add a `workstations`.

![Screenshot 2024-10-27 at 16-14-05 Mercator](https://github.com/user-attachments/assets/50cf94f1-4bb7-4338-a74d-12ea006c34a2)

If I come back, I seen my form. If I click on save button, I seen "name a déjà été pris. ", and if I come back in menu, I can seen my new workstation with all value.

An idea?

Regards,

**Comment by dbarzin** [comment]
Corrigé https://github.com/dbarzin/mercator/pull/922

**Comment by PhilippeAccorsi** [comment]
Merci
