### ISSUE TITLE
Fonctionnalité - Création d'équipement - Clonage

### ISSUE THREAD

**Issue by etienne-64** [dbarzin/mercator#92]
Lors de la création de la cartographie et peut-être à l'occasion de sa mise à jour, on est amené à créer plusieurs fois le même élément (serveurs, routeurs, switch ...), l'option "cloner" pourrait être un plus.

**Comment by dbarzin** [comment]
Le besoin est compréhensible mais les interfaces sont déjà fort chargées.
Il est possible d'utiliser l'API REST ou d'accéder directement à la base de données : 
https://github.com/dbarzin/mercator/issues/41

**Comment by etienne-64** [comment]
Oui, effectivement. 
La question que je me pose, c'est quand on part de rien ou presque (postes de travail dans GLPI, le reste dans des fichiers disparates), quelle est la solution la plus efficace: fichiers + routine pour charger dans l'appli via l'API ou saisie dans l'application au fil de l'eau avec une fonction telle que "cloner" ?

**Comment by dbarzin** [comment]
Comme nous partions de fichiers Excel, nous avons générer les commandes SQL correspondantes pour alimenter la cartographie.

**Comment by dbarzin** [comment]
Il existe une RESP API dans Mercator qui permettrait de synchroniser Mercator avec une autre source de données.

**Comment by dbarzin** [comment]
:tada: Le clonage est disponible pour les postes de travail, les périphériques, les sites, les salles, les baies, les serveurs physiques, les routeurs, le switchs...
