### ISSUE TITLE
Feat: not close sidebar menu when create something

### ISSUE THREAD

**Issue by PhilippeAccorsi** [dbarzin/mercator#920]
## At present

We use the sidebar to navigate in all menu. When we want to create something, we click on `Ajouter Bloc applicatif` and at this moment, the sidebar menu is closed.

If we not want to create entry, we don't have menu where we can click again on `Blocs applicatif` to open the list.

[feat_not_close_sidebar_menu.webm](https://github.com/user-attachments/assets/0d74cf5b-1dd9-4876-94f4-6d24ab7fade1)

## Expected

- [ ] menu stay open when we click on `Ajouter Bloc applicatif`

**Comment by dbarzin** [comment]
This need to upgrade to [Bootstrap version 5.3](https://getbootstrap.com). It has been added to the roadmap.

**Comment by dbarzin** [comment]
Done !

**Comment by PhilippeAccorsi** [comment]
Merci ça marche nickel.
