### ISSUE TITLE
[Enhancement] VLAN IDs

### ISSUE THREAD

**Issue by ggs67** [dbarzin/mercator#935]
If its not me missing something somewhere, I miss the ability to assign a VLAN ID (1...4095) to each VLAN which is quite critical data

**Comment by dbarzin** [comment]
For now, users have put the VLAN ID in the VLAN Name (ex: VLAN_42). 
But we should clearly add a VLAN ID field in that table.

**Comment by ggs67** [comment]
Unfortunately we have long organizes (tokenized) VLan names which get too long with the ID added (maybe even otherwise). There are some I could shorten in the import process, but it is not possible for others.

I guess the maximum length is 32 characters ? Would be possibly to increase this to 64 ? For VLans now, possibly for all entities later as well ?

**Comment by ggs67** [comment]
Sorry for bothering, but I would like to know if the change was implemented in one of the recent commits as I don't see this change explicitly as commit. I am waiting for this change before updating mercator.

**Comment by dbarzin** [comment]
It is available in the commits of this weekend. See here : https://github.com/dbarzin/mercator/pull/938/commits/136f15d42a733bc79b6058ea70a7593291dffb2a

**Comment by ggs67** [comment]
Thank you, works like a charm :-)
