### ISSUE TITLE
Impossible de mettre à jour Mercator

### ISSUE THREAD

**Issue by victorgyt** [dbarzin/mercator#937]
Bonjour, 
J'ai tenté de mettre à jour Mercator ce matin, malheureusement il est impossible de réaliser cette mise à jour, cf la capture d'écran

J'ai tenté de faire reboot et de mettre à jour le serveur, cela n'a pas fonctionné. Pouvez vous nous aider ? 

![image](https://github.com/user-attachments/assets/eb8fc5a5-5478-4f05-bf4e-c800c877a10c)

Merci 
Cordialement

**Comment by dbarzin** [comment]
Essaye : 

    rm composer.lock

et refait 

    git pull

puis

    composer update

**Comment by victorgyt** [comment]
Bonjour, 
Merci pour votre retour extrêmement rapide, 

Les deux premières commandes ont fonctionné avec succès, la dernière "composer update" me retour une erreur : 


![image](https://github.com/user-attachments/assets/43051e33-1b66-4b65-b130-5a8f33a82519)

Pouvez vous nous aider ? 
Merci.

**Comment by agentcobra** [comment]
L'erreur indique que votre version PHP (8.1) n'est pas suffisante pour la mise à jour de Laravel (qui est utilisé dans mercator).
Il faut mettre à jour votre version de PHP à 8.2 minimum.

**Comment by dbarzin** [comment]
On est passé sur Laravel 11 qui nécessite PHP 8.2

**Comment by victorgyt** [comment]
Rebonjour, 
Après avoir mis à jour PHP, et réalisé les updates, cela a été corrigé et refonctionne. 
Merci !
