### ISSUE TITLE
Unable to link logical-server to physical-server via "servers[]" through API

### ISSUE THREAD

**Issue by ggs67** [dbarzin/mercator#951]
I use the API to create our assets and try to link logical-servers to physical-servers which is a n-m relation.  I do this in accordance with the code through the "servers[]" json attribute. A dd() in the Mercator code shows that the attribute is well arriving in the method and a second test with a dd() inside the "if" clause which checks for "servers[]" confirms that the if actually recognizes the attribute. Nevertheless the link table stays empty and no error returned. 

I have verified that the physical server with ID 4 as passed via "servers[]" : [ 4 ] actually exists

**Comment by ggs67** [comment]
I did exactly this but in the initial POST (i.e. create). The code suggests to me that this should work as well. Nevertheless I changed my code to attempt an update via PUT after the create:

The PUT to the URL below returns status code 200, but the physical servers remain empty (physical server with id 4 exists)

URL: https://mercator.oursite.net/api/logical-servers/1480

data (some fields edited or masked:

{'id': 1480, 
'name': 'xx-1234xxx123', 
'description': '<ul><li><b>Role:</b> some text</li>', 
'net_services': None, 
'configuration': '<ul>
<li><b>Power state:</b> poweredOn</li>
<li><b>Protected  :</b> Yes</li>', 
'created_at': '2024-11-12', 
'updated_at': '2024-11-12', 
'deleted_at': None, 
'operating_system': 'Red Hat Enterprise Linux', 
'address_ip': '192.168.xx.xx', 
'cpu': 4, 
'memory': '8 GB', 
'environment': 'Integration', 
'disk': 95, 
'disk_used': None, 
'install_date': None, 
'update_date': None, 
'attributes': None, 
'patching_frequency': None, 
'next_update': None, 
'cluster_id': 2, 
'domain_id': None, 
'servers[]': [4]
}

**Comment by dbarzin** [comment]
I might have fixed a bug in the API.
Didoer

Le mar. 12 nov. 2024, 10:56, Gaston Gloesener ***@***.***> a
écrit :

**Comment by ggs67** [comment]
Thank you. Works now ! 

You changed the API not to use [] anymore, so the code above needs to be changed to: 

`data['servers'] = [ "1", "2", "3" ]`

and it works as well in POST than in PUT
