### ISSUE TITLE
Erreur apres update :  Vue infra logique = 500 Server Error 

### ISSUE THREAD

**Issue by lynch4fr** [dbarzin/mercator#961]
J'ai fais un _git pull, composer update et php artisan migrate_ ce matin et je viens de perdre la Vue "Infrastructure logique" ? C'est l'URL [http://mercator.xxx.fr:8000/admin/report/logical_infrastructure]

- Le message d'erreur:  500 Serve Error
- Log php  artisan:  2024-11-14 15:02:54 ................................................................................................. ~ 500.60ms et rien de plus, aucun appel /css/ ou /js/ ?

Encore merci

**Comment by dbarzin** [comment]
Avez-vous vider le cache 

    php artisan optimize:clear
 
Pouvez-vous me donner l'erreur qui se trouve dans storage/logs/laravel.log ?

**Comment by lynch4fr** [comment]
Il me semble ne pas avoir rencontré d'erreur et j'ai aussi fait un _php artisan config:clear && php artisan view:clear_ apres la migration.

`[2024-11-14 16:37:28] local.ERROR: Unclosed '(' does not match '}' (View: /var/www/mercator/resources/views/admin/reports/logical_infrastructure.blade.php) {"userId":2,"exception":"[object] (Illuminate\\View\\ViewException(code: 0): Unclosed '(' does not match '}' (View: /var/www/mercator/resources/views/admin/reports/logical_infrastructure.blade.php) at /var/www/mercator/storage/framework/views/1deb36e6d4a413851431c169d8941736.php:521)
[stacktrace]
#0 /var/www/mercator/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(60): Illuminate\\View\\Engines\\CompilerEngine->handleViewException()..........
#53 /var/www/mercator/server.php(21): require_once('...')
#54 {main}
`

`
[previous exception] [object] (ParseError(code: 0): Unclosed '(' does not match '}' at /var/www/mercator/storage/framework/views/1deb36e6d4a413851431c169d8941736.php:521)
[stacktrace]
#0 /var/www/mercator/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#1 /var/www/mercator/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire().......
#54 /var/www/mercator/server.php(21): require_once('...')
#55 {main}
"} 
`

**Comment by dbarzin** [comment]
OK, corrigé
