### ISSUE TITLE
Problème de suppression source/cible d'un flux dans le cas de services

### ISSUE THREAD

**Issue by cpages175** [dbarzin/mercator#964]
Bonjour,

Tout d'abord, je tenais à vous remercier pour tout ce travail autour de Mercator. 
Nous montons actuellement en charge avec l'application qui répond largement à nos besoins actuels !

Nous venons de constater un problème sur la page d'édition d'un flux lorsque celui-ci comporte en source et/ou en cible un service.

Au chargement du formulaire d'édition, le lien n'est pas établi avec le service, et la zone apparaît alors vierge. La validation de la page conduit alors à la perte, selon les cas, de l'émetteur et/ou du destinataire du flux.

Après avoir regardé le code sous-jacent, il semblerait que le problème proviennent du module "mercator/app/Flux.php" dans lequel il faut remplacer "SERV" par "SRV" au niveau de la liste des objets candidats. (ligne 56 et ligne 76).

Cette modification semble avoir résolu le problème dans notre contexte.

Bien cordialement

**Comment by dbarzin** [comment]
Merci, c'est corrigé ici : https://github.com/dbarzin/mercator/pull/965/files
