### ISSUE TITLE
Bug affichage Vue Ecosysteme->Entités : Externe à l'organisme

### ISSUE THREAD

**Issue by lynch4fr** [dbarzin/mercator#985]
Bonjour,
Nous remarquons, l'affichage d'un "Oui"  dans le champs "Externe à l'organisme" alors que bouton n'est pas activée.
Par contre il n'y a pas l'erreur dans "Entité liste"
Merci d'avance 

![image](https://github.com/user-attachments/assets/2dd76e85-689e-4cc4-9092-df9782a61cc3)
![image](https://github.com/user-attachments/assets/31c4b668-c8a5-445a-bd2b-e625ada018a2)
![image](https://github.com/user-attachments/assets/cccf7bcd-1b65-4c36-9e4f-82dcf1e78c2c)

**Comment by dbarzin** [comment]
Ce bug a été corrigé il y a plusieurs semaines. Veuillez mettre votre application à jour.

**Comment by lynch4fr** [comment]
Mince, je ne comprends pas, j'ai pourtant la derniere version 2024-11-R1 et j'ai fais un git pull ce matin....

**Comment by dbarzin** [comment]
OK corrigé !
